{
  Project:  AVR Universal Bootloader Download
  File:     tips.pas
  Describe: Sayings.
  Author:   Shaoziyang
  Date:     2007.6
  Version:  3.0
  Web:      http://shaoziyang.googlepages.com
        or  http://shaoziyang.bloger.com.cn (Chinese)
  Email:    shaoziyang@gmail.com
}

const
  MAXTIPCN = 80;
  tipcn: array[0..MAXTIPCN - 1] of string = (
    '学而时习之，不亦悦乎',
    '【文章】 陆游' + #13#10#13#10 + '文章本天成，妙手偶得之。' + #13#10 + '粹然无疵瑕，岂复须人为。' + #13#10 + '君看古彝器，巧拙两无施。' + #13#10 + '汉最近先秦，固已殊淳漓。' + #13#10 + '胡部何为者，豪竹杂哀丝。' + #13#10 + '后夔不复作，千载谁与期？',
    '古人学问无遗力' + #13#10 + '少壮工夫老始成' + #13#10 + '纸上得来终觉浅' + #13#10 + '绝知此事要躬行',
    '沧海观天阔，浮浪平我心',
    '男儿何不带吴钩，' + #13#10 + '收取关山五十州。' + #13#10 + '请君暂上凌烟阁，' + #13#10 + '若个书生万户侯。',
    '【春江花月夜】 张若虚' + #13#10#13#10 + '春江潮水连海平，海上明月共潮生。' + #13#10 + '滟滟随波千万里，何处春江无月明？' + #13#10 + '江流宛转绕芳甸，月照花林皆似霰。' + #13#10 + '空里流霜不觉飞，汀上白沙看不见。' + #13#10 + '江天一色无纤尘，皎皎空中孤月轮。' + #13#10 + '江畔何人初见月？江月何年初照人？' + #13#10 + '人生代代无穷已，江月年年只相似。' + #13#10 + '不知江月待何人，但见长江送流水。' + #13#10 + '白云一片去悠悠，青枫浦上不胜愁。' + #13#10 + '谁家今夜扁舟子？何处相思明月楼？' + #13#10 + '可怜楼上月徘徊，应照离人妆镜台。' + #13#10 + '玉户帘中卷不去，捣衣砧上拂还来。' + #13#10 + '此时相望不相闻，愿逐月华流照君。' + #13#10 + '鸿雁长飞光不度，鱼龙潜跃水成文。' + #13#10 + '昨夜闲潭梦落花，可怜春半不还家。' + #13#10 + '江水流春去欲尽，江潭落月复西斜。' + #13#10 + '斜月沉沉藏海雾，碣石潇湘无限路。' + #13#10 + '不知乘月几人归？落花摇情满江树。',
    '春花秋月何时了，' + #13#10 + '往事知多少。' + #13#10 + '小楼昨夜又东风，' + #13#10 + '故国不堪回首月明中。' + #13#10#13#10 + '雕栏玉砌应犹在，' + #13#10 + '只是朱颜改。' + #13#10 + '问君能有几多愁，' + #13#10 + '恰是一江春水向东流。',
    '滚滚长江东逝水，浪花淘尽英雄。' + #13#10 + '是非成败转头空。青山依旧在，几度夕阳红。' + #13#10#13#10 + '白发渔樵江渚上，惯看秋月春风。' + #13#10 + '一壶浊酒喜相逢。古今多少事，都付笑谈中。',
    '白日依山尽，黄河入海流。欲穷千里目，更上一层楼。',
    '去年今日此门中，' + #13#10 + '人面桃花相映红。' + #13#10 + '人面不知何处去，' + #13#10 + '桃花依旧笑春风。',
    '昔人已乘黄鹤去，此地空馀黄鹤楼。' + #13#10 + '黄鹤一去不复返，白云千载空悠悠。' + #13#10#13#10 + '晴川历历汉阳树，芳草萋萋鹦鹉洲。' + #13#10 + '日暮乡关何处是，烟波江上使人愁。',
    '【满江红】' + #13#10#13#10 + '怒发冲冠，凭栏处，潇潇雨歇。' + #13#10 + '抬望眼，仰天长啸，壮怀激烈。' + #13#10 + '三十功名尘与土，' + #13#10 + '八千里路云和月。' + #13#10 + '莫等闲，白了少年头，空悲切。' + #13#10#13#10 + '靖康耻，犹未雪；' + #13#10 + '臣子恨，何时灭！' + #13#10 + '驾长车踏破贺兰山缺。' + #13#10 + '壮志饥餐胡虏肉，' + #13#10 + '笑谈渴饮匈奴血。' + #13#10 + '待从头，收拾旧山河，朝天阙。',
    '老夫聊发少年狂，左牵黄，右擎苍。' + #13#10 + '锦帽貂裘，千骑卷平冈。' + #13#10 + '欲报倾城随太守，亲射虎，看孙郎。' + #13#10#13#10 + '酒酣胸胆尚开张，鬓微霜，又何妨！' + #13#10 + '持节云中，何日遣冯唐？' + #13#10 + '会挽雕弓如满月，西北望，射天狼。',
    '大梦谁先觉？' + #13#10 + '平生我自知，' + #13#10 + '草堂春睡足，' + #13#10 + '窗外日迟迟。',
    '【侠客行】 李白' + #13#10#13#10 + '赵客缦胡缨，吴钩霜雪明。' + #13#10 + '银鞍照白马，飒沓如流星。' + #13#10 + '十步杀一人，千里不留行。' + #13#10 + '事了拂衣去，深藏身与名。' + #13#10 + '闲过信陵饮，脱剑膝前横。' + #13#10 + '将炙啖朱亥，持觞劝侯嬴。' + #13#10 + '三杯吐然诺，五岳倒为轻。' + #13#10 + '眼花耳热后，意气素霓生。' + #13#10 + '救赵挥金槌，邯郸先震惊。' + #13#10 + '千秋二壮士，烜赫大梁城。' + #13#10 + '纵死侠骨香，不惭世上英。' + #13#10 + '谁能书阁下，白首太玄经。',
    '天地有正气，杂然赋流形。下则为河岳，上则为日星。' + #13#10 + '于人曰浩然，沛乎塞苍冥。皇路当清夷，含和吐明庭。' + #13#10 + '时穷节乃见，一一垂丹青：在齐太史简，在晋董狐笔。' + #13#10 + '在秦张良椎，在汉苏武节；为严将军头，为嵇侍中血，' + #13#10 + '为张睢阳齿，为颜常山舌；或为辽东帽，清操厉冰雪；' + #13#10 + '或为出师表，鬼神泣壮烈。或为渡江楫，慷慨吞胡羯，' + #13#10 + '或为击贼笏，逆竖头破裂。是气所磅礴，凛然万古存。' + #13#10 + '当其贯日月，生死安足论！地维赖以立，天柱赖以尊。' + #13#10 + '三纲实系命，道义为之根。磋余遘阳九，隶也实不力。' + #13#10 + '楚囚缨其冠，传车送穷北。鼎镬甘如馅，求之不可得。' + #13#10 + '阴房冥鬼火，春院閟天黑。牛骥同一皂，鸡栖凤凰食。' + #13#10 + '一朝蒙雾露，分作沟中瘠。如此再寒暑，百沴自辟易。' + #13#10 + '哀哉沮洳场，为我安乐国。岂有他谬巧，阴阳不能贼！' + #13#10 + '顾此耿耿在，仰视浮云白。悠悠我心忧，苍天曷有极！' + #13#10 + '哲人日已远，典刑在夙昔。风檐展书读，古道照颜色。',
    '我住长江头，' + #13#10 + '君住长江尾。' + #13#10 + '日日思君不见君，' + #13#10 + '共饮长江水。',
    '对酒当歌，人生几何？' + #13#10 + '譬如朝露，去日苦多。' + #13#10 + '慨当以慷，忧思难忘。' + #13#10 + '何以解忧，唯有杜康。' + #13#10 + '青青子衿，悠悠我心。' + #13#10 + '但为君故，沉吟至今。',
    '海内存知己，天涯若比邻。',
    '【江上吟】 李白' + #13#10#13#10 + '木兰之枻沙棠舟，玉箫金管坐两头；' + #13#10 + '美酒樽中置千斛，载妓随波任去留。' + #13#10 + '仙人有待乘黄鹤，海客无心随白鸥。' + #13#10 + '屈平辞赋悬日月，楚王台榭空山丘。' + #13#10 + '兴酣落笔摇五岳，诗成啸傲凌沧州；' + #13#10 + '功名富贵若常在，汉水亦应西北流。',
    '众里寻他千百度，' + #13#10 + '蓦然回首，' + #13#10 + '那人却在，' + #13#10 + '灯火阑珊处。',
    '它山之石，可以攻玉。',
    '昨夜星辰昨夜风，' + #13#10 + '画楼西畔桂堂东。' + #13#10 + '身无彩凤双飞翼，' + #13#10 + '心有灵犀一点通。',
    '温故而知新',
    '【水调歌头】' + #13#10#13#10 + '明月几时有，把酒问青天。' + #13#10 + '不知天上宫阙，今夕是何年？' + #13#10 + '我欲乘风归去，又恐琼楼玉宇，' + #13#10 + '高处不胜寒。' + #13#10 + '起舞弄清影，何似在人间！' + #13#10#13#10 + '转朱阁，低绮户，照无眠。' + #13#10 + '不应有恨，何事长向别时圆？' + #13#10 + '人有悲欢离合，月有阴晴圆缺，' + #13#10 + '此事古难全。' + #13#10 + '但愿人长久，千里共婵娟。',
    '知我者，谓我心忧，' + #13#10 + '不知我者，谓我何求。',
    '朝闻道，夕死可矣。',
    '君子坦荡荡，小人长戚戚。',
    '衣带渐宽终不悔',
    '学而不思则罔' + #13#10 + '思而不学则殆',
    '富贵不能淫' + #13#10 + '贫贱不能移' + #13#10 + '威武不能屈',
    '穷则独善其身，达则兼济天下。',
    '路漫漫其修远兮，吾将上下而求索。',
    '同声相应，同气相求。',
    '仁者见仁，智者见智。',
    '学然后知不足，教然后知困。',
    '天道无亲，常与善人。',
    '玉不琢，不成器；' + #13#10 + '人不学，不知道。',
    '三人行，必有我师焉：' + #13#10 + '择其善而从之，' + #13#10 + '其不善者而改之。',
    '大学之道，在明明德，在亲民，在止于至善。',
    '知止而后有定，' + #13#10 + '定而后能静，' + #13#10 + '静而后能安，' + #13#10 + '安而后能虑，' + #13#10 + '虑而后能得。',
    '物格而后知至，' + #13#10 + '知至而后意诚，' + #13#10 + '意诚而后心正，' + #13#10 + '心正而后身修，' + #13#10 + '身修而后家齐，' + #13#10 + '家齐而后国治，' + #13#10 + '国治而后天下平。 ',
    '人谁无过？过而能改，善莫大焉。',
    '知之为知之，不知为不知，是知也。',
    '知之者不如好之者，好之者不如乐之者。',
    '不鸣则已，一鸣惊人。',
    '绳锯木断，水滴石穿。',
    '读书百遍，其义自见。',
    '欲穷千里目，更上一层楼。',
    '读书破万卷，下笔如有神。',
    '会当凌绝顶，一览众山小。',
    '登高壮观天地间，大江茫茫去不还',
    '两句三年得，一吟双泪流。',
    '山不在高，水不在深',
    '千里之行，始于足下',
    '不识庐山真面目，只缘身在此山中。',
    '业精于勤荒于嬉，行成于思而毁于随。',
    '十年磨一剑，' + #13#10 + '霜刃未曾试。' + #13#10 + '今日把示君，' + #13#10 + '谁有不平事。',
    '天生我材必有用，千金散尽复还来。',
    '先天下之忧而忧，后天下之乐而乐。',
    '运筹帷幄，在乎一心',
    '书到用时方绝少' + #13#10 + '事非经过不知难',
    '天行健，君子以自强不息。',
    '为了保护Bootloader区程序不被意外改写，应当设置BLB1熔丝位为' + #13#10 + '模式2或3，禁止对Bootloader区进行写。',
    '本软件可以方便的进行HEX格式和BIN格式的转换',
    '本软件只有在下载时才占用串口，下载完成后自动释放串口',
    '本软件带有一个自动代码生成工具，可以工具用户设置的参数' + #13#10 + '自动生成配置文件',
    '下载软件时间片的大小应当比单片机的稍微大一点',
    '单片机程序中如果加入复位命令，可以通过下载软件对单片机' + #13#10 + '进行复位，这样可以方便进行下载',
    '如果选择‘自动判断下载数据长度’，那么将只下载给定的数' + #13#10 + '据，空余部分将不处理。这样下载速度比较快，' + #13#10 + '但是在意外情况下程序跑飞后会执行以前的程序。',
    '软件对HEX格式和BIN格式的处理做了优化，' + #13#10 + '所以载入和转换的速度很快。',
    '软件自动将HEX文件中的数据转换为缓冲区的倍速，' + #13#10 + '并且根据缓冲区的大小自动补足数据。',
    '用户可以将未用的空间填充，提高程序的抗干扰能力。' + #13#10 + '默认的填充数据是<FF CF>，即一个死循环。',
    '如果下载后不能自动跳回到用户程序，请检查熔丝位的' + #13#10 + '设置。还可以查看反汇编中跳转语句是否正确（有的版' + #13#10 + '本的编译器会出问题）。',
    '当Bootloader运行有错误时，可以先试试软件中带有的' + #13#10 + 'Test程序，并在超级终端中实验。如果Test能正常运行，' + #13#10 + '那么Bootloader一般就没有太大的问题了。',
    '填充未用空间，可以提高程序的抗干扰能力。一般填充 "jmp 0" 或' + #13#10 + 'while(1)死循环这样的命令。注意一般填充双字节。',
    '你可以直接修改BIN缓冲区的内容。',
    'AVR通用Bootloader可以支持Flash写入校验，' + #13#10 + '可以极大的提高可靠性。',
    '本软件使用Delphi开发，使用了CPort、SynEdit、btBeep' + #13#10 + 'HighResTimer、HexEdit等控件',
    ''
    );

  MAXTIPEN = 261;
  tipen: array[0..MAXTIPEN - 1] of string = (
    'A bad workman always blames his tools.',
    'A brave man may fall, but he cannot yield.',
    'A burnt child dreads the fire.',
    'A constant guest is never welcome.',
    'A contented mind is a perpetual feast.',
    'A cracked bell can never sound well.',
    'A fair death honors the whole life.',
    'A fox may grow grey, but never good.',
    'A friend in need is a friend in indeed.',
    'A friend is easier lost than found.',
    'A good beginning is half the battle.',
    'A good book is the best of friends, the same today and forever.',
    'A good name is sooner lost than won.',
    'A good winter brings a good summer.',
    'A house divided against itself cannot stand.',
    'A lazy youth, a lousy age.',
    'A little help is worth a deal of pity.',
    'A little is better than none.',
    'A little learning is a dangerous thing.',
    'A little pot is soon hot.',
    'A man can only die once.',
    'A man who has friends must show himself friendly.',
    'A merry heart goes all the way.',
    'A miss is as good as a mile.',
    'A penny saved is a penny earned.',
    'A rolling stone gathers no moss.',
    'A secret between more than two is no secret.',
    'A smooth sea never made a skillful mariner.',
    'A still tongue makes a wise head.',
    'A straw will show which way the wind blows.',
    'A tale never loses in the telling.',
    'A thing of beauty is a joy for ever.',
    'A thing you don''t want is dear at any price.',
    'A true jest is no jest.',
    'A useful trade is amine of gold.',
    'A willful man must have his way.',
    'A wonder lasts but nine days.',
    'A work ill done must be twice done.',
    'Achievement is founded on diligence and wasted upon recklessness.',
    'Actions speak louder than words.',
    'Adversity makes a man wise,not rich.',
    'After a storm comes a calm.',
    'After dinner sit a while; after supper walk a mile.',
    'All are not friends that speak us fair.',
    'All his geese are swans.',
    'All is not  gain that is got into the purse.',
    'All roads lead to Rome.',
    'All that glitters is not gold.',
    'All things are difficult before they are easy.',
    'All work and no play makes Jack a dull boy.',
    'All''s well that ends well.',
    'An empty sack cannot stand upright.',
    'An evil lesson is soon learned. ',
    'As good lost as found.',
    'Bad excuses are worse than none.',
    'Be just before you are generous.',
    'Beauty is but skin-deep.',
    'Better early than late.',
    'Better go to heaven in rags than to hell in embroidery.',
    'Better late than never.',
    'Better lose the saddle than the horse.',
    'Birds of a feather flock together.',
    'Birth is much, but breeding is more.',
    'Blessed is he that expects nothing, for he shall never be disappointed.',
    'Brevity is the soul of wit.',
    'Cheats never prosper.',
    'Children and fools tell the truth.',
    'Circumstances alter cases.',
    'Cleanliness is next to godliness.',
    'Coming events cast their shadows before.',
    'Constant dropping wears away a stone.',
    'Content is better than riches.',
    'Cowards die many times before their deaths.',
    'Diligence is the mother of good luck.',
    'Do not count your chickens before they are hatched.',
    'Do not cry for the moon.',
    'Do not keep all the eggs in one basket.',
    'Do not try to teach your grandmother to such eggs.',
    'Don''t cut down the tree that gives you shade.',
    'Don''t put the cart before the horse.',
    'Dreams go by contraries.',
    'Early sow, early mow.',
    'Early to bed, early to rise, make a man healthy, wealthy, and wise.',
    'Easier said than done.',
    'Easy come, easy go.',
    'Empty vessels make the most noise.',
    'Every bean hath its black.',
    'Every little helps.',
    'Every little makes a mickle.',
    'Every why has a where fore.',
    'Everything comes to him who waits.',
    'Example is better than precept.',
    'Experience is the best teacher.',
    'Experience is the father of wisdom.',
    'Experience must be bought.',
    'Extremes are dangerous.',
    'Facts speak louder than words.',
    'Failure teaches success.',
    'First impressions are most lasting.',
    'Fools build houses and wise men live in them.',
    'Fool''s haste is no speed.',
    'Fortune favours the brave.',
    'Fortune favours those who use their judgement.',
    'Friendship should not be all on one side.',
    'Give him an inch and he will take a yard.',
    'God helps those who help themselves.',
    'Gold will not buy everything.',
    'Good advice is beyond price.',
    'Good advice is harsh to the ear.',
    'Good counsel has no price.',
    'Good health is above wealth.',
    'Grasp all, lose all.',
    'Harm watch, harm catch.',
    'Haste makes waste.',
    'He is happy that he thinks himself so.',
    'He is only bright that shines by himself.',
    'He is rich that has few wants.',
    'He knows most who speaks least.',
    'He laughs best who laughs last.',
    'He that begins many things , finishes but few.',
    'He that falls today may rise tomorrow.',
    'He that is full of himself is very empty.',
    'He that travels far knows much.',
    'He who is ashamed of asking is ashamed of learning.',
    'He who mistrusts most should be trusted least.',
    'He who plays with fire gets burnt.',
    'He who rides on a tiger can never dismount.',
    'Hear all parties.',
    'Honesty is the best policy.',
    'Idleness is the root of all evil.',
    'If we dream, everything is possible.',
    'If you run after two hares, you will catch neither.',
    'If you want a thing well done, do it yourself.',
    'Ill news flies apace.',
    'In the end, things will mend.',
    'It is better to be alone than in bad company.',
    'It is better to do well than to say well.',
    'It is easier to get money than to keep it.',
    'It is good to have friends in trouble.',
    'It is never too late to learn.',
    'It is never too late to mend.',
    'It is the first step that is troublesome.',
    'Jack of all trades, master of none.',
    'Joy surfeited turns to sorrow.',
    'Judge not a book by its cover.',
    'Judge not from appearance.',
    'Justice has long arms.',
    'Keep your mouth shut and your ears open.',
    'Kill not the goose that lays the golden eggs.',
    'Knowledge in youth is wisdom in age.',
    'Knowledge is a treasure, but practice is the key to it.',
    'Knowledge is no burden.',
    'Knowledge is power.',
    'Knowledge is the food of the soul.',
    'Knowledge makes humble; ignorance make proud.',
    'Learning is the eye of the mind.',
    'Learning makes a good man better, and an ill man worse.',
    'Learn not, and know not.',
    'Learn to say before you sing.',
    'Lies have short legs.',
    'Life is not all beer and skittles.',
    'Lightly come, lightly go.',
    'Little and often fills the purse.',
    'Little drops of water make the mighty ocean.',
    'Look before you leap.',
    'Lookers-on see most of the game.',
    'Lost time is never found again.',
    'Love me little, love me long.',
    'Make hay while the sun shines.',
    'Man proposes, God disposes.',
    'Man struggles upwards; water flows downwards.',
    'Many drops make a shower.',
    'Misfortune tests the sincerity of friends.',
    'Money is the root of all evil.',
    'More haste, less speed.',
    'Necessity is the mother of invention.',
    'Never buy a pig in a poke.',
    'Never do things by halves.',
    'Never judge from appearances.',
    'Never put off till tomorrow what you can do today.',
    'No bees, no honey; no work, no money.',
    'No cross, no crown.',
    'No gains without pains.',
    'No news is good news.',
    'No pains, no gains.',
    'No way is impossible to courage.',
    'Nothing is cheap if you don''t want it.',
    'Nothing is difficult to the man who will try.',
    'Nothing seek, nothing find.',
    'Nothing venture, nothing have.',
    'Observation is the best teacher.',
    'Of nothing comes nothing.',
    'Once a thief, always a thief.',
    'One flower makes no garland.',
    'One man''s fault is another man''s lesson.',
    'One today is worth two tomorrow.',
    'Out of sight, out of mind.',
    'Pain past is pleasure.',
    'Practice makes perfect.',
    'Practise what you preach.',
    'Prevention is better than cure.',
    'Ragged colts may make fine horses.',
    'Reason is the guide and light of life.',
    'Rome was not build in a day',
    'Satan always finds work for idle hands.',
    'Saving is getting.',
    'Say nothing, think the more.',
    'Saying and doing are two things.',
    'Second thoughts are best.',
    'Self do, self have.',
    'Short pleasure, long lament.',
    'So many men, so many minds.',
    'Soft fire makes sweet malt.',
    'Soon got, soon spent.',
    'Soon learnt, soon forgotten.',
    'Speech is silver; silence is golden.',
    'Sweet are the uses of adversity.',
    'Tall trees catch much wind.',
    'The bait hides the hook.',
    'The cheap buyer takes bad meat.',
    'The day has eyes, the night has ears.',
    'The early bird catches the worm.',
    'The fire is the test of gold; adversity of strong men.',
    'The frog in the well knows nothing of the great ocean.',
    'The future becomes the present if we fight for it.',
    'The love of money is the root of all evil.',
    'The more a man learns, the more he sees his ignorance.',
    'The more haste, the less speed.',
    'The more you have, the more you want.',
    'The proof of the pudding is in the eating.',
    'The world is his who enjoys it.',
    'The years teach much which the days never know.',
    'Time gives good advice.',
    'Time works wonders.',
    'Two heads are better than one.',
    'Union is strength.',
    'Use makes perfectness.',
    'Venture a small fish to catch a great one.',
    'Very often a change of self is needed more than a change of scene.',
    'Virtue is a jewel of great price.',
    'Virtue is fairer far than beauty.',
    'Virtue is its own reward.',
    'Walls have ears.',
    'Waste not, want not.',
    'Wasting time is robbing oneself.',
    'Water-drops, gathered together, become a sea;' + #13#10 + 'experience, gathered together, becomes knowledge.',
    'Weak things united become strong.',
    'Well begun is half done.',
    'What is done by night appears by day.',
    'When children stand quiet, they have done some harm.',
    'When one will not, two cannot quarrel.',
    'When the cat is away, the mice will play.',
    'Where there is a will there is a way.',
    'Where there is smoke, there is fire.',
    'Where there''s life there''s hope.',
    'Will is power.',
    'Wisdom is a good purchase though we pay dear for it.',
    'Wise men are silent; fools talk.',
    'You are never too old to learn.',
    'You never know till you have tried.',
    ''
    );


