/*
	Led driver module.

	Phase & Freq correct PWM mode Tmr1
	Resolution (top) defined by OCR1A
	Output generated by OCR1B (pin 16, mod required)
	Minimum frame rate with prescaler of 1=15.259 fps
	OCR1A & OCR1B updated at bottom

OCR1A isr occurs 1/2 way through displaying plane 7 (top)

	(At 200Hz frame rate, we have ~5000 clock cycles to complete this ISR)
	
	copy next frame into output buffer
	copy row intensities into output buffer.
	copy frame rate (top/OCR1A) value.

	load plane 0 data into shift registers (8MHz clock)
	load plane 0 intensity into OCR1B
	
	Signal frame sync to main application.

TOV1 isr occurs at END of plane N (bottom), start of plane N+1

	latch data into output registers
	switch fets to display plane 0

OCR1A isr occurs 1/2 way through displaying plane N(1-6) (top)

	load plane N+1 data into shift registers (8MHz clock)
	load plane N+1 intensity into OCR1B

Columbs should be wired so that bitmap:

	Bit 7 - 0 runs left to right
	Byte 0 - 7 runs front to back
	(this follows the view of a byte, in terms of shift left, shift right)

The planes should be wired so that plane 0 -7 runs top to bottom

The actual co-ordinate system X, Y, Z

	0, 0, 0 is LEFT, TOP, CLOSEST
	7, 7, 7 is RIGHT, BOTTOM, FURTHEST

SPI outputs MSB of byte 0 first, and LSB of byte 7 last, so:
	co-ordinate 0, 0, 0 is drain7 on last shift register
	co-ordinate 7, 0, 0 is drain0 on last shift register
	co-ordinate 0, 0, 7 is drain7 on first shift register
	co-ordinate 7, 0, 7 is drain0 on first shift register

*/

	#include "includes.h"

//********************************************************************************************************
// Configurable defines
//********************************************************************************************************

//	Called while waiting for a frame sync
	#define WAIT_LOOP		main_fly
	
	#define LED_LATCH_BIT	PF7
	#define LED_LATCH_PORT	PORTF
	#define LED_LATCH_DDR	DDRF
	
	//planes 0-7 must be on bits 0-7
	#define PLANES_PORT	PORTC
	#define PLANES_DDR	DDRC

	#define	SS_PORT		PORTB
	#define SS_BIT		PB0
	#define SS_DDR		DDRB

	#define MISO_BIT	PB3
	#define MISO_DDR	DDRB

	#define MOSI_BIT	PB2
	#define MOSI_DDR	DDRB

	#define SCK_BIT		PB1
	#define SCK_DDR		DDRB
	
	#define LED_EN_BIT	PB6
	#define LED_EN_DDR	DDRB

	//used to keep control if application gives us a 0 or unreasonably low plane time
	#define MINIMUM_PLANE_TIME	4000

//********************************************************************************************************
// Local defines
//********************************************************************************************************

//********************************************************************************************************
// Public variables
//********************************************************************************************************

	unsigned char 			led_frame_bitmap[64];	//8x8x8 bitmap

//********************************************************************************************************
// Private variables
//********************************************************************************************************

	static volatile char	frame_sync = FALSE;	//set just after 1/2 way through the last plane of each frame

	static unsigned int		plane_period[8];	//actual values used in CCR1B for each plane during next frame
	static unsigned int		frame_time;			//TOP counter value, determines frame rate for next frame

	static unsigned char 	plane_intensity[8];	//user desired intensity for next frame (0-255), used to re-calc plane_period when changing frame rates

	static unsigned char	plane_current=7;

	static unsigned char	output_bitmap[64];			//bitmap for current frame
	static int				output_plane_period[8];		//actual values used in CCR1B for current frame

	//display upside down if true, this is done by flipping dimensions Y and Z
	static char				flip=FALSE;

//********************************************************************************************************
// Private prototypes
//********************************************************************************************************

//********************************************************************************************************
// Public functions
//********************************************************************************************************

void led_init(void)
{
	unsigned char tempchar;

	LED_LATCH_PORT &=~_BV(LED_LATCH_BIT);
	LED_LATCH_DDR |= _BV(LED_LATCH_BIT);

	MOSI_DDR	|= _BV(MOSI_BIT);
	SCK_DDR		|= _BV(SCK_BIT);
	SS_PORT		|= _BV(SS_BIT);
	SS_DDR		|= _BV(SS_BIT);

	//Timer 1
	TCCR1A |= _BV(COM1B1) + _BV(WGM10);
	TCCR1B |= _BV(WGM13) + _BV(CS10);

	//SPI
	SPCR		|= _BV(SPE) + _BV(MSTR);	// mode 0
	SPSR		|= _BV(SPI2X);				// Fosc/2 clock output

	//Planes
	PLANES_PORT = 0xFF;
	PLANES_DDR	= 0xFF;

	//LED Enable
	LED_EN_DDR |=_BV(LED_EN_BIT);

	//ISR's
	TIMSK |= _BV(OCIE1A) + _BV(TOIE1);

	//default frame
	memset(led_frame_bitmap, 0, 64);		// All off

	led_framerate(60);						// 60Hz frame rate
	tempchar=0;
	while(tempchar !=8)
		led_plane_intensity(tempchar++, 128);	// 0 intensity on all planes

	//default output buffer
	memcpy(output_bitmap, led_frame_bitmap, 64);
	memcpy(output_plane_period, plane_period, 8);

	OCR1A = frame_time;
}

void led_flip(char x)
{
	flip = x;
}

void led_shutdown(void)
{
	//disable int's
	TIMSK &=~( _BV(OCIE1A) + _BV(TOIE1));

	//all planes off
	PLANES_PORT = 0xFF;
	PLANES_DDR	= 0xFF;
}

void led_framerate(int rate)
{
//	Fpwm = 16MHz / (2*TOP)
//	TOP = F_CPU/Fpwm/2
//	TOP = F_CPU/Frate/16

	unsigned long top = F_CPU / 16ul;
	unsigned char tempchar;

	if(rate < 16)
		rate=16;
		
	top /= rate;
	
	frame_time = (unsigned int)top;

	//re-calc intensity periods after changing frame rate
	tempchar=0;
	while(tempchar !=8)
	{
		led_plane_intensity(tempchar, plane_intensity[tempchar]);
		tempchar++;
	};
}

void led_plane_intensity(unsigned char plane, unsigned char intensity)
{
	unsigned int tempint;
	unsigned long templong;

	tempint = intensity * intensity;
	templong = (unsigned long)tempint * (unsigned long)frame_time;
	templong >>= 16;

	plane_period[plane] = frame_time - (unsigned int)templong;

	plane_intensity[plane] = intensity;	//remember setting se we can re-calc if frame rate changes
}

void led_plane_intensity_all(unsigned char intensity)
{
	unsigned int tempint;
	unsigned long templong;

	tempint = intensity * intensity;
	templong = (unsigned long)tempint * (unsigned long)frame_time;
	templong >>= 16;

	plane_period[0] = frame_time - (unsigned int)templong;
	plane_intensity[0] = intensity;	//remember setting so we can re-calc if frame rate changes
	plane_period[1] = frame_time - (unsigned int)templong;
	plane_intensity[1] = intensity;	//remember setting so we can re-calc if frame rate changes
	plane_period[2] = frame_time - (unsigned int)templong;
	plane_intensity[2] = intensity;	//remember setting so we can re-calc if frame rate changes
	plane_period[3] = frame_time - (unsigned int)templong;
	plane_intensity[3] = intensity;	//remember setting so we can re-calc if frame rate changes
	plane_period[4] = frame_time - (unsigned int)templong;
	plane_intensity[4] = intensity;	//remember setting so we can re-calc if frame rate changes
	plane_period[5] = frame_time - (unsigned int)templong;
	plane_intensity[5] = intensity;	//remember setting so we can re-calc if frame rate changes
	plane_period[6] = frame_time - (unsigned int)templong;
	plane_intensity[6] = intensity;	//remember setting so we can re-calc if frame rate changes
	plane_period[7] = frame_time - (unsigned int)templong;
	plane_intensity[7] = intensity;	//remember setting so we can re-calc if frame rate changes
}

// byte address = y * 8 + z
// bit address 7-0 is x 0-7 (reversed)
void led_point(unsigned char x, unsigned char y, unsigned char z, unsigned char on_off)
{
	if( ((x|y|z)&0xF8) == 0)	//check range
	{
		if(on_off)
			led_frame_bitmap[z+(y<<3)] |= 0x80>>x;
		else
			led_frame_bitmap[z+(y<<3)] &=~(0x80>>x);
	};
}

void led_blank(void)
{
	memset(led_frame_bitmap, 0, 64);
}

/* maximum of a and b */
#define MAX(a,b) (((a)>(b))?(a):(b))

/* absolute value of a */
#define ABS(a) (((a)<0) ? -(a) : (a))

/* take sign of a, either -1, 0, or 1 */
#define ZSGN(a) (((a)<0) ? -1 : (a)>0 ? 1 : 0)

void led_line(int x1, int y1, int z1, int x2, int y2, int z2, unsigned char on_off)
{
    int xd, yd, zd;
    int x, y, z;
    int ax, ay, az;
    int sx, sy, sz;
    int dx, dy, dz;

    dx = x2 - x1;
    dy = y2 - y1;
    dz = z2 - z1;

    ax = ABS(dx) << 1;
    ay = ABS(dy) << 1;
    az = ABS(dz) << 1;

    sx = ZSGN(dx);
    sy = ZSGN(dy);
    sz = ZSGN(dz);

    x = x1;
    y = y1;
    z = z1;

    if (ax >= MAX(ay, az))            /* x dominant */
    {
        yd = ay - (ax >> 1);
        zd = az - (ax >> 1);
        for (;;)
        {
            led_point(x, y, z, on_off);
            if (x == x2)
            {
                return;
            }

            if (yd >= 0)
            {
                y += sy;
                yd -= ax;
            }

            if (zd >= 0)
            {
                z += sz;
                zd -= ax;
            }

            x += sx;
            yd += ay;
            zd += az;
        }
    }
    else if (ay >= MAX(ax, az))            /* y dominant */
    {
        xd = ax - (ay >> 1);
        zd = az - (ay >> 1);
        for (;;)
        {
            led_point(x, y, z, on_off);
            if (y == y2)
            {
                return;
            }

            if (xd >= 0)
            {
                x += sx;
                xd -= ay;
            }

            if (zd >= 0)
            {
                z += sz;
                zd -= ay;
            }

            y += sy;
            xd += ax;
            zd += az;
        }
    }
    else if (az >= MAX(ax, ay))            /* z dominant */
    {
        xd = ax - (az >> 1);
        yd = ay - (az >> 1);
        for (;;)
        {
            led_point(x, y, z, on_off);
            if (z == z2)
            {
                return;
            }

            if (xd >= 0)
            {
                x += sx;
                xd -= az;
            }

            if (yd >= 0)
            {
                y += sy;
                yd -= az;
            }

            z += sz;
            xd += ax;
            yd += ay;
        }
    }
}

void led_waitframe(unsigned int x)
{
	while(x--)
	{
		frame_sync=FALSE;
		while(!frame_sync)
			WAIT_LOOP();
	};
}

//scroll a horizontal plane back
void led_plane_y_back(unsigned char y)
{
	y<<=3;
	memmove(&led_frame_bitmap[y+1], &led_frame_bitmap[y], 7);
	led_frame_bitmap[y]=0;
}

//scroll a horizontal plane forwards
void led_plane_y_forward(unsigned char y)
{
	y<<=3;
	memmove(&led_frame_bitmap[y], &led_frame_bitmap[y+1], 7);
	led_frame_bitmap[y+7]=0;
}

//scroll a horizontal plane left
void led_plane_y_left(unsigned char y)
{
	y<<=3;
	
	led_frame_bitmap[y++]<<=1;
	led_frame_bitmap[y++]<<=1;
	led_frame_bitmap[y++]<<=1;
	led_frame_bitmap[y++]<<=1;
	led_frame_bitmap[y++]<<=1;
	led_frame_bitmap[y++]<<=1;
	led_frame_bitmap[y++]<<=1;
	led_frame_bitmap[y]<<=1;
}

//scroll a horizontal plane right
void led_plane_y_right(unsigned char y)
{
	y<<=3;
	
	led_frame_bitmap[y++]>>=1;
	led_frame_bitmap[y++]>>=1;
	led_frame_bitmap[y++]>>=1;
	led_frame_bitmap[y++]>>=1;
	led_frame_bitmap[y++]>>=1;
	led_frame_bitmap[y++]>>=1;
	led_frame_bitmap[y++]>>=1;
	led_frame_bitmap[y]>>=1;
}

//scroll a verticle plane running in the x direction down
void led_plane_z_down(unsigned char z)
{
	unsigned char *a, *b;
	a = &led_frame_bitmap[z+56];
	b = &led_frame_bitmap[z+48];
	
	*a=*b;	//7=6
	a-=16;
	*b=*a;	//6=5
	b-=16;
	*a=*b;	//5=4
	a-=16;
	*b=*a;	//4=3
	b-=16;
	*a=*b;	//3=2
	a-=16;
	*b=*a;	//2=1
	b-=16;
	*a=*b;	//1=0
	*b=0;	//0=blank
}


//scroll a verticle plane running in the x direction up
void led_plane_z_up(unsigned char z)
{
	unsigned char *a, *b;
	a = &led_frame_bitmap[z];
	b = &led_frame_bitmap[z+8];
	
	*a=*b;	//0=1
	a+=16;
	*b=*a;	//1=2
	b+=16;
	*a=*b;	//2=3
	a+=16;
	*b=*a;	//3=4
	b+=16;
	*a=*b;	//4=5
	a+=16;
	*b=*a;	//5=6
	b+=16;
	*a=*b;	//6=7
	*b=0;	//7=blank
}

//scroll a verticle plane 1 pixel backwards, new front columb is blank
void led_plane_x_back(unsigned char x)
{
	unsigned char bit_on;
	unsigned char bit_off;
	
	bit_on = 0x80>>x;
	bit_off = ~bit_on;

	//shift back 1

	led_frame_bitmap[7] &=bit_off;
	led_frame_bitmap[15] &=bit_off;
	led_frame_bitmap[23] &=bit_off;
	led_frame_bitmap[31] &=bit_off;
	led_frame_bitmap[39] &=bit_off;
	led_frame_bitmap[47] &=bit_off;
	led_frame_bitmap[55] &=bit_off;
	led_frame_bitmap[63] &=bit_off;

	if(led_frame_bitmap[6] & bit_on)
		led_frame_bitmap[7] |=bit_on;
	if(led_frame_bitmap[14] & bit_on)
		led_frame_bitmap[15] |=bit_on;
	if(led_frame_bitmap[22] & bit_on)
		led_frame_bitmap[23] |=bit_on;
	if(led_frame_bitmap[30] & bit_on)
		led_frame_bitmap[31] |=bit_on;
	if(led_frame_bitmap[38] & bit_on)
		led_frame_bitmap[39] |=bit_on;
	if(led_frame_bitmap[46] & bit_on)
		led_frame_bitmap[47] |=bit_on;
	if(led_frame_bitmap[54] & bit_on)
		led_frame_bitmap[55] |=bit_on;
	if(led_frame_bitmap[62] & bit_on)
		led_frame_bitmap[63] |=bit_on;

	led_frame_bitmap[6] &=bit_off;
	led_frame_bitmap[14] &=bit_off;
	led_frame_bitmap[22] &=bit_off;
	led_frame_bitmap[30] &=bit_off;
	led_frame_bitmap[38] &=bit_off;
	led_frame_bitmap[46] &=bit_off;
	led_frame_bitmap[54] &=bit_off;
	led_frame_bitmap[62] &=bit_off;

	if(led_frame_bitmap[5] & bit_on)
		led_frame_bitmap[6] |= bit_on;
	if(led_frame_bitmap[13] & bit_on)
		led_frame_bitmap[14] |= bit_on;
	if(led_frame_bitmap[21] & bit_on)
		led_frame_bitmap[22] |= bit_on;
	if(led_frame_bitmap[29] & bit_on)
		led_frame_bitmap[30] |= bit_on;
	if(led_frame_bitmap[37] & bit_on)
		led_frame_bitmap[38] |= bit_on;
	if(led_frame_bitmap[45] & bit_on)
		led_frame_bitmap[46] |= bit_on;
	if(led_frame_bitmap[53] & bit_on)
		led_frame_bitmap[54] |= bit_on;
	if(led_frame_bitmap[61] & bit_on)
		led_frame_bitmap[62] |= bit_on;

	led_frame_bitmap[5] &=bit_off;
	led_frame_bitmap[13] &=bit_off;
	led_frame_bitmap[21] &=bit_off;
	led_frame_bitmap[29] &=bit_off;
	led_frame_bitmap[37] &=bit_off;
	led_frame_bitmap[45] &=bit_off;
	led_frame_bitmap[53] &=bit_off;
	led_frame_bitmap[61] &=bit_off;

	if(led_frame_bitmap[4] & bit_on)
		led_frame_bitmap[5] |= bit_on;
	if(led_frame_bitmap[12] & bit_on)
		led_frame_bitmap[13] |= bit_on;
	if(led_frame_bitmap[20] & bit_on)
		led_frame_bitmap[21] |= bit_on;
	if(led_frame_bitmap[28] & bit_on)
		led_frame_bitmap[29] |= bit_on;
	if(led_frame_bitmap[36] & bit_on)
		led_frame_bitmap[37] |= bit_on;
	if(led_frame_bitmap[44] & bit_on)
		led_frame_bitmap[45] |= bit_on;
	if(led_frame_bitmap[52] & bit_on)
		led_frame_bitmap[53] |= bit_on;
	if(led_frame_bitmap[60] & bit_on)
		led_frame_bitmap[61] |= bit_on;

	led_frame_bitmap[4] &=bit_off;
	led_frame_bitmap[12] &=bit_off;
	led_frame_bitmap[20] &=bit_off;
	led_frame_bitmap[28] &=bit_off;
	led_frame_bitmap[36] &=bit_off;
	led_frame_bitmap[44] &=bit_off;
	led_frame_bitmap[52] &=bit_off;
	led_frame_bitmap[60] &=bit_off;

	if(led_frame_bitmap[3] & bit_on)
		led_frame_bitmap[4] |= bit_on;
	if(led_frame_bitmap[11] & bit_on)
		led_frame_bitmap[12] |= bit_on;
	if(led_frame_bitmap[19] & bit_on)
		led_frame_bitmap[20] |= bit_on;
	if(led_frame_bitmap[27] & bit_on)
		led_frame_bitmap[28] |= bit_on;
	if(led_frame_bitmap[35] & bit_on)
		led_frame_bitmap[36] |= bit_on;
	if(led_frame_bitmap[43] & bit_on)
		led_frame_bitmap[44] |= bit_on;
	if(led_frame_bitmap[51] & bit_on)
		led_frame_bitmap[52] |= bit_on;
	if(led_frame_bitmap[59] & bit_on)
		led_frame_bitmap[60] |= bit_on;

	led_frame_bitmap[3] &=bit_off;
	led_frame_bitmap[11] &=bit_off;
	led_frame_bitmap[19] &=bit_off;
	led_frame_bitmap[27] &=bit_off;
	led_frame_bitmap[35] &=bit_off;
	led_frame_bitmap[43] &=bit_off;
	led_frame_bitmap[51] &=bit_off;
	led_frame_bitmap[59] &=bit_off;

	if(led_frame_bitmap[2] & bit_on)
		led_frame_bitmap[3] |= bit_on;
	if(led_frame_bitmap[10] & bit_on)
		led_frame_bitmap[11] |= bit_on;
	if(led_frame_bitmap[18] & bit_on)
		led_frame_bitmap[19] |= bit_on;
	if(led_frame_bitmap[26] & bit_on)
		led_frame_bitmap[27] |= bit_on;
	if(led_frame_bitmap[34] & bit_on)
		led_frame_bitmap[35] |= bit_on;
	if(led_frame_bitmap[42] & bit_on)
		led_frame_bitmap[43] |= bit_on;
	if(led_frame_bitmap[50] & bit_on)
		led_frame_bitmap[51] |= bit_on;
	if(led_frame_bitmap[58] & bit_on)
		led_frame_bitmap[59] |= bit_on;

	led_frame_bitmap[2] &=bit_off;
	led_frame_bitmap[10] &=bit_off;
	led_frame_bitmap[18] &=bit_off;
	led_frame_bitmap[26] &=bit_off;
	led_frame_bitmap[34] &=bit_off;
	led_frame_bitmap[42] &=bit_off;
	led_frame_bitmap[50] &=bit_off;
	led_frame_bitmap[58] &=bit_off;

	if(led_frame_bitmap[1] & bit_on)
		led_frame_bitmap[2] |= bit_on;
	if(led_frame_bitmap[9] & bit_on)
		led_frame_bitmap[10] |= bit_on;
	if(led_frame_bitmap[17] & bit_on)
		led_frame_bitmap[18] |= bit_on;
	if(led_frame_bitmap[25] & bit_on)
		led_frame_bitmap[26] |= bit_on;
	if(led_frame_bitmap[33] & bit_on)
		led_frame_bitmap[34] |= bit_on;
	if(led_frame_bitmap[41] & bit_on)
		led_frame_bitmap[42] |= bit_on;
	if(led_frame_bitmap[49] & bit_on)
		led_frame_bitmap[50] |= bit_on;
	if(led_frame_bitmap[57] & bit_on)
		led_frame_bitmap[58] |= bit_on;

	led_frame_bitmap[1] &=bit_off;
	led_frame_bitmap[9] &=bit_off;
	led_frame_bitmap[17] &=bit_off;
	led_frame_bitmap[25] &=bit_off;
	led_frame_bitmap[33] &=bit_off;
	led_frame_bitmap[41] &=bit_off;
	led_frame_bitmap[49] &=bit_off;
	led_frame_bitmap[57] &=bit_off;

	if(led_frame_bitmap[0] & bit_on)
		led_frame_bitmap[1] |= bit_on;
	if(led_frame_bitmap[8] & bit_on)
		led_frame_bitmap[9] |= bit_on;
	if(led_frame_bitmap[16] & bit_on)
		led_frame_bitmap[17] |= bit_on;
	if(led_frame_bitmap[24] & bit_on)
		led_frame_bitmap[25] |= bit_on;
	if(led_frame_bitmap[32] & bit_on)
		led_frame_bitmap[33] |= bit_on;
	if(led_frame_bitmap[40] & bit_on)
		led_frame_bitmap[41] |= bit_on;
	if(led_frame_bitmap[48] & bit_on)
		led_frame_bitmap[49] |= bit_on;
	if(led_frame_bitmap[56] & bit_on)
		led_frame_bitmap[57] |= bit_on;

	led_frame_bitmap[0] &=bit_off;
	led_frame_bitmap[8] &=bit_off;
	led_frame_bitmap[16] &=bit_off;
	led_frame_bitmap[24] &=bit_off;
	led_frame_bitmap[32] &=bit_off;
	led_frame_bitmap[40] &=bit_off;
	led_frame_bitmap[48] &=bit_off;
	led_frame_bitmap[56] &=bit_off;

}

//scroll a verticle plane 1 pixel forwards, new back columb is blank
void led_plane_x_forward(unsigned char x)
{
	unsigned char bit_on;
	unsigned char bit_off;
	
	bit_on = 0x80>>x;
	bit_off = ~bit_on;

	//shift back 1

	led_frame_bitmap[0] &=bit_off;
	led_frame_bitmap[8] &=bit_off;
	led_frame_bitmap[16] &=bit_off;
	led_frame_bitmap[24] &=bit_off;
	led_frame_bitmap[32] &=bit_off;
	led_frame_bitmap[40] &=bit_off;
	led_frame_bitmap[48] &=bit_off;
	led_frame_bitmap[56] &=bit_off;

	if(led_frame_bitmap[1] & bit_on)
		led_frame_bitmap[0] |= bit_on;
	if(led_frame_bitmap[9] & bit_on)
		led_frame_bitmap[8] |= bit_on;
	if(led_frame_bitmap[17] & bit_on)
		led_frame_bitmap[16] |= bit_on;
	if(led_frame_bitmap[25] & bit_on)
		led_frame_bitmap[24] |= bit_on;
	if(led_frame_bitmap[33] & bit_on)
		led_frame_bitmap[32] |= bit_on;
	if(led_frame_bitmap[41] & bit_on)
		led_frame_bitmap[40] |= bit_on;
	if(led_frame_bitmap[49] & bit_on)
		led_frame_bitmap[48] |= bit_on;
	if(led_frame_bitmap[57] & bit_on)
		led_frame_bitmap[56] |= bit_on;


	led_frame_bitmap[1] &=bit_off;
	led_frame_bitmap[9] &=bit_off;
	led_frame_bitmap[17] &=bit_off;
	led_frame_bitmap[25] &=bit_off;
	led_frame_bitmap[33] &=bit_off;
	led_frame_bitmap[41] &=bit_off;
	led_frame_bitmap[49] &=bit_off;
	led_frame_bitmap[57] &=bit_off;

	if(led_frame_bitmap[2] & bit_on)
		led_frame_bitmap[1] |= bit_on;
	if(led_frame_bitmap[10] & bit_on)
		led_frame_bitmap[9] |= bit_on;
	if(led_frame_bitmap[18] & bit_on)
		led_frame_bitmap[17] |= bit_on;
	if(led_frame_bitmap[26] & bit_on)
		led_frame_bitmap[25] |= bit_on;
	if(led_frame_bitmap[34] & bit_on)
		led_frame_bitmap[33] |= bit_on;
	if(led_frame_bitmap[42] & bit_on)
		led_frame_bitmap[41] |= bit_on;
	if(led_frame_bitmap[50] & bit_on)
		led_frame_bitmap[49] |= bit_on;
	if(led_frame_bitmap[58] & bit_on)
		led_frame_bitmap[57] |= bit_on;

	led_frame_bitmap[2] &=bit_off;
	led_frame_bitmap[10] &=bit_off;
	led_frame_bitmap[18] &=bit_off;
	led_frame_bitmap[26] &=bit_off;
	led_frame_bitmap[34] &=bit_off;
	led_frame_bitmap[42] &=bit_off;
	led_frame_bitmap[50] &=bit_off;
	led_frame_bitmap[58] &=bit_off;

	if(led_frame_bitmap[3] & bit_on)
		led_frame_bitmap[2] |= bit_on;
	if(led_frame_bitmap[11] & bit_on)
		led_frame_bitmap[10] |= bit_on;
	if(led_frame_bitmap[19] & bit_on)
		led_frame_bitmap[18] |= bit_on;
	if(led_frame_bitmap[27] & bit_on)
		led_frame_bitmap[26] |= bit_on;
	if(led_frame_bitmap[35] & bit_on)
		led_frame_bitmap[34] |= bit_on;
	if(led_frame_bitmap[43] & bit_on)
		led_frame_bitmap[42] |= bit_on;
	if(led_frame_bitmap[51] & bit_on)
		led_frame_bitmap[50] |= bit_on;
	if(led_frame_bitmap[59] & bit_on)
		led_frame_bitmap[58] |= bit_on;

	led_frame_bitmap[3] &=bit_off;
	led_frame_bitmap[11] &=bit_off;
	led_frame_bitmap[19] &=bit_off;
	led_frame_bitmap[27] &=bit_off;
	led_frame_bitmap[35] &=bit_off;
	led_frame_bitmap[43] &=bit_off;
	led_frame_bitmap[51] &=bit_off;
	led_frame_bitmap[59] &=bit_off;

	if(led_frame_bitmap[4] & bit_on)
		led_frame_bitmap[3] |= bit_on;
	if(led_frame_bitmap[12] & bit_on)
		led_frame_bitmap[11] |= bit_on;
	if(led_frame_bitmap[20] & bit_on)
		led_frame_bitmap[19] |= bit_on;
	if(led_frame_bitmap[28] & bit_on)
		led_frame_bitmap[27] |= bit_on;
	if(led_frame_bitmap[36] & bit_on)
		led_frame_bitmap[35] |= bit_on;
	if(led_frame_bitmap[44] & bit_on)
		led_frame_bitmap[43] |= bit_on;
	if(led_frame_bitmap[52] & bit_on)
		led_frame_bitmap[51] |= bit_on;
	if(led_frame_bitmap[60] & bit_on)
		led_frame_bitmap[59] |= bit_on;

	led_frame_bitmap[4] &=bit_off;
	led_frame_bitmap[12] &=bit_off;
	led_frame_bitmap[20] &=bit_off;
	led_frame_bitmap[28] &=bit_off;
	led_frame_bitmap[36] &=bit_off;
	led_frame_bitmap[44] &=bit_off;
	led_frame_bitmap[52] &=bit_off;
	led_frame_bitmap[60] &=bit_off;

	if(led_frame_bitmap[5] & bit_on)
		led_frame_bitmap[4] |= bit_on;
	if(led_frame_bitmap[13] & bit_on)
		led_frame_bitmap[12] |= bit_on;
	if(led_frame_bitmap[21] & bit_on)
		led_frame_bitmap[20] |= bit_on;
	if(led_frame_bitmap[29] & bit_on)
		led_frame_bitmap[28] |= bit_on;
	if(led_frame_bitmap[37] & bit_on)
		led_frame_bitmap[36] |= bit_on;
	if(led_frame_bitmap[45] & bit_on)
		led_frame_bitmap[44] |= bit_on;
	if(led_frame_bitmap[53] & bit_on)
		led_frame_bitmap[52] |= bit_on;
	if(led_frame_bitmap[61] & bit_on)
		led_frame_bitmap[60] |= bit_on;

	led_frame_bitmap[5] &=bit_off;
	led_frame_bitmap[13] &=bit_off;
	led_frame_bitmap[21] &=bit_off;
	led_frame_bitmap[29] &=bit_off;
	led_frame_bitmap[37] &=bit_off;
	led_frame_bitmap[45] &=bit_off;
	led_frame_bitmap[53] &=bit_off;
	led_frame_bitmap[61] &=bit_off;

	if(led_frame_bitmap[6] & bit_on)
		led_frame_bitmap[5] |= bit_on;
	if(led_frame_bitmap[14] & bit_on)
		led_frame_bitmap[13] |= bit_on;
	if(led_frame_bitmap[22] & bit_on)
		led_frame_bitmap[21] |= bit_on;
	if(led_frame_bitmap[30] & bit_on)
		led_frame_bitmap[29] |= bit_on;
	if(led_frame_bitmap[38] & bit_on)
		led_frame_bitmap[37] |= bit_on;
	if(led_frame_bitmap[46] & bit_on)
		led_frame_bitmap[45] |= bit_on;
	if(led_frame_bitmap[54] & bit_on)
		led_frame_bitmap[53] |= bit_on;
	if(led_frame_bitmap[62] & bit_on)
		led_frame_bitmap[61] |= bit_on;

	led_frame_bitmap[6] &=bit_off;
	led_frame_bitmap[14] &=bit_off;
	led_frame_bitmap[22] &=bit_off;
	led_frame_bitmap[30] &=bit_off;
	led_frame_bitmap[38] &=bit_off;
	led_frame_bitmap[46] &=bit_off;
	led_frame_bitmap[54] &=bit_off;
	led_frame_bitmap[62] &=bit_off;

	if(led_frame_bitmap[7] & bit_on)
		led_frame_bitmap[6] |= bit_on;
	if(led_frame_bitmap[15] & bit_on)
		led_frame_bitmap[14] |= bit_on;
	if(led_frame_bitmap[23] & bit_on)
		led_frame_bitmap[22] |= bit_on;
	if(led_frame_bitmap[31] & bit_on)
		led_frame_bitmap[30] |= bit_on;
	if(led_frame_bitmap[39] & bit_on)
		led_frame_bitmap[38] |= bit_on;
	if(led_frame_bitmap[47] & bit_on)
		led_frame_bitmap[46] |= bit_on;
	if(led_frame_bitmap[55] & bit_on)
		led_frame_bitmap[54] |= bit_on;
	if(led_frame_bitmap[63] & bit_on)
		led_frame_bitmap[62] |= bit_on;

	led_frame_bitmap[7] &=bit_off;
	led_frame_bitmap[15] &=bit_off;
	led_frame_bitmap[23] &=bit_off;
	led_frame_bitmap[31] &=bit_off;
	led_frame_bitmap[39] &=bit_off;
	led_frame_bitmap[47] &=bit_off;
	led_frame_bitmap[55] &=bit_off;
	led_frame_bitmap[63] &=bit_off;

}

//scroll a verticle plane 1 pixel up, new bottom row is blank
void led_plane_x_up(unsigned char x)
{
	unsigned char bit_off, bit_on;
	
	bit_on=0x80>>x;
	bit_off=~bit_on;

	#define T 0
	#define S 8
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S
	
	#define T 8
	#define S 16
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 16
	#define S 24
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 24
	#define S 32
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 32
	#define S 40
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 40
	#define S 48
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 48
	#define S 56
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 56
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	#undef T
}

//scroll a verticle plane 1 pixel down, new top row is blank
void led_plane_x_down(unsigned char x)
{
	unsigned char bit_off, bit_on;
	
	bit_on=0x80>>x;
	bit_off=~bit_on;

	#define T 56
	#define S 48
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S
	
	#define T 48
	#define S 40
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 40
	#define S 32
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 32
	#define S 24
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 24
	#define S 16
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 16
	#define S 8
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 8
	#define S 0
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	if(led_frame_bitmap[0+S] & bit_on)
		led_frame_bitmap[0+T] |= bit_on;
	if(led_frame_bitmap[1+S] & bit_on)
		led_frame_bitmap[1+T] |= bit_on;
	if(led_frame_bitmap[2+S] & bit_on)
		led_frame_bitmap[2+T] |= bit_on;
	if(led_frame_bitmap[3+S] & bit_on)
		led_frame_bitmap[3+T] |= bit_on;
	if(led_frame_bitmap[4+S] & bit_on)
		led_frame_bitmap[4+T] |= bit_on;
	if(led_frame_bitmap[5+S] & bit_on)
		led_frame_bitmap[5+T] |= bit_on;
	if(led_frame_bitmap[6+S] & bit_on)
		led_frame_bitmap[6+T] |= bit_on;
	if(led_frame_bitmap[7+S] & bit_on)
		led_frame_bitmap[7+T] |= bit_on;
	#undef T
	#undef S

	#define T 0
	led_frame_bitmap[0+T] &=bit_off;
	led_frame_bitmap[1+T] &=bit_off;
	led_frame_bitmap[2+T] &=bit_off;
	led_frame_bitmap[3+T] &=bit_off;
	led_frame_bitmap[4+T] &=bit_off;
	led_frame_bitmap[5+T] &=bit_off;
	led_frame_bitmap[6+T] &=bit_off;
	led_frame_bitmap[7+T] &=bit_off;
	#undef T

}

//scroll a verticle plane to the left, new columb at the right is blank
void led_plane_z_left(unsigned char plane)
{
	led_frame_bitmap[plane]<<=1;
	plane+=8;
	led_frame_bitmap[plane]<<=1;
	plane+=8;
	led_frame_bitmap[plane]<<=1;
	plane+=8;
	led_frame_bitmap[plane]<<=1;
	plane+=8;
	led_frame_bitmap[plane]<<=1;
	plane+=8;
	led_frame_bitmap[plane]<<=1;
	plane+=8;
	led_frame_bitmap[plane]<<=1;
	plane+=8;
	led_frame_bitmap[plane]<<=1;
}

//scroll a verticle plane to the right, new columb at the left is blank
void led_plane_z_right(unsigned char plane)
{
	led_frame_bitmap[plane]>>=1;
	plane+=8;
	led_frame_bitmap[plane]>>=1;
	plane+=8;
	led_frame_bitmap[plane]>>=1;
	plane+=8;
	led_frame_bitmap[plane]>>=1;
	plane+=8;
	led_frame_bitmap[plane]>>=1;
	plane+=8;
	led_frame_bitmap[plane]>>=1;
	plane+=8;
	led_frame_bitmap[plane]>>=1;
	plane+=8;
	led_frame_bitmap[plane]>>=1;
}

void led_perimeter_left(void)
{
	unsigned char tempcol1[8];
	unsigned char tempcol2[8];

	memset(tempcol1, 0, 8);
	memset(tempcol2, 0, 8);

	//save back right columb before rotate (this will be restored to 7,Y,6)
	if(led_frame_bitmap[7] & 1)
		tempcol1[0]=1;
	if(led_frame_bitmap[15] & 1)
		tempcol1[1]=1;
	if(led_frame_bitmap[23] & 1)
		tempcol1[2]=1;
	if(led_frame_bitmap[31] & 1)
		tempcol1[3]=1;
	if(led_frame_bitmap[39] & 1)
		tempcol1[4]=1;
	if(led_frame_bitmap[47] & 1)
		tempcol1[5]=1;
	if(led_frame_bitmap[55] & 1)
		tempcol1[6]=1;
	if(led_frame_bitmap[63] & 1)
		tempcol1[7]=1;

	led_plane_z_right(7);	// back face right (destroys data in back right columb)
	led_plane_x_back(0);		// left face back
	led_plane_z_left(0);		// front face left		

	//save back right columb again, as right face forward will erase it
	if(led_frame_bitmap[7] & 1)
		tempcol2[0]=1;
	if(led_frame_bitmap[15] & 1)
		tempcol2[1]=1;
	if(led_frame_bitmap[23] & 1)
		tempcol2[2]=1;
	if(led_frame_bitmap[31] & 1)
		tempcol2[3]=1;
	if(led_frame_bitmap[39] & 1)
		tempcol2[4]=1;
	if(led_frame_bitmap[47] & 1)
		tempcol2[5]=1;
	if(led_frame_bitmap[55] & 1)
		tempcol2[6]=1;
	if(led_frame_bitmap[63] & 1)
		tempcol2[7]=1;

	led_plane_x_forward(7);	// right face forward

	//restore correct back right columb 
	if(tempcol2[0])
		led_frame_bitmap[7] |=0x01;
	if(tempcol2[1])
		led_frame_bitmap[15] |=0x01;
	if(tempcol2[2])
		led_frame_bitmap[23] |=0x01;
	if(tempcol2[3])
		led_frame_bitmap[31] |=0x01;
	if(tempcol2[4])
		led_frame_bitmap[39] |=0x01;
	if(tempcol2[5])
		led_frame_bitmap[47] |=0x01;
	if(tempcol2[6])
		led_frame_bitmap[55] |=0x01;
	if(tempcol2[7])
		led_frame_bitmap[63] |=0x01;

	//erase 7,Y,6
	led_frame_bitmap[6] &=0xFE;
	led_frame_bitmap[14] &=0xFE;
	led_frame_bitmap[22] &=0xFE;
	led_frame_bitmap[30] &=0xFE;
	led_frame_bitmap[38] &=0xFE;
	led_frame_bitmap[46] &=0xFE;
	led_frame_bitmap[54] &=0xFE;
	led_frame_bitmap[62] &=0xFE;

	//restore pre-rotated back right columb to 7,Y,6
	if(tempcol1[0])
		led_frame_bitmap[6] |=0x01;
	if(tempcol1[1])
		led_frame_bitmap[14] |=0x01;
	if(tempcol1[2])
		led_frame_bitmap[22] |=0x01;
	if(tempcol1[3])
		led_frame_bitmap[30] |=0x01;
	if(tempcol1[4])
		led_frame_bitmap[38] |=0x01;
	if(tempcol1[5])
		led_frame_bitmap[46] |=0x01;
	if(tempcol1[6])
		led_frame_bitmap[54] |=0x01;
	if(tempcol1[7])
		led_frame_bitmap[62] |=0x01;

}

void led_perimeter_right(void)
{
	unsigned char tempcol1[8];
	unsigned char tempcol2[8];

	memset(tempcol1, 0, 8);
	memset(tempcol2, 0, 8);

	//save back left columb before rotate (this will be restored to 0,Y,6)
	if(led_frame_bitmap[7] & 0x80)
		tempcol1[0]=1;
	if(led_frame_bitmap[15] & 0x80)
		tempcol1[1]=1;
	if(led_frame_bitmap[23] & 0x80)
		tempcol1[2]=1;
	if(led_frame_bitmap[31] & 0x80)
		tempcol1[3]=1;
	if(led_frame_bitmap[39] & 0x80)
		tempcol1[4]=1;
	if(led_frame_bitmap[47] & 0x80)
		tempcol1[5]=1;
	if(led_frame_bitmap[55] & 0x80)
		tempcol1[6]=1;
	if(led_frame_bitmap[63] & 0x80)
		tempcol1[7]=1;

	led_plane_z_left(7);		// back face left (destroys data in back left columb)
	led_plane_x_back(7);		// right face back
	led_plane_z_right(0);	// front face right

	//save back left columb again, as left face forward will erase it
	if(led_frame_bitmap[7] & 0x80)
		tempcol2[0]=1;
	if(led_frame_bitmap[15] & 0x80)
		tempcol2[1]=1;
	if(led_frame_bitmap[23] & 0x80)
		tempcol2[2]=1;
	if(led_frame_bitmap[31] & 0x80)
		tempcol2[3]=1;
	if(led_frame_bitmap[39] & 0x80)
		tempcol2[4]=1;
	if(led_frame_bitmap[47] & 0x80)
		tempcol2[5]=1;
	if(led_frame_bitmap[55] & 0x80)
		tempcol2[6]=1;
	if(led_frame_bitmap[63] & 0x80)
		tempcol2[7]=1;

	led_plane_x_forward(0);	// left face forward

	//restore correct back left columb 
	if(tempcol2[0])
		led_frame_bitmap[7] |=0x80;
	if(tempcol2[1])
		led_frame_bitmap[15] |=0x80;
	if(tempcol2[2])
		led_frame_bitmap[23] |=0x80;
	if(tempcol2[3])
		led_frame_bitmap[31] |=0x80;
	if(tempcol2[4])
		led_frame_bitmap[39] |=0x80;
	if(tempcol2[5])
		led_frame_bitmap[47] |=0x80;
	if(tempcol2[6])
		led_frame_bitmap[55] |=0x80;
	if(tempcol2[7])
		led_frame_bitmap[63] |=0x80;

	//erase 0,Y,6
	led_frame_bitmap[6] &=0x7F;
	led_frame_bitmap[14] &=0x7F;
	led_frame_bitmap[22] &=0x7F;
	led_frame_bitmap[30] &=0x7F;
	led_frame_bitmap[38] &=0x7F;
	led_frame_bitmap[46] &=0x7F;
	led_frame_bitmap[54] &=0x7F;
	led_frame_bitmap[62] &=0x7F;

	//restore pre-rotated back right columb to 0,Y,6
	if(tempcol1[0])
		led_frame_bitmap[6] |=0x80;
	if(tempcol1[1])
		led_frame_bitmap[14] |=0x80;
	if(tempcol1[2])
		led_frame_bitmap[22] |=0x80;
	if(tempcol1[3])
		led_frame_bitmap[30] |=0x80;
	if(tempcol1[4])
		led_frame_bitmap[38] |=0x80;
	if(tempcol1[5])
		led_frame_bitmap[46] |=0x80;
	if(tempcol1[6])
		led_frame_bitmap[54] |=0x80;
	if(tempcol1[7])
		led_frame_bitmap[62] |=0x80;

}

void led_perimeter_up(void)
{
	unsigned char temprow1;
	unsigned char temprow2;

	//save back top row before rotate (1)
	//top face back
	//front face up
	//botom face forwards
	//save back top row again (2)
	//back face down
	//restore back top row (2)
	//restore (1) to X,1,7
	

	//save back top row before rotate (1)
	temprow1 = led_frame_bitmap[7];
	
	//top face back
	led_plane_y_back(0);
	
	//front face up
	led_plane_z_up(0);
	
	//botom face forwards
	led_plane_y_forward(7);
	
	//save back top row again (2)
	temprow2 = led_frame_bitmap[7];
	
	//back face down
	led_plane_z_down(7);

	//restore back top row (2)
	led_frame_bitmap[7] = temprow2;
	
	//restore (1) to X,1,7
	led_frame_bitmap[15] = temprow1;

}

void led_perimeter_down(void)
{
	unsigned char temprow1;
	unsigned char temprow2;

	//save back bottom row before rotate (1)
	//bottom face back
	//front face down
	//top face forwards
	//save back bottom row again (2)
	//back face up
	//restore back bottom row (2)
	//restore (1) to X,6,7

	//save back bottom row before rotate (1)
	temprow1 = led_frame_bitmap[63];
	
	//bottom face back
	led_plane_y_back(7);
	
	//front face down
	led_plane_z_down(0);

	//top face forwards
	led_plane_y_forward(0);

	//save back bottom row again (2)
	temprow2 = led_frame_bitmap[63];
	
	//back face up
	led_plane_z_up(7);
	
	//restore back bottom row (2)
	led_frame_bitmap[63] = temprow2;
	
	//restore (1) to X,6,7
	led_frame_bitmap[55] = temprow1;

}


//rotate perimiter clockwise (top right)
void led_perimeter_clockwise(void)
{

	unsigned char temprow1[8];
	unsigned char temprow2[8];

	memset(temprow1, 0, 8);
	memset(temprow2, 0, 8);

	//save top right row (1)
	//scroll top right
	//scroll left up
	//scroll bottom left
	//save top right row (2)
	//scroll right down
	//restore top right row(2)
	//restore (1) to 7,1,Z

	//save top right row (1)
	if(led_frame_bitmap[0] & 1)
		temprow1[0]=1;
	if(led_frame_bitmap[1] & 1)
		temprow1[1]=1;
	if(led_frame_bitmap[2] & 1)
		temprow1[2]=1;
	if(led_frame_bitmap[3] & 1)
		temprow1[3]=1;
	if(led_frame_bitmap[4] & 1)
		temprow1[4]=1;
	if(led_frame_bitmap[5] & 1)
		temprow1[5]=1;
	if(led_frame_bitmap[6] & 1)
		temprow1[6]=1;
	if(led_frame_bitmap[7] & 1)
		temprow1[7]=1;

	//scroll top right
	led_plane_y_right(0);
	//scroll left up
	led_plane_x_up(0);		
	//scroll bottom left
	led_plane_y_left(7);

	//save top right row (2)
	if(led_frame_bitmap[0] & 1)
		temprow2[0]=1;
	if(led_frame_bitmap[1] & 1)
		temprow2[1]=1;
	if(led_frame_bitmap[2] & 1)
		temprow2[2]=1;
	if(led_frame_bitmap[3] & 1)
		temprow2[3]=1;
	if(led_frame_bitmap[4] & 1)
		temprow2[4]=1;
	if(led_frame_bitmap[5] & 1)
		temprow2[5]=1;
	if(led_frame_bitmap[6] & 1)
		temprow2[6]=1;
	if(led_frame_bitmap[7] & 1)
		temprow2[7]=1;

	//scroll right down
	led_plane_x_down(7);

	//restore correct top right row (2)
	if(temprow2[0])
		led_frame_bitmap[0] |=0x01;
	if(temprow2[1])
		led_frame_bitmap[1] |=0x01;
	if(temprow2[2])
		led_frame_bitmap[2] |=0x01;
	if(temprow2[3])
		led_frame_bitmap[3] |=0x01;
	if(temprow2[4])
		led_frame_bitmap[4] |=0x01;
	if(temprow2[5])
		led_frame_bitmap[5] |=0x01;
	if(temprow2[6])
		led_frame_bitmap[6] |=0x01;
	if(temprow2[7])
		led_frame_bitmap[7] |=0x01;

	//restore (1) to 7,1,Z
	led_frame_bitmap[8] &=0xFE;
	led_frame_bitmap[9] &=0xFE;
	led_frame_bitmap[10] &=0xFE;
	led_frame_bitmap[11] &=0xFE;
	led_frame_bitmap[12] &=0xFE;
	led_frame_bitmap[13] &=0xFE;
	led_frame_bitmap[14] &=0xFE;
	led_frame_bitmap[15] &=0xFE;
	if(temprow1[0])
		led_frame_bitmap[8] |=0x01;
	if(temprow1[1])
		led_frame_bitmap[9] |=0x01;
	if(temprow1[2])
		led_frame_bitmap[10] |=0x01;
	if(temprow1[3])
		led_frame_bitmap[11] |=0x01;
	if(temprow1[4])
		led_frame_bitmap[12] |=0x01;
	if(temprow1[5])
		led_frame_bitmap[13] |=0x01;
	if(temprow1[6])
		led_frame_bitmap[14] |=0x01;
	if(temprow1[7])
		led_frame_bitmap[15] |=0x01;

}

//rotate perimiter clockwise (top left)
void led_perimeter_anticlockwise(void)
{
	unsigned char temprow1[8];
	unsigned char temprow2[8];

	memset(temprow1, 0, 8);
	memset(temprow2, 0, 8);

	//save top left row (1)
	if(led_frame_bitmap[0] & 0x80)
		temprow1[0]=1;
	if(led_frame_bitmap[1] & 0x80)
		temprow1[1]=1;
	if(led_frame_bitmap[2] & 0x80)
		temprow1[2]=1;
	if(led_frame_bitmap[3] & 0x80)
		temprow1[3]=1;
	if(led_frame_bitmap[4] & 0x80)
		temprow1[4]=1;
	if(led_frame_bitmap[5] & 0x80)
		temprow1[5]=1;
	if(led_frame_bitmap[6] & 0x80)
		temprow1[6]=1;
	if(led_frame_bitmap[7] & 0x80)
		temprow1[7]=1;

	//scroll top left
	led_plane_y_left(0);
	//scroll right up
	led_plane_x_up(7);
	//scroll bottom right
	led_plane_y_right(7);

	//save top left row (2)
	if(led_frame_bitmap[0] & 0x80)
		temprow2[0]=1;
	if(led_frame_bitmap[1] & 0x80)
		temprow2[1]=1;
	if(led_frame_bitmap[2] & 0x80)
		temprow2[2]=1;
	if(led_frame_bitmap[3] & 0x80)
		temprow2[3]=1;
	if(led_frame_bitmap[4] & 0x80)
		temprow2[4]=1;
	if(led_frame_bitmap[5] & 0x80)
		temprow2[5]=1;
	if(led_frame_bitmap[6] & 0x80)
		temprow2[6]=1;
	if(led_frame_bitmap[7] & 0x80)
		temprow2[7]=1;

	//scroll left down
	led_plane_x_down(0);

	//restore correct top left row (2)
	if(temprow2[0])
		led_frame_bitmap[0] |=0x80;
	if(temprow2[1])
		led_frame_bitmap[1] |=0x80;
	if(temprow2[2])
		led_frame_bitmap[2] |=0x80;
	if(temprow2[3])
		led_frame_bitmap[3] |=0x80;
	if(temprow2[4])
		led_frame_bitmap[4] |=0x80;
	if(temprow2[5])
		led_frame_bitmap[5] |=0x80;
	if(temprow2[6])
		led_frame_bitmap[6] |=0x80;
	if(temprow2[7])
		led_frame_bitmap[7] |=0x80;

	//restore (1) to 7,1,Z
	led_frame_bitmap[8] &=0x7F;
	led_frame_bitmap[9] &=0x7F;
	led_frame_bitmap[10] &=0x7F;
	led_frame_bitmap[11] &=0x7F;
	led_frame_bitmap[12] &=0x7F;
	led_frame_bitmap[13] &=0x7F;
	led_frame_bitmap[14] &=0x7F;
	led_frame_bitmap[15] &=0x7F;
	if(temprow1[0])
		led_frame_bitmap[8] |=0x80;
	if(temprow1[1])
		led_frame_bitmap[9] |=0x80;
	if(temprow1[2])
		led_frame_bitmap[10] |=0x80;
	if(temprow1[3])
		led_frame_bitmap[11] |=0x80;
	if(temprow1[4])
		led_frame_bitmap[12] |=0x80;
	if(temprow1[5])
		led_frame_bitmap[13] |=0x80;
	if(temprow1[6])
		led_frame_bitmap[14] |=0x80;
	if(temprow1[7])
		led_frame_bitmap[15] |=0x80;

}	

//scroll entire frame down 1 pixel
void led_frame_down(void)
{
	memmove(&led_frame_bitmap[8], &led_frame_bitmap[0], 56);
	memset(&led_frame_bitmap[0], 0, 8);
}

//scroll entire frame up 1 pixel
void led_frame_up(void)
{
	memmove(&led_frame_bitmap[0], &led_frame_bitmap[8], 56);
	memset(&led_frame_bitmap[56], 0, 8);
}

//scroll entire frame left 1 pixel
void led_frame_left(void)
{
	led_frame_bitmap[0]<<=1;
	led_frame_bitmap[1]<<=1;
	led_frame_bitmap[2]<<=1;
	led_frame_bitmap[3]<<=1;
	led_frame_bitmap[4]<<=1;
	led_frame_bitmap[5]<<=1;
	led_frame_bitmap[6]<<=1;
	led_frame_bitmap[7]<<=1;
	led_frame_bitmap[8]<<=1;
	led_frame_bitmap[9]<<=1;
	led_frame_bitmap[10]<<=1;
	led_frame_bitmap[11]<<=1;
	led_frame_bitmap[12]<<=1;
	led_frame_bitmap[13]<<=1;
	led_frame_bitmap[14]<<=1;
	led_frame_bitmap[15]<<=1;
	led_frame_bitmap[16]<<=1;
	led_frame_bitmap[17]<<=1;
	led_frame_bitmap[18]<<=1;
	led_frame_bitmap[19]<<=1;
	led_frame_bitmap[20]<<=1;
	led_frame_bitmap[21]<<=1;
	led_frame_bitmap[22]<<=1;
	led_frame_bitmap[23]<<=1;
	led_frame_bitmap[24]<<=1;
	led_frame_bitmap[25]<<=1;
	led_frame_bitmap[26]<<=1;
	led_frame_bitmap[27]<<=1;
	led_frame_bitmap[28]<<=1;
	led_frame_bitmap[29]<<=1;
	led_frame_bitmap[30]<<=1;
	led_frame_bitmap[31]<<=1;
	led_frame_bitmap[32]<<=1;
	led_frame_bitmap[33]<<=1;
	led_frame_bitmap[34]<<=1;
	led_frame_bitmap[35]<<=1;
	led_frame_bitmap[36]<<=1;
	led_frame_bitmap[37]<<=1;
	led_frame_bitmap[38]<<=1;
	led_frame_bitmap[39]<<=1;
	led_frame_bitmap[40]<<=1;
	led_frame_bitmap[41]<<=1;
	led_frame_bitmap[42]<<=1;
	led_frame_bitmap[43]<<=1;
	led_frame_bitmap[44]<<=1;
	led_frame_bitmap[45]<<=1;
	led_frame_bitmap[46]<<=1;
	led_frame_bitmap[47]<<=1;
	led_frame_bitmap[48]<<=1;
	led_frame_bitmap[49]<<=1;
	led_frame_bitmap[50]<<=1;
	led_frame_bitmap[51]<<=1;
	led_frame_bitmap[52]<<=1;
	led_frame_bitmap[53]<<=1;
	led_frame_bitmap[54]<<=1;
	led_frame_bitmap[55]<<=1;
	led_frame_bitmap[56]<<=1;
	led_frame_bitmap[57]<<=1;
	led_frame_bitmap[58]<<=1;
	led_frame_bitmap[59]<<=1;
	led_frame_bitmap[60]<<=1;
	led_frame_bitmap[61]<<=1;
	led_frame_bitmap[62]<<=1;
	led_frame_bitmap[63]<<=1;

}

//scroll entire frame right 1 pixel
void led_frame_right(void)
{
	led_frame_bitmap[0]>>=1;
	led_frame_bitmap[1]>>=1;
	led_frame_bitmap[2]>>=1;
	led_frame_bitmap[3]>>=1;
	led_frame_bitmap[4]>>=1;
	led_frame_bitmap[5]>>=1;
	led_frame_bitmap[6]>>=1;
	led_frame_bitmap[7]>>=1;
	led_frame_bitmap[8]>>=1;
	led_frame_bitmap[9]>>=1;
	led_frame_bitmap[10]>>=1;
	led_frame_bitmap[11]>>=1;
	led_frame_bitmap[12]>>=1;
	led_frame_bitmap[13]>>=1;
	led_frame_bitmap[14]>>=1;
	led_frame_bitmap[15]>>=1;
	led_frame_bitmap[16]>>=1;
	led_frame_bitmap[17]>>=1;
	led_frame_bitmap[18]>>=1;
	led_frame_bitmap[19]>>=1;
	led_frame_bitmap[20]>>=1;
	led_frame_bitmap[21]>>=1;
	led_frame_bitmap[22]>>=1;
	led_frame_bitmap[23]>>=1;
	led_frame_bitmap[24]>>=1;
	led_frame_bitmap[25]>>=1;
	led_frame_bitmap[26]>>=1;
	led_frame_bitmap[27]>>=1;
	led_frame_bitmap[28]>>=1;
	led_frame_bitmap[29]>>=1;
	led_frame_bitmap[30]>>=1;
	led_frame_bitmap[31]>>=1;
	led_frame_bitmap[32]>>=1;
	led_frame_bitmap[33]>>=1;
	led_frame_bitmap[34]>>=1;
	led_frame_bitmap[35]>>=1;
	led_frame_bitmap[36]>>=1;
	led_frame_bitmap[37]>>=1;
	led_frame_bitmap[38]>>=1;
	led_frame_bitmap[39]>>=1;
	led_frame_bitmap[40]>>=1;
	led_frame_bitmap[41]>>=1;
	led_frame_bitmap[42]>>=1;
	led_frame_bitmap[43]>>=1;
	led_frame_bitmap[44]>>=1;
	led_frame_bitmap[45]>>=1;
	led_frame_bitmap[46]>>=1;
	led_frame_bitmap[47]>>=1;
	led_frame_bitmap[48]>>=1;
	led_frame_bitmap[49]>>=1;
	led_frame_bitmap[50]>>=1;
	led_frame_bitmap[51]>>=1;
	led_frame_bitmap[52]>>=1;
	led_frame_bitmap[53]>>=1;
	led_frame_bitmap[54]>>=1;
	led_frame_bitmap[55]>>=1;
	led_frame_bitmap[56]>>=1;
	led_frame_bitmap[57]>>=1;
	led_frame_bitmap[58]>>=1;
	led_frame_bitmap[59]>>=1;
	led_frame_bitmap[60]>>=1;
	led_frame_bitmap[61]>>=1;
	led_frame_bitmap[62]>>=1;
	led_frame_bitmap[63]>>=1;

}

//scroll entire frame forward 1 pixel
void led_frame_forward(void)
{
	memmove(&led_frame_bitmap[0], &led_frame_bitmap[1], 63);
	led_frame_bitmap[7]=0;
	led_frame_bitmap[15]=0;
	led_frame_bitmap[23]=0;
	led_frame_bitmap[31]=0;
	led_frame_bitmap[39]=0;
	led_frame_bitmap[47]=0;
	led_frame_bitmap[55]=0;
	led_frame_bitmap[63]=0;
}

//scroll entire frame back 1 pixel
void led_frame_back(void)
{
	memmove(&led_frame_bitmap[1], &led_frame_bitmap[0], 63);
	led_frame_bitmap[0]=0;
	led_frame_bitmap[8]=0;
	led_frame_bitmap[16]=0;
	led_frame_bitmap[24]=0;
	led_frame_bitmap[32]=0;
	led_frame_bitmap[40]=0;
	led_frame_bitmap[48]=0;
	led_frame_bitmap[56]=0;
}

//********************************************************************************************************
// Private functions
//********************************************************************************************************

ISR(TIMER1_COMPA_vect)
{
	unsigned char* output_ptr;
	//OCR1A isr occurs 1/2 way through displaying plane  (top)

	//if displaying last plane
	if(plane_current==7)
	{
		//copy new frame to output buffer
		memcpy(output_bitmap, led_frame_bitmap, 64);
		memcpy(output_plane_period, plane_period, 16);
		OCR1A = frame_time;
		plane_current=0;
		frame_sync=TRUE;
	}
	else
		plane_current++;

	if(flip)
	{
		output_ptr = &output_bitmap[7+(plane_current<<3)];
		
		//load data for new plane
		SPDR = *output_ptr--;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr--;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr--;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr--;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr--;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr--;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr--;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr;
		while(!(SPSR & _BV(SPIF)));
	}
	else
	{
		output_ptr = &output_bitmap[plane_current<<3];
		
		//load data for new plane
		SPDR = *output_ptr++;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr++;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr++;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr++;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr++;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr++;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr++;
		while(!(SPSR & _BV(SPIF)));
		SPDR = *output_ptr;
		while(!(SPSR & _BV(SPIF)));
	};

	//load next plane intensity
	OCR1B = output_plane_period[plane_current];

}

ISR(TIMER1_OVF_vect)
{
	//TOV1 isr occurs at END of plane N (bottom), start of plane N+1

	LED_LATCH_PORT |=_BV(LED_LATCH_BIT);

	if(flip)
		PLANES_PORT =~ (0x80>>plane_current);
	else
		PLANES_PORT =~ (1<<plane_current);
	
	LED_LATCH_PORT &=~_BV(LED_LATCH_BIT);
}
