#!/bin/bash

usage()
{
	echo "Usage: $0 <MCU-type> <clock-frequency>";
}

if [ ! "$#" == "2" ]; then
	usage;
	exit 1;
fi

sed "s/__CONFIGURE_CPU_TYPE__/$1/g" "src/Makefile.in" | sed "s/__CONFIGURE_CPU_FREQ__/$2/g" - >"src/Makefile";

echo "Makefile successfully created.";
echo "Type 'make' then 'make install' to build and install the library."
exit 0;

