
#define FOSC0						12000000 // 12MHz ext. xtal
#define OSC0_STARTUP				AVR32_PM_OSCCTRL0_STARTUP_2048_RCOSC

#define LED0_GPIO					AVR32_PIN_PA13

#define GPIO_JOYSTICK_PUSH    		AVR32_PIN_PA26
#define GPIO_JOYSTICK_LEFT    		AVR32_PIN_PA23
#define GPIO_JOYSTICK_RIGHT   		AVR32_PIN_PA12
#define GPIO_JOYSTICK_UP      		AVR32_PIN_PA11
#define GPIO_JOYSTICK_DOWN    		AVR32_PIN_PA24

// SD/MMC-settings.
#define SD_MMC_CARD_DETECT_PIN      AVR32_PIN_PA27
#define SD_MMC_SPI                  (&AVR32_SPI)
#define SD_MMC_SPI_NPCS             0
#define SD_MMC_SPI_SCK_PIN          AVR32_SPI_SCK_0_0_PIN
#define SD_MMC_SPI_SCK_FUNCTION     AVR32_SPI_SCK_0_0_FUNCTION
#define SD_MMC_SPI_MISO_PIN         AVR32_SPI_MISO_0_0_PIN
#define SD_MMC_SPI_MISO_FUNCTION    AVR32_SPI_MISO_0_0_FUNCTION
#define SD_MMC_SPI_MOSI_PIN         AVR32_SPI_MOSI_0_0_PIN
#define SD_MMC_SPI_MOSI_FUNCTION    AVR32_SPI_MOSI_0_0_FUNCTION
#define SD_MMC_SPI_NPCS_PIN         AVR32_SPI_NPCS_0_0_PIN
#define SD_MMC_SPI_NPCS_FUNCTION    AVR32_SPI_NPCS_0_0_FUNCTION
