//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Studio.rc
//
#define IDD_SPLASH                      101
#define IDD_ABOUT                       102
#define IDD_LICENSE                     103
#define IDD_SETTINGS                    104
#define IDD_SOURCEFILE                  105
#define IDD_FUNCTION                    106
#define IDD_VARIABLE                    107
#define IDD_ASMVARIABLE                 108
#define IDR_MAINFRAME                   129
#define IDI_PROJECT                     130
#define IDR_PROJECT                     131
#define IDR_SOURCE                      132
#define IDR_SFRS                        133
#define IDR_WATCH                       134
#define IDI_REGISTERS                   135
#define IDI_SRAM                        136
#define IDI_EEPROM                      137
#define IDI_STACK                       138
#define IDI_CHIP                        139
#define IDR_CHIP                        140
#define IDR_HELP                        141
#define IDB_TREE_FIRST                  200
#define IDB_TREE_PROJECT                200
#define IDB_TREE_FOLDER                 201
#define IDB_TREE_FOLDEROPEN             202
#define IDB_TREE_FUNCTIONS              203
#define IDB_TREE_FUNCTIONSOPEN          204
#define IDB_TREE_VARIABLES              205
#define IDB_TREE_VARIABLESOPEN          206
#define IDB_TREE_FILE                   207
#define IDB_TREE_FUNCTION               208
#define IDB_TREE_VARIABLE               209
#define IDB_TREE_WATCH                  210
#define IDB_TREE_LAST                   210
#define IDT_PROJECTBAR                  300
#define IDT_TARGETCONTROLBAR            301
#define IDB_CURSOR                      307
#define IDB_CURSORMASK                  308
#define IDB_SOFTBP                      309
#define IDB_SOFTBPMASK                  310
#define IDB_HARDBP                      311
#define IDB_HARDBPMASK                  313
#define IDB_PC                          314
#define IDB_COMMSCONNECTED              326
#define IDB_COM                         327
#define IDB_BAUD                        328
#define IDB_SPLASH                      333
#define IDA_ABOUT                       339
#define IDD_PROJECTWIZARD               344
#define IDD_PLUGINS                     346
#define IDD_COMMSTIMEOUT                347
#define IDC_ABOUTANIM                   1010
#define IDC_PROJECT_TREE                1020
#define IDC_SFRS_LIST                   1030
#define IDC_WATCH_LIST                  1040
#define IDC_SRAM_SCROLLER               1050
#define IDC_EEPROM_SCROLLER             1060
#define IDC_SOURCE_HSCROLLER            1070
#define IDC_SOURCE_VSCROLLER            1071
#define IDC_SOURCE_SIZEBOX              1072
#define IDC_STACK_SCROLLER              1080
#define IDC_LICENSE_ANIM                1100
#define IDC_LICENSE_MESSAGE             1101
#define IDC_LICENSE_PUBLICKEY           1102
#define IDC_LICENSE_IN                  1103
#define IDC_LICENSE_LICENSE             1104
#define IDC_LICENSE_FROMDISK            1105
#define IDC_LICENSE_CODE                1106
#define IDC_LICENSE_EMAIL               1107
#define IDC_LICENSE_CPUS                1108
#define IDC_LICENSE_CPUSALL             1109
#define IDC_LICENSE_IDES                1110
#define IDC_LICENSE_IDESALL             1111
#define IDC_LICENSE_BASIC               1112
#define IDC_LICENSE_BASICWANT           1113
#define IDC_LICENSE_PROF                1114
#define IDC_LICENSE_PROFWANT            1115
#define IDC_LICENSE_ENTWANT             1116
#define IDC_LICENSE_ENT                 1117
#define IDC_LICENSE_ICE                 1118
#define IDC_LICENSE_ICEWANT             1119
#define IDC_SETTINGS_TAB                1200
#define IDC_SETTINGS_COMMSFIRST         1201
#define IDC_SETTINGS_COMMSPORTSTATIC    1201
#define IDC_SETTINGS_COMMSPORT          1202
#define IDC_SETTINGS_COMMSBAUD          1203
#define IDC_SETTINGS_COMMSSTANDARDSTATIC 1204
#define IDC_SETTINGS_COMMSPORTGROUP     1205
#define IDC_SETTINGS_COMMSBAUDGROUP     1206
#define IDC_SETTINGS_COMMSCHECK         1207
#define IDC_SETTINGS_COMMSCUSTOM        1208
#define IDC_SETTINGS_COMMSLAST          1208
#define IDC_SETTINGS_CPUFIRST           1209
#define IDC_SETTINGS_CPUCPUGROUP        1209
#define IDC_SETTINGS_CPUCPU             1210
#define IDC_SETTINGS_CPUPACKAGEGROUP    1211
#define IDC_SETTINGS_CPUPACKAGE         1212
#define IDC_SETTINGS_CPULAST            1212
#define IDC_SETTINGS_SFRSFIRST          1213
#define IDC_SETTINGS_SFRSLIST           1213
#define IDC_SETTINGS_SFRSSELECT         1214
#define IDC_SETTINGS_SFRSCLEAR          1215
#define IDC_SETTINGS_SFRSFLAGS          1216
#define IDC_SETTINGS_SFRSLAST           1216
#define IDC_SETTINGS_MEMFIRST           1217
#define IDC_SETTINGS_EXTERNALMEM        1217
#define IDC_SETTINGS_EXMEMSTARTTEXT     1218
#define IDC_SETTINGS_EXMEMSTART         1219
#define IDC_SETTINGS_EXMEMSIZETEXT      1220
#define IDC_SETTINGS_EXMEMSIZE          1221
#define IDC_SETTINGS_MEMLAST            1221
#define IDC_SETTINGS_STACKFIRST         1222
#define IDC_SETTINGS_STACKTEXT          1222
#define IDC_SETTINGS_STACK              1223
#define IDC_SETTINGS_STACKLAST          1223
#define IDC_SOURCEFILE_NAME             1300
#define IDC_SOURCEFILE_PATH             1301
#define IDC_SOURCEFILE_LINES            1302
#define IDC_FUNCTION_NAME               1400
#define IDC_FUNCTION_FILE               1401
#define IDC_FUNCTION_LINE               1402
#define IDC_FUNCTION_FROM               1403
#define IDC_FUNCTION_TO                 1404
#define IDC_VARIABLE_NAME               1500
#define IDC_VARIABLE_ADDRESS            1501
#define IDC_VARIABLE_REGISTER           1502
#define IDC_PROJECTWIZARD_IDE           1502
#define IDC_VARIABLE_MEMORY             1503
#define IDC_PROJECTWIZARD_FAMILY        1503
#define IDC_VARIABLE_SOURCE             1504
#define IDC_PROJECTWIZARD_IDELOGO       1504
#define IDC_VARIABLE_LINE               1505
#define IDC_PROJECTWIZARD_FAMILYLOGO    1505
#define IDC_VARIABLE_GLOBAL             1506
#define IDC_PLUGINS_FAMILYS             1506
#define IDC_VARIABLE_FUNCTIONTEXT       1507
#define IDC_PLUGINS_IDES                1507
#define IDC_VARIABLE_FUNCTION           1508
#define IDC_COMMSTIMEOUT_ENABLE         1508
#define IDC_VARIABLE_SCOPEFROM          1509
#define IDC_COMMSTIMEOUT_PERIOD         1509
#define IDC_VARIABLE_SCOPETEXT          1510
#define IDC_COMMSTIMEOUT_TEXT           1510
#define IDC_VARIABLE_SCOPETO            1511
#define IDC_COMMSTIMEOUT_MS             1511
#define IDC_VARIABLE_DATATYPE           1512
#define IDC_VARIABLE_POINTER            1513
#define IDC_VARIABLE_ARRAY              1514
#define IDC_VARIABLE_DIMENSIONSTEXT     1515
#define IDC_VARIABLE_DIMENSIONS         1516
#define IDC_VARIABLE_SIZE               1517
#define IDC_VARIABLE_VALUE              1518
#define IDC_VARIABLE_DECLARATIONTEXT    1519
#define IDC_VARIABLE_DECLARATION        1520
#define IDC_ASMVARIABLE_REGISTER        1600
#define IDC_ASMVARIABLE_MEMORY          1601
#define IDC_ASMVARIABLE_NAME            1602
#define IDC_ASMVARIABLE_ADDRESS         1603
#define IDC_ASMVARIABLE_GLOBAL          1604
#define IDC_ASMVARIABLE_SCOPETEXT       1605
#define IDC_ASMVARIABLE_SCOPEFROM       1606
#define IDC_ASMVARIABLE_SCOPETO         1607
#define IDC_ASMVARIABLE_DATATYPE        1608
#define IDC_ASMVARIABLE_POINTER         1609
#define IDC_ASMVARIABLE_ARRAY           1610
#define IDC_ASMVARIABLE_DIMENSIONS      1611
#define IDC_ASMVARIABLE_DIMENSIONSTEXT  1612
#define IDC_ASMVARIABLE_DECLARATION     1613
#define IDC_ASMVARIABLE_VALUE           1614
#define IDC_ASMVARIABLE_SIZE            1615
#define ID_INDICATOR_FAMILY             9000
#define ID_INDICATOR_CPU                9001
#define ID_INDICATOR_PACKAGE            9002
#define ID_INDICATOR_PC                 9003
#define ID_INDICATOR_COMPORT            9004
#define ID_INDICATOR_BAUD               9005
#define ID_FILE_NEWPROJECT              10000
#define ID_FILE_OPENPROJECT             10001
#define IDM_FILE_SAVE                   10002
#define IDM_FILE_SAVEAS                 10003
#define ID_FILE_CLOSEPROJECT            10004
#define ID_FILE_RECENTPROJECT           10050
#define IDM_VIEW_MAINTOOLBAR            10100
#define IDM_VIEW_TARGETCONTROLBAR       10101
#define ID_VIEW_STATUSBAR               10102
#define ID_VIEW_PROJECT                 10103
#define ID_VIEW_REGISTERS               10104
#define ID_VIEW_MEMORY_SFRS             10105
#define ID_VIEW_MEMORY_SRAM             10106
#define ID_VIEW_MEMORY_EEPROM           10107
#define ID_VIEW_WATCH                   10108
#define ID_VIEW_STACK                   10109
#define IDM_VIEW_CHIP                   10110
#define ID_VIEW_SOURCE                  10150
#define ID_PROJECT_SETTINGS             10200
#define ID_PROJECT_REFRESH              10201
#define ID_PREFS_SOURCE_SYNTAXHI        10301
#define ID_PREFS_SOURCE_TRACKPC         10302
#define IDM_PREFS_SOURCE_ASM            10303
#define IDM_PREFS_SOURCE_ADDRESS        10304
#define ID_PREFS_SOURCE_CODE            10305
#define IDM_WINDOW_CASCADE              10400
#define IDM_WINDOW_PREV                 10401
#define IDM_WINDOW_NEXT                 10402
#define ID_HELP_HELPTOPICS              10500
#define ID_HELP_ABOUT                   10501
#define ID_HELP_REGISTER                10502
#define IDM_HELP_EXPORT                 10503
#define IDM_HELP_IDE                    10550
#define IDC_PROJECTBAR_OPEN             11000
#define IDC_PROJECTBAR_SAVE             11001
#define IDC_PROJECTBAR_SETTINGS         11002
#define IDC_PROJECTBAR_REFRESH          11003
#define IDC_PROJECTBAR_COMMS            11004
#define IDC_PROJECTBAR_VIEWPROJECT      11005
#define IDC_PROJECTBAR_VIEWREGISTERS    11006
#define IDC_PROJECTBAR_VIEWSFRS         11007
#define IDC_PROJECTBAR_VIEWSRAM         11008
#define IDC_PROJECTBAR_VIEWEEPROM       11009
#define IDC_PROJECTBAR_VIEWWATCH        11010
#define IDC_PROJECTBAR_VIEWSTACK        11011
#define IDC_PROJECTBAR_VIEWCHIP         11012
#define IDC_PROJECTBAR_SYNTAXHI         11013
#define IDC_PROJECTBAR_TRACKPC          11014
#define IDC_PROJECTBAR_ASSEMBLER        11015
#define IDC_PROJECTBAR_ADDRESSES        11016
#define IDC_PROJECTBAR_MACHINECODE      11017
#define ID_SINGLESTEP                   11100
#define ID_CSTEP                        11101
#define ID_CSTEPINTO                    11102
#define ID_CSTEPOVER                    11103
#define ID_CSTEPOUT                     11104
#define ID_STEPTOCURSOR                 11105
#define ID_ANIMATE                      11106
#define ID_TOSOFTBP                     11107
#define ID_COMPLEXBP                    11108
#define ID_TOHARDBP                     11109
#define ID_SNAPSHOT                     11110
#define ID_PAUSETARGET                  11111
#define ID_RESETTARGET                  11112
#define IDM_CONTEXT_PROJECT             14000
#define IDM_CONTEXT_FILE                14001
#define IDM_CONTEXT_FUNCTION            14002
#define IDM_CONTEXT_VARIABLE            14003
#define IDM_CONTEXT_WATCHSRC            14004
#define IDM_CONTEXT_WATCHASM            14005
#define IDM_CONTEXT_WATCHNEW            14006
#define IDM_CONTEXT_PROJECT_EXPAND      15001
#define IDM_CONTEXT_FILE_OPEN           15010
#define IDM_CONTEXT_FILE_PROPERTIES     15011
#define IDM_CONTEXT_FILE_EXPAND         15012
#define IDM_CONTEXT_FUNCTION_SHOW       15020
#define IDM_CONTEXT_FUNCTION_PROPERTIES 15021
#define IDM_CONTEXT_FUNCTION_EXPAND     15022
#define IDM_CONTEXT_VARIABLE_SHOW       15030
#define IDM_CONTEXT_VARIABLE_ADDTOWATCH 15031
#define IDM_CONTEXT_VARIABLE_PROPERTIES 15032
#define IDM_CONTEXT_WATCHSRC_PROPERTIES 15033
#define IDM_CONTEXT_WATCHSRC_DELETE     15034
#define IDM_CONTEXT_WATCHASM_EDIT       15035
#define IDM_CONTEXT_WATCHASM_DELETE     15036
#define IDM_CONTEXT_WATCHNEW_ADD        15037
#define ID_BUTTON15039                  15039
#define IDM_HELP_PLUGINS                15047
#define IDM_PREFS_MONITORCOMMS          15048
#define IDM_PREFS_COMMSTIMEOUT          15049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        348
#define _APS_NEXT_COMMAND_VALUE         15050
#define _APS_NEXT_CONTROL_VALUE         1512
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
