#define IsLowTsop  (!( PINB & _BV(PB0)))
#define TSOP4      (!(PINC & _BV(PC5)))
#define TSOP3      (!(PINC & _BV(PC4)))
#define TSOP2      (!(PINC & _BV(PC3)))
#define TSOP1      (!(PINC & _BV(PC2)))
#define TSOP0      (!(PINC & _BV(PC1)))
#define TSOP5      (!(PIND & _BV(PD7)))
#define TSOP6      (!(PIND & _BV(PD6)))
#define TSOP7      (!(PIND & _BV(PD5)))

