cd "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3\"
C:
del "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3\tiny26hexdispdriverrp3.map"
del "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3\tiny26hexdispdriverrp3.lst"
"C:\Program Files\Atmel\AVR Tools\AvrAssembler\avrasm32.exe" -fI "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3\Tiny26HexDispDriverRP3.asm" -o "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3\tiny26hexdispdriverrp3.hex" -d "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3\tiny26hexdispdriverrp3.obj" -e "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3\tiny26hexdispdriverrp3.eep" -I "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3" -I "C:\Program Files\Atmel\AVR Tools\AvrAssembler\AppNotes" -w  -m "C:\Program Files\Atmel\AVR Tools\AvrStudio4\Tiny26HexDispDriverRP3\tiny26hexdispdriverrp3.map"
