Desktop/Copy of GPS_TRACE/SRC/GSMParser.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <avr/interrupt.h>
#include <avr/signal.h>
#include `lcd.h`
#include `GSMParser.h`
Functions
void InitGSMParser ()
Feeds the buffer of the GSMParser.
void GSMFeedBuffer (char pdata)
int ProcessGSMCOM ()
Analyseerd inkomende data.
int ProcessGSMLEX ()
Verwerkt het initialisatie commando van een binnenkomende gesprek (CLIP).
void ProcessGSM ()
Initialiseerd de GSM Parser.
Variables
int count
int fora = 0
Function Documentation
void GSMFeedBuffer (char pdata)
Definition at line 19 of file GSMParser.c.
void InitGSMParser ()
Feeds the buffer of the GSMParser.
Parameters:
Incoming Character
Returns: none
Definition at line 12 of file GSMParser.c.
void ProcessGSM ()
Initialiseerd de GSM Parser.
Parameters:
none
Returns: none
Definition at line 59 of file GSMParser.c.
Referenced by GSMFeedBuffer().
int ProcessGSMCOM ()
Analyseerd inkomende data.
Parameters:
none
Returns: none
Definition at line 25 of file GSMParser.c.
Referenced by ProcessGSM().
int ProcessGSMLEX ()
Verwerkt het initialisatie commando van een binnenkomende gesprek (CLIP).
Parameters:
none
Returns: none
Definition at line 42 of file GSMParser.c.
Referenced by ProcessGSM().
Variable Documentation
int count
Definition at line 9 of file GSMParser.c.
Referenced by InitGSMParser().
int fora = 0
Definition at line 10 of file GSMParser.c.
Referenced by initNMEA(), and ProcessNMEA().