Desktop/Copy of GPS_TRACE/SRC/NMEA0183Parser.h File Reference
Functions
void initNMEA ()
Initialiseerd de NMEA Parser.
void NMEAFeedBuffer (char pdata)
voert de buffer van de parser & Start data analyse
void UpdateStatus ()
Update de gps positie variablen.
void ProcessNMEA ()
Statemachine voor analyse van NMEA data.
int ProcessCMD ()
vult de buffer voor het initialisatie commando
int GetFixState ()
Bepaald of er al dan niet een GPS-fix is.
void GetField (int fieldnumber, int offset)
Verkrijgt velden uit de GPGGSA sentence.
Variables
int state
int CMD_count
int COMMAND_count
char data
char CMD [4]
char COMMAND [200]
int test
int fora
just for debugging
char * testch
char DisplayBuffer_1 [7]
char result [10]
Function Documentation
void GetField (int fieldnumber, int offset)
Verkrijgt velden uit de GPGGSA sentence.
Parameters:
velnummer (int), offset (int)
Returns: none
Definition at line 96 of file NMEA0183Parser.c.
References COMMAND, COMMAND_count, and result.
int GetFixState ()
Bepaald of er al dan niet een GPS-fix is.
Parameters:
none
Returns: Fixstate 0/1
void initNMEA ()
Initialiseerd de NMEA Parser.
Parameters:
none
Returns: none
Definition at line 11 of file NMEA0183Parser.c.
References CMD_count, COMMAND_count, fora, state, and test.
void NMEAFeedBuffer (char pdata)
voert de buffer van de parser & Start data analyse
Parameters:
none
Returns: none
Definition at line 19 of file NMEA0183Parser.c.
References data, and ProcessNMEA().
int ProcessCMD ()
vult de buffer voor het initialisatie commando
Parameters:
none
Returns: none
Definition at line 25 of file NMEA0183Parser.c.
References CMD, CMD_count, and data.
void ProcessNMEA ()
Statemachine voor analyse van NMEA data.
Parameters:
none
Returns: none
Definition at line 45 of file NMEA0183Parser.c.
References CMD, COMMAND, COMMAND_count, data, fora, ProcessCMD(), state, and UpdateStatus().
void UpdateStatus ()
Update de gps positie variablen.
Parameters:
none
Returns: none
Definition at line 117 of file NMEA0183Parser.c.
References FormatLatitude(), FormatLongitude(), GetField(), result, setEW_indicator(), setFixstate(), setLatitude(), setLongitude(), setNS_indicator(), showLatitudeFormatted(), showLongitudeFormatted(), and test.
Variable Documentation
char CMD[4]
Definition at line 5 of file NMEA0183Parser.h.
Referenced by ProcessCMD(), and ProcessNMEA().
int CMD_count
Definition at line 2 of file NMEA0183Parser.h.
Referenced by initNMEA(), and ProcessCMD().
char COMMAND[200]
Definition at line 6 of file NMEA0183Parser.h.
Referenced by GetField(), and ProcessNMEA().
int COMMAND_count
Definition at line 3 of file NMEA0183Parser.h.
Referenced by GetField(), initNMEA(), and ProcessNMEA().
char data
Definition at line 4 of file NMEA0183Parser.h.
Referenced by lcd_read(), NMEAFeedBuffer(), ProcessCMD(), and ProcessNMEA().
char DisplayBuffer_1[7]
Definition at line 10 of file NMEA0183Parser.h.
int fora
just for debugging
Definition at line 8 of file NMEA0183Parser.h.
char result[10]
Definition at line 11 of file NMEA0183Parser.h.
Referenced by GetField(), and UpdateStatus().
int state
Definition at line 1 of file NMEA0183Parser.h.
Referenced by initNMEA(), and ProcessNMEA().
int test
Definition at line 7 of file NMEA0183Parser.h.
Referenced by initNMEA(), and UpdateStatus().
char* testch
Definition at line 9 of file NMEA0183Parser.h.