Desktop/Copy of GPS_TRACE/SRC/NMEA0183Parser.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <avr/interrupt.h>
#include <avr/signal.h>
#include `NMEA0183Parser.h`
#include `lcd.h`
#include `RS232.h`
#include `status.h`
Functions
void initNMEA ()
Initialiseerd de NMEA Parser.
void NMEAFeedBuffer (char pdata)
voert de buffer van de parser & Start data analyse
int ProcessCMD ()
vult de buffer voor het initialisatie commando
void ProcessNMEA ()
Statemachine voor analyse van NMEA data.
void GetField (int fieldnumber, int offset)
Verkrijgt velden uit de GPGGSA sentence.
void UpdateStatus ()
Update de gps positie variablen.
Function Documentation
void GetField (int fieldnumber, int offset)
Verkrijgt velden uit de GPGGSA sentence.
Parameters:
velnummer (int), offset (int)
Returns: none
Definition at line 96 of file NMEA0183Parser.c.
Referenced by UpdateStatus().
void initNMEA ()
Initialiseerd de NMEA Parser.
Parameters:
none
Returns: none
Definition at line 11 of file NMEA0183Parser.c.
void NMEAFeedBuffer (char pdata)
voert de buffer van de parser & Start data analyse
Parameters:
none
Returns: none
Definition at line 19 of file NMEA0183Parser.c.
int ProcessCMD ()
vult de buffer voor het initialisatie commando
Parameters:
none
Returns: none
Definition at line 25 of file NMEA0183Parser.c.
Referenced by ProcessNMEA().
void ProcessNMEA ()
Statemachine voor analyse van NMEA data.
Parameters:
none
Returns: none
Definition at line 45 of file NMEA0183Parser.c.
Referenced by NMEAFeedBuffer().
void UpdateStatus ()
Update de gps positie variablen.
Parameters:
none
Returns: none
Definition at line 117 of file NMEA0183Parser.c.
Referenced by ProcessNMEA().