Desktop/Copy of GPS_TRACE/SRC/RS232.c File Reference
#include <avr/io.h>
#include `RS232.h`
Defines
#define F_OSC 4000000
#define UART_BAUD_RATE 4800
#define UART_BAUD_CALC(UART_BAUD_RATE, F_OSC) ((F_OSC)/((UART_BAUD_RATE)*16l)-1)
Functions
void uart0_init (char *s)
void uart0_putc (unsigned char c)
initialize UART0
void uart0_puts (char *s)
put char to UART0
void uart0_send_initial_char ()
put string to UART0
void uart1_init ()
Send initials char to UART0.
void uart1_putc (unsigned char c)
initialize UART1
void uart1_puts (char *s)
put char to UART1
void uart1_send_initial_char ()
put string UART1
Define Documentation
#define F_OSC 4000000
Definition at line 4 of file RS232.c.
Referenced by uart0_init(), and uart1_init().
#define UART_BAUD_CALC(UART_BAUD_RATE, F_OSC) ((F_OSC)/((UART_BAUD_RATE)*16l)-1)
Definition at line 6 of file RS232.c.
Referenced by uart0_init(), and uart1_init().
#define UART_BAUD_RATE 4800
Definition at line 5 of file RS232.c.
Referenced by uart0_init(), and uart1_init().
Function Documentation
void uart0_init (char * s)
Definition at line 8 of file RS232.c.
References F_OSC, UART_BAUD_CALC, and UART_BAUD_RATE.
Referenced by InitUarts().
void uart0_putc (unsigned char c)
initialize UART0
Parameters:
none
Returns: none
Definition at line 21 of file RS232.c.
Referenced by ReportPosition(), and uart0_puts().
void uart0_puts (char * s)
put char to UART0
Parameters:
none
Returns: none
Definition at line 28 of file RS232.c.
Referenced by initGSM(), ReportPosition(), and sendTestSMS().
void uart0_send_initial_char ()
put string to UART0
Parameters:
none
Returns: none
Definition at line 36 of file RS232.c.
Referenced by InitUarts().
void uart1_init ()
Send initials char to UART0.
Parameters:
none
Returns: none
Definition at line 44 of file RS232.c.
Referenced by InitUarts().
void uart1_putc (unsigned char c)
initialize UART1
Parameters:
none
Returns: none
Definition at line 57 of file RS232.c.
Referenced by uart1_puts().
void uart1_puts (char * s)
put char to UART1
Parameters:
none
Returns: none
Definition at line 64 of file RS232.c.
void uart1_send_initial_char ()
put string UART1
Parameters:
none
Returns: none
Definition at line 73 of file RS232.c.