Desktop/Copy of GPS_TRACE/SRC/init.h File Reference
Functions
void InitLCDText ()
void InitUarts ()
Initialiseert het Display en plaats de welkomstekst etc.
void initGSM ()
Initialiseerd de UARTS (RS232 Poorten).
void sendTestSMS ()
Initialisatie GSM-Module (aanloggen op het netwerk, pincode, etc).
void delay_ms (unsigned short ms)
[debugger functie] Met deze functie kan indien nodig een SMS worden gestuurd voor test doeleinden
Function Documentation
void delay_ms (unsigned short ms)
[debugger functie] Met deze functie kan indien nodig een SMS worden gestuurd voor test doeleinden
Parameters:
none
Returns: none
Definition at line 5 of file init.c.
void initGSM ()
Initialiseerd de UARTS (RS232 Poorten).
Parameters:
none
Returns: none
Definition at line 40 of file init.c.
References delay_ms(), and uart0_puts().
void InitLCDText ()
Definition at line 19 of file init.c.
References lcd_clrscr(), LCD_DISP_ON, lcd_gotoxy(), lcd_init(), and lcd_puts().
void InitUarts ()
Initialiseert het Display en plaats de welkomstekst etc.
Parameters:
none
Returns: none
Definition at line 32 of file init.c.
References uart0_init(), uart0_send_initial_char(), and uart1_init().
void sendTestSMS ()
Initialisatie GSM-Module (aanloggen op het netwerk, pincode, etc).
Parameters:
none
Returns: none
Definition at line 55 of file init.c.
References delay_ms(), and uart0_puts().