Desktop/Copy of GPS_TRACE/SRC/init.c File Reference
#include `lcd.h`
#include `RS232.h`
#include <avr/interrupt.h>
Functions
void delay_ms (unsigned short ms)
[debugger functie] Met deze functie kan indien nodig een SMS worden gestuurd voor test doeleinden
void InitLCDText ()
void InitUarts ()
Initialiseert het Display en plaats de welkomstekst etc.
void initGSM ()
Initialiseerd de UARTS (RS232 Poorten).
void sendTestSMS ()
Initialisatie GSM-Module (aanloggen op het netwerk, pincode, etc).
Function Documentation
void delay_ms (unsigned short ms)
[debugger functie] Met deze functie kan indien nodig een SMS worden gestuurd voor test doeleinden
Parameters:
none
Returns: none
Definition at line 5 of file init.c.
Referenced by initGSM(), ReportPosition(), and sendTestSMS().
void initGSM ()
Initialiseerd de UARTS (RS232 Poorten).
Parameters:
none
Returns: none
Definition at line 40 of file init.c.
void InitLCDText ()
Definition at line 19 of file init.c.
void InitUarts ()
Initialiseert het Display en plaats de welkomstekst etc.
Parameters:
none
Returns: none
Definition at line 32 of file init.c.
void sendTestSMS ()
Initialisatie GSM-Module (aanloggen op het netwerk, pincode, etc).
Parameters:
none
Returns: none
Definition at line 55 of file init.c.