Desktop/Copy of GPS_TRACE/SRC/led.h File Reference
Functions
void led_init ()
void led_yellow_on ()
Set PC0, PC1 and PC2 as output.
void led_yellow_off ()
Turn on the yellow LED.
void led_red_on ()
Turn off the yellow LED.
void led_red_off ()
Turn on the red LED.
void led_green_on ()
Turn off the red LED.
void led_green_off ()
Turn on the green LED.
void led_toggle_red ()
Turn off the green LED.
void led_toggle_green ()
Toggle state of red LED.
Variables
int ledstategreen
int ledstatered
Function Documentation
void led_green_off ()
Turn on the green LED.
Parameters:
none
Returns: none
Definition at line 41 of file led.c.
void led_green_on ()
Turn off the red LED.
Parameters:
none
Returns: none
Definition at line 36 of file led.c.
void led_init ()
Definition at line 6 of file led.c.
References ledstategreen, and ledstatered.
void led_red_off ()
Turn on the red LED.
Parameters:
none
Returns: none
Definition at line 31 of file led.c.
void led_red_on ()
Turn off the yellow LED.
Parameters:
none
Returns: none
Definition at line 26 of file led.c.
void led_toggle_green ()
Toggle state of red LED.
Parameters:
none
Returns: none
Definition at line 46 of file led.c.
References led_green_off(), led_green_on(), and ledstategreen.
void led_toggle_red ()
Turn off the green LED.
Parameters:
none
Returns: none
Definition at line 60 of file led.c.
References led_red_off(), led_red_on(), and ledstatered.
void led_yellow_off ()
Turn on the yellow LED.
Parameters:
none
Returns: none
Definition at line 21 of file led.c.
void led_yellow_on ()
Set PC0, PC1 and PC2 as output.
Parameters:
none
Returns: none
Definition at line 16 of file led.c.
Variable Documentation
int ledstategreen
Definition at line 8 of file led.h.
Referenced by led_init(), and led_toggle_green().
int ledstatered
Definition at line 9 of file led.h.
Referenced by led_init(), and led_toggle_red().