Desktop/Copy of GPS_TRACE/SRC/status.h File Reference
Functions
void setFixstate (char c)
int getFixstate ()
Sets the status of GPS fix (fixstate).
void showFixstate ()
Returns the value of GPS fix (fixstate).
void setNS_indicator (char c)
Displays the fix state on LCD.
char getNS_indicator ()
Sets the North/South inidicator.
char getEW_indicator ()
Gets the North/South inidicator.
void setEW_indicator (char c)
Gets the East/West inidicator.
char * getLatitude ()
Sets the East/West inidicator.
void setLatitude (char *s)
Returns a char pointer the the N degree.
char * getLongitude ()
Sets GPS Latitude.
void setLongitude (char *s)
Gets GPS Longitude.
void FormatLongitude ()
Sets GPS Longitude.
void FormatLatitude ()
Formats GPS Latitude van ddmm.mmmm naar DD°MM.mmm.
void showLatitudeFormatted ()
Formats GPS Longitude van dddmm.mmmm naar DD°MM.mmm.
void showLongitudeFormatted ()
Shows GPS Latitude in DD°MM.mmm format on LCD.
char * getLatitudeFormatted ()
Shows GPS Longitude in DD°MM.mmm format on LCD.
char * getLongitudeFormatted ()
void ReportPosition ()
Variables
int fixstate
char NSindicator
Represents the fixstate of the GPS-module.
char EWindicator
Represents the Latitude North/South indicator.
char Latitude [10]
Represents the Longitude East/West indicator.
char LatitudeFormatted [15]
Represents the Latitude in ddmm.mmmm format.
char Longitude [10]
Represents the Latitude in DD°MM.mmm format.
char LongitudeFormatted [15]
Represents the Longitude in dddmm.mmmm format.
Function Documentation
void FormatLatitude ()
Formats GPS Latitude van ddmm.mmmm naar DD°MM.mmm.
Parameters:
none
Returns: none
Definition at line 114 of file status.c.
References Latitude, LatitudeFormatted, and NSindicator.
void FormatLongitude ()
Sets GPS Longitude.
Parameters:
char *s (result)
Returns: none
Definition at line 96 of file status.c.
References EWindicator, Longitude, and LongitudeFormatted.
char getEW_indicator ()
Gets the North/South inidicator.
Parameters:
none
Returns: NSindicator (char)
Definition at line 70 of file status.c.
References EWindicator.
int getFixstate ()
Sets the status of GPS fix (fixstate).
Parameters:
char c --> this is the result of getfield (5,2);
Returns: none
Definition at line 10 of file status.c.
References fixstate.
char* getLatitude ()
Sets the East/West inidicator.
Parameters:
char c
Returns: none
Definition at line 75 of file status.c.
References Latitude.
char* getLatitudeFormatted ()
Shows GPS Longitude in DD°MM.mmm format on LCD.
Parameters:
none
Returns: none
Definition at line 131 of file status.c.
References LatitudeFormatted.
char* getLongitude ()
Sets GPS Latitude.
Parameters:
char *s (result)
Returns: none
Definition at line 86 of file status.c.
References Longitude.
char* getLongitudeFormatted ()
Definition at line 136 of file status.c.
References LongitudeFormatted.
char getNS_indicator ()
Sets the North/South inidicator.
Parameters:
char c
Returns: none
Definition at line 65 of file status.c.
References NSindicator.
void ReportPosition ()
Definition at line 142 of file status.c.
References delay_ms(), getFixstate(), getLatitudeFormatted(), getLongitudeFormatted(), GSM_COMMAND, led_yellow_off(), uart0_putc(), and uart0_puts().
void setEW_indicator (char c)
Gets the East/West inidicator.
Parameters:
none
Returns: EWindicator (char)
Definition at line 55 of file status.c.
References EWindicator.
void setFixstate (char c)
Definition at line 15 of file status.c.
References fixstate.
void setLatitude (char * s)
Returns a char pointer the the N degree.
Parameters:
none
Returns: char* Latitude
Definition at line 80 of file status.c.
References Latitude.
void setLongitude (char * s)
Gets GPS Longitude.
Parameters:
none
Returns: char* Longitude
Definition at line 91 of file status.c.
References Longitude.
void setNS_indicator (char c)
Displays the fix state on LCD.
Parameters:
none
Returns: none
Definition at line 60 of file status.c.
References NSindicator.
void showFixstate ()
Returns the value of GPS fix (fixstate).
Parameters:
none
Returns: 1 or 0 --> 1 means fix, 0 means no fix
Definition at line 27 of file status.c.
References getFixstate(), lcd_gotoxy(), and lcd_puts().
void showLatitudeFormatted ()
Formats GPS Longitude van dddmm.mmmm naar DD°MM.mmm.
Parameters:
none
Returns: none
Definition at line 42 of file status.c.
References getLatitudeFormatted(), lcd_gotoxy(), and lcd_puts().
void showLongitudeFormatted ()
Shows GPS Latitude in DD°MM.mmm format on LCD.
Parameters:
none
Returns: none
Definition at line 49 of file status.c.
References getLongitudeFormatted(), lcd_gotoxy(), and lcd_puts().
Variable Documentation
char EWindicator
Represents the Latitude North/South indicator.
Definition at line 120 of file status.h.
Referenced by FormatLongitude(), getEW_indicator(), and setEW_indicator().
int fixstate
Definition at line 110 of file status.h.
Referenced by getFixstate(), and setFixstate().
char Latitude[10]
Represents the Longitude East/West indicator.
Definition at line 125 of file status.h.
Referenced by FormatLatitude(), getLatitude(), and setLatitude().
char LatitudeFormatted[15]
Represents the Latitude in ddmm.mmmm format.
Definition at line 130 of file status.h.
Referenced by FormatLatitude(), and getLatitudeFormatted().
char Longitude[10]
Represents the Latitude in DD°MM.mmm format.
Definition at line 136 of file status.h.
Referenced by FormatLongitude(), getLongitude(), and setLongitude().
char LongitudeFormatted[15]
Represents the Longitude in dddmm.mmmm format.
Definition at line 141 of file status.h.
Referenced by FormatLongitude(), and getLongitudeFormatted().
char NSindicator
Represents the fixstate of the GPS-module.
Definition at line 115 of file status.h.
Referenced by FormatLatitude(), getNS_indicator(), and setNS_indicator().