Desktop/Copy of GPS_TRACE/SRC/status.c File Reference
#include <inttypes.h>
#include <avr\pgmspace.h>
#include `status.h`
#include `lcd.h`
#include `RS232.h`
#include `init.h`
#include `led.h`
#include `GSMParser.h`
Functions
int getFixstate ()
Sets the status of GPS fix (fixstate).
void setFixstate (char c)
void showFixstate ()
Returns the value of GPS fix (fixstate).
void showLatitudeFormatted ()
Formats GPS Longitude van dddmm.mmmm naar DD°MM.mmm.
void showLongitudeFormatted ()
Shows GPS Latitude in DD°MM.mmm format on LCD.
void setEW_indicator (char c)
Gets the East/West inidicator.
void setNS_indicator (char c)
Displays the fix state on LCD.
char getNS_indicator ()
Sets the North/South inidicator.
char getEW_indicator ()
Gets the North/South inidicator.
char * getLatitude ()
Sets the East/West inidicator.
void setLatitude (char *s)
Returns a char pointer the the N degree.
char * getLongitude ()
Sets GPS Latitude.
void setLongitude (char *s)
Gets GPS Longitude.
void FormatLongitude ()
Sets GPS Longitude.
void FormatLatitude ()
Formats GPS Latitude van ddmm.mmmm naar DD°MM.mmm.
char * getLatitudeFormatted ()
Shows GPS Longitude in DD°MM.mmm format on LCD.
char * getLongitudeFormatted ()
void ReportPosition ()
Function Documentation
void FormatLatitude ()
Formats GPS Latitude van ddmm.mmmm naar DD°MM.mmm.
Parameters:
none
Returns: none
Definition at line 114 of file status.c.
Referenced by UpdateStatus().
void FormatLongitude ()
Sets GPS Longitude.
Parameters:
char *s (result)
Returns: none
Definition at line 96 of file status.c.
Referenced by UpdateStatus().
char getEW_indicator ()
Gets the North/South inidicator.
Parameters:
none
Returns: NSindicator (char)
Definition at line 70 of file status.c.
int getFixstate ()
Sets the status of GPS fix (fixstate).
Parameters:
char c --> this is the result of getfield (5,2);
Returns: none
Definition at line 10 of file status.c.
Referenced by ReportPosition(), and showFixstate().
char* getLatitude ()
Sets the East/West inidicator.
Parameters:
char c
Returns: none
Definition at line 75 of file status.c.
char* getLatitudeFormatted ()
Shows GPS Longitude in DD°MM.mmm format on LCD.
Parameters:
none
Returns: none
Definition at line 131 of file status.c.
Referenced by ReportPosition(), and showLatitudeFormatted().
char* getLongitude ()
Sets GPS Latitude.
Parameters:
char *s (result)
Returns: none
Definition at line 86 of file status.c.
char* getLongitudeFormatted ()
Definition at line 136 of file status.c.
Referenced by ReportPosition(), and showLongitudeFormatted().
char getNS_indicator ()
Sets the North/South inidicator.
Parameters:
char c
Returns: none
Definition at line 65 of file status.c.
void ReportPosition ()
Definition at line 142 of file status.c.
Referenced by ProcessGSM().
void setEW_indicator (char c)
Gets the East/West inidicator.
Parameters:
none
Returns: EWindicator (char)
Definition at line 55 of file status.c.
Referenced by UpdateStatus().
void setFixstate (char c)
Definition at line 15 of file status.c.
Referenced by UpdateStatus().
void setLatitude (char * s)
Returns a char pointer the the N degree.
Parameters:
none
Returns: char* Latitude
Definition at line 80 of file status.c.
Referenced by UpdateStatus().
void setLongitude (char * s)
Gets GPS Longitude.
Parameters:
none
Returns: char* Longitude
Definition at line 91 of file status.c.
Referenced by UpdateStatus().
void setNS_indicator (char c)
Displays the fix state on LCD.
Parameters:
none
Returns: none
Definition at line 60 of file status.c.
Referenced by UpdateStatus().
void showFixstate ()
Returns the value of GPS fix (fixstate).
Parameters:
none
Returns: 1 or 0 --> 1 means fix, 0 means no fix
Definition at line 27 of file status.c.
void showLatitudeFormatted ()
Formats GPS Longitude van dddmm.mmmm naar DD°MM.mmm.
Parameters:
none
Returns: none
Definition at line 42 of file status.c.
Referenced by UpdateStatus().
void showLongitudeFormatted ()
Shows GPS Latitude in DD°MM.mmm format on LCD.
Parameters:
none
Returns: none
Definition at line 49 of file status.c.
Referenced by UpdateStatus().