/* Copyright 2006 Google */ 
var tn_a=false,tn_b=null,tn_=true;function tn_aa(a){if(a in tn_ba)return tn_ba[a];return tn_ba[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var tn_ba={};var tn_ca={Pa:function(a){return a.document.body.scrollTop},Qa:function(a){return a.document.documentElement.scrollTop},Ja:function(a){return a.pageYOffset}};var tn_da={Pa:function(a){return a.document.body.scrollLeft},Qa:function(a){return a.document.documentElement.scrollLeft},Ja:function(a){return a.pageXOffset}};
function tn_ea(a,b){try{if(!window.opera&&"compatMode"in a.document&&a.document.compatMode=="CSS1Compat")return b.Qa(a);else if(tn_aa("msie")&&!window.opera)return b.Pa(a)}catch(c){}return b.Ja(a)}function tn_fa(a){return document.getElementById(a)}function tn_ga(a){return document.all[a]}var tn_ha=document.getElementById?tn_fa:tn_ga;
function tn_ia(a){try{if(window.parent!=window&&window.parent.log){window.parent.log(window.name+"::"+a);return}}catch(b){}var c=tn_ha("log");if(c){var d="<p class=logentry><span class=logdate>"+new Date+"</span><span class=logmsg>"+a+"</span></p>";c.innerHTML=d+c.innerHTML}else window.status=a};function tn_c(a,b,c){this.x=a;this.y=b;this.coordinateFrame=c||tn_b}tn_c.prototype.toString=function(){return"[P "+this.x+","+this.y+"]"};tn_c.prototype.clone=function(){return new tn_c(this.x,this.y,this.coordinateFrame)};function tn_ja(a,b){this.dx=a;this.dy=b}tn_ja.prototype.toString=function(){return"[D "+this.dx+","+this.dy+"]"};function tn_d(a,b,c,d,e){this.x=a;this.y=b;this.w=c;this.h=d;this.coordinateFrame=e||tn_b}
tn_d.prototype.contains=function(a){return this.x<=a.x&&a.x<this.x+this.w&&this.y<=a.y&&a.y<this.y+this.h};tn_d.prototype.toString=function(){return"[R "+this.w+"x"+this.h+"+"+this.x+"+"+this.y+"]"};tn_d.prototype.clone=function(){return new tn_d(this.x,this.y,this.w,this.h,this.coordinateFrame)};function tn_ka(a){if(!a)return tn_b;function b(j){for(var g=a.offsetParent;g&&g.offsetParent;g=g.offsetParent){if(g.scrollLeft)j.x-=g.scrollLeft;if(g.scrollTop)j.y-=g.scrollTop}}var c;c=a.ownerDocument&&a.ownerDocument.parentWindow?a.ownerDocument.parentWindow:window;if(a.ownerDocument&&a.ownerDocument.getBoxObjectFor){var d=a.ownerDocument.getBoxObjectFor(a),e=new tn_d(d.x,d.y,d.width,d.height,c);b(e);return e}if(a.getBoundingClientRect){var f=a.getBoundingClientRect();return new tn_d(f.left+tn_ea(c,
tn_da),f.top+tn_ea(c,tn_ca),f.right-f.left,f.bottom-f.top,c)}var h=0,i=0;for(var k=a;k.offsetParent;k=k.offsetParent){h+=k.offsetLeft;i+=k.offsetTop}var e=new tn_d(h,i,a.offsetWidth,a.offsetHeight,c);b(e);return e};var tn_e=(function(){var a=[" ","\u0120",-1,"!","\u0120",-1,"\u0120","\u0120",0,"\u0121","\u0120",-1,"\u0121","\u0120|\u0121",0,"\u0122","\u0120|\u0121",-1,"\u0120","[\u0120]",0,"\u0121","[\u0120]",-1,"\u0121","[\u0120\u0121]",0,"\u0122","[\u0120\u0121]",-1,"\u0121","[\u0120-\u0121]",0,"\u0122","[\u0120-\u0121]",-1];for(var b=0;b<a.length;b+=3)if(a[b].search(new RegExp(a[b+1]))!=a[b+2])return tn_a;return tn_})(),tn_la="([ \t\r\n]+)?=([ \t\r\n]+)?",tn_ma="&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_na="[ \t\r\n]+version"+
tn_la+"(\"1\\.0\"|'1\\.0')",tn_oa=tn_e?"A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u0131\u0134-\u013e\u0141-\u0148\u014a-\u017e\u0180-\u01c3\u01cd-\u01f0\u01f4-\u01f5\u01fa-\u0217\u0250-\u02a8\u02bb-\u02c1\u0386\u0388-\u038a\u038c\u038e-\u03a1\u03a3-\u03ce\u03d0-\u03d6\u03da\u03dc\u03de\u03e0\u03e2-\u03f3\u0401-\u040c\u040e-\u044f\u0451-\u045c\u045e-\u0481\u0490-\u04c4\u04c7-\u04c8\u04cb-\u04cc\u04d0-\u04eb\u04ee-\u04f5\u04f8-\u04f9\u0531-\u0556\u0559\u0561-\u0586\u05d0-\u05ea\u05f0-\u05f2\u0621-\u063a\u0641-\u064a\u0671-\u06b7\u06ba-\u06be\u06c0-\u06ce\u06d0-\u06d3\u06d5\u06e5-\u06e6\u0905-\u0939\u093d\u0958-\u0961\u0985-\u098c\u098f-\u0990\u0993-\u09a8\u09aa-\u09b0\u09b2\u09b6-\u09b9\u09dc-\u09dd\u09df-\u09e1\u09f0-\u09f1\u0a05-\u0a0a\u0a0f-\u0a10\u0a13-\u0a28\u0a2a-\u0a30\u0a32-\u0a33\u0a35-\u0a36\u0a38-\u0a39\u0a59-\u0a5c\u0a5e\u0a72-\u0a74\u0a85-\u0a8b\u0a8d\u0a8f-\u0a91\u0a93-\u0aa8\u0aaa-\u0ab0\u0ab2-\u0ab3\u0ab5-\u0ab9\u0abd\u0ae0\u0b05-\u0b0c\u0b0f-\u0b10\u0b13-\u0b28\u0b2a-\u0b30\u0b32-\u0b33\u0b36-\u0b39\u0b3d\u0b5c-\u0b5d\u0b5f-\u0b61\u0b85-\u0b8a\u0b8e-\u0b90\u0b92-\u0b95\u0b99-\u0b9a\u0b9c\u0b9e-\u0b9f\u0ba3-\u0ba4\u0ba8-\u0baa\u0bae-\u0bb5\u0bb7-\u0bb9\u0c05-\u0c0c\u0c0e-\u0c10\u0c12-\u0c28\u0c2a-\u0c33\u0c35-\u0c39\u0c60-\u0c61\u0c85-\u0c8c\u0c8e-\u0c90\u0c92-\u0ca8\u0caa-\u0cb3\u0cb5-\u0cb9\u0cde\u0ce0-\u0ce1\u0d05-\u0d0c\u0d0e-\u0d10\u0d12-\u0d28\u0d2a-\u0d39\u0d60-\u0d61\u0e01-\u0e2e\u0e30\u0e32-\u0e33\u0e40-\u0e45\u0e81-\u0e82\u0e84\u0e87-\u0e88\u0e8a\u0e8d\u0e94-\u0e97\u0e99-\u0e9f\u0ea1-\u0ea3\u0ea5\u0ea7\u0eaa-\u0eab\u0ead-\u0eae\u0eb0\u0eb2-\u0eb3\u0ebd\u0ec0-\u0ec4\u0f40-\u0f47\u0f49-\u0f69\u10a0-\u10c5\u10d0-\u10f6\u1100\u1102-\u1103\u1105-\u1107\u1109\u110b-\u110c\u110e-\u1112\u113c\u113e\u1140\u114c\u114e\u1150\u1154-\u1155\u1159\u115f-\u1161\u1163\u1165\u1167\u1169\u116d-\u116e\u1172-\u1173\u1175\u119e\u11a8\u11ab\u11ae-\u11af\u11b7-\u11b8\u11ba\u11bc-\u11c2\u11eb\u11f0\u11f9\u1e00-\u1e9b\u1ea0-\u1ef9\u1f00-\u1f15\u1f18-\u1f1d\u1f20-\u1f45\u1f48-\u1f4d\u1f50-\u1f57\u1f59\u1f5b\u1f5d\u1f5f-\u1f7d\u1f80-\u1fb4\u1fb6-\u1fbc\u1fbe\u1fc2-\u1fc4\u1fc6-\u1fcc\u1fd0-\u1fd3\u1fd6-\u1fdb\u1fe0-\u1fec\u1ff2-\u1ff4\u1ff6-\u1ffc\u2126\u212a-\u212b\u212e\u2180-\u2182\u3041-\u3094\u30a1-\u30fa\u3105-\u312c\uac00-\ud7a3":
"A-Za-z",tn_pa=tn_e?"\u4e00-\u9fa5\u3007\u3021-\u3029":"",tn_qa=tn_e?"\u0300-\u0345\u0360-\u0361\u0483-\u0486\u0591-\u05a1\u05a3-\u05b9\u05bb-\u05bd\u05bf\u05c1-\u05c2\u05c4\u064b-\u0652\u0670\u06d6-\u06dc\u06dd-\u06df\u06e0-\u06e4\u06e7-\u06e8\u06ea-\u06ed\u0901-\u0903\u093c\u093e-\u094c\u094d\u0951-\u0954\u0962-\u0963\u0981-\u0983\u09bc\u09be\u09bf\u09c0-\u09c4\u09c7-\u09c8\u09cb-\u09cd\u09d7\u09e2-\u09e3\u0a02\u0a3c\u0a3e\u0a3f\u0a40-\u0a42\u0a47-\u0a48\u0a4b-\u0a4d\u0a70-\u0a71\u0a81-\u0a83\u0abc\u0abe-\u0ac5\u0ac7-\u0ac9\u0acb-\u0acd\u0b01-\u0b03\u0b3c\u0b3e-\u0b43\u0b47-\u0b48\u0b4b-\u0b4d\u0b56-\u0b57\u0b82-\u0b83\u0bbe-\u0bc2\u0bc6-\u0bc8\u0bca-\u0bcd\u0bd7\u0c01-\u0c03\u0c3e-\u0c44\u0c46-\u0c48\u0c4a-\u0c4d\u0c55-\u0c56\u0c82-\u0c83\u0cbe-\u0cc4\u0cc6-\u0cc8\u0cca-\u0ccd\u0cd5-\u0cd6\u0d02-\u0d03\u0d3e-\u0d43\u0d46-\u0d48\u0d4a-\u0d4d\u0d57\u0e31\u0e34-\u0e3a\u0e47-\u0e4e\u0eb1\u0eb4-\u0eb9\u0ebb-\u0ebc\u0ec8-\u0ecd\u0f18-\u0f19\u0f35\u0f37\u0f39\u0f3e\u0f3f\u0f71-\u0f84\u0f86-\u0f8b\u0f90-\u0f95\u0f97\u0f99-\u0fad\u0fb1-\u0fb7\u0fb9\u20d0-\u20dc\u20e1\u302a-\u302f\u3099\u309a":
"",tn_ra=tn_e?"0-9\u0660-\u0669\u06f0-\u06f9\u0966-\u096f\u09e6-\u09ef\u0a66-\u0a6f\u0ae6-\u0aef\u0b66-\u0b6f\u0be7-\u0bef\u0c66-\u0c6f\u0ce6-\u0cef\u0d66-\u0d6f\u0e50-\u0e59\u0ed0-\u0ed9\u0f20-\u0f29":"0-9",tn_sa=tn_e?"\u00b7\u02d0\u02d1\u0387\u0640\u0e46\u0ec6\u3005\u3031-\u3035\u309d-\u309e\u30fc-\u30fe":"",tn_ta=tn_oa+tn_pa,tn_ua=tn_ta+tn_ra+"\\._:"+tn_qa+tn_sa+"-",tn_va="["+tn_ta+"_:]["+tn_ua+"]*",tn_wa="&"+tn_va+";",tn_xa=tn_wa+"|"+tn_ma,tn_ya='"(([^<&"]|'+tn_xa+")*)\"|'(([^<&']|"+tn_xa+")*)'",
tn_za="("+tn_va+")"+tn_la+"("+tn_ya+")",tn_Aa="[ \t\r\n]+version"+tn_la+"(\"1\\.1\"|'1\\.1')",tn_Ba=tn_e?":A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd":":A-Z_a-z",tn_Ca=tn_Ba+(tn_e?"\\.0-9\u00b7\u0300-\u036f\u203f-\u2040-":"\\.0-9-"),tn_Da="["+tn_Ba+"]["+tn_Ca+"]*",tn_Ea="&"+tn_Da+";",tn_Fa=tn_Ea+"|"+tn_ma,tn_Ga='"(([^<&"]|'+tn_Fa+")*)\"|'(([^<&']|"+tn_Fa+")*)'",tn_Ha="("+tn_Da+")"+tn_la+"("+
tn_Ga+")",tn_Ia=tn_ta+tn_ra+"\\._"+tn_qa+tn_sa+"-",tn_Ja="["+tn_ta+"_]["+tn_Ia+"]*";function tn_Ka(){}function tn_f(a){a||tn_g("Assertion failed")}function tn_La(a,b){var c=a.indexOf(b);if(c==-1)return[a];var d=[];d.push(a.substr(0,c));while(c!=-1){var e=a.indexOf(b,c+1);e!=-1?d.push(a.substr(c+1,e-c-1)):d.push(a.substr(c+1));c=e}return d}
function tn_Ma(a,b){if(b.nodeType==3)return a.createTextNode(b.nodeValue);else if(b.nodeType==4)return a.createCDATASection(b.nodeValue);else if(b.nodeType==1){var c=a.createElement(b.nodeName);for(var d=0;d<b.attributes.length;++d){var e=b.attributes[d],f=e.nodeName,h=e.nodeValue;c.setAttribute(f,h)}for(var i=b.firstChild;i;i=i.nextSibling){var k=arguments.callee(a,i);c.appendChild(k)}return c}else return a.createComment(b.nodeName)}function tn_Na(){this.keys=[]}tn_Na.prototype.size=function(){return this.keys.length};
tn_Na.prototype.add=function(a,b){var c=b||1;if(!this.contains(a)){this[":"+a]=c;this.keys.push(a)}};tn_Na.prototype.remove=function(a){if(this.contains(a)){delete this[":"+a];tn_Oa(this.keys,a,tn_)}};tn_Na.prototype.contains=function(a){return typeof this[":"+a]!="undefined"};tn_Na.prototype.map=function(a){for(var b=0;b<this.keys.length;++b){var c=this.keys[b];a.call(this,c,this[":"+c])}};
tn_Na.prototype.clear=function(){for(var a=0;a<this.keys.length;++a)delete this[":"+this.keys[a]];this.keys.length=0};function tn_Pa(a,b){for(var c=0;c<a.length;++c)b.call(this,a[c],c)}function tn_Qa(a,b){var c=[];for(var d=0;d<a.length;++d)c.push(b(a[d]));return c}function tn_Ra(a){for(var b=0;b<a.length/2;++b){var c=a[b],d=a.length-b-1;a[b]=a[d];a[d]=c}}function tn_Oa(a,b,c){var d=0;for(var e=0;e<a.length;++e)if(a[e]===b||c&&a[e]==b){a.splice(e--,1);d++}return d}
function tn_Sa(a,b){for(var c=0;c<b.length;++c)a.push(b[c])}function tn_h(a){if(!a)return"";var b="";if(a.nodeType==3||a.nodeType==4||a.nodeType==2)b+=a.nodeValue;else if(a.nodeType==1||a.nodeType==9||a.nodeType==11)for(var c=0;c<a.childNodes.length;++c)b+=arguments.callee(a.childNodes[c]);return b}function tn_Ta(a,b){var c=[];tn_Ua(a,c,b);return c.join("")}
function tn_Ua(a,b,c){if(a.nodeType==3)b.push(tn_Va(a.nodeValue));else if(a.nodeType==4)c?b.push(a.nodeValue):b.push("<![CDATA["+a.nodeValue+"]]\>");else if(a.nodeType==8)b.push("<!--"+a.nodeValue+"--\>");else if(a.nodeType==1){b.push("<"+tn_Wa(a));for(var d=0;d<a.attributes.length;++d){var e=a.attributes[d];e&&e.nodeName&&e.nodeValue&&b.push(" "+tn_Wa(e)+'="'+tn_Va(e.nodeValue).replace(/\"/g,"&quot;")+'"')}if(a.childNodes.length==0)b.push("/>");else{b.push(">");for(var d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],
b,c);b.push("</"+tn_Wa(a)+">")}}else if(a.nodeType==9||a.nodeType==11)for(var d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],b,c)}function tn_Wa(a){return a.prefix&&a.nodeName.indexOf(a.prefix+":")!=0?a.prefix+":"+a.nodeName:a.nodeName}function tn_Va(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function tn_g(a){if(typeof Error!="undefined")throw new Error(a||"Assertion Failed");else throw a;};function tn_Xa(a){var b=tn_La(a,"&"),c=b[0];for(var d=1;d<b.length;++d){var e=b[d].indexOf(";");if(e==-1){c+=b[d];continue}var f=b[d].substring(0,e),h=b[d].substring(e+1),i;switch(f){case "lt":i="<";break;case "gt":i=">";break;case "amp":i="&";break;case "quot":i='"';break;case "apos":i="'";break;case "nbsp":i=String.fromCharCode(160);break;default:var k=window.document.createElement("span");k.innerHTML="&"+f+"; ";i=k.childNodes[0].nodeValue.charAt(0)}c+=i+h}return c}
var tn_Ya=new RegExp("^("+tn_va+")"),tn_Za=new RegExp(tn_za,"g"),tn__a=new RegExp("^("+tn_Da+")"),tn_0a=new RegExp(tn_Ha,"g");
function tn_1a(a){var b=/\/$/,c,d;if(a.match(/^<\?xml/))if(a.search(new RegExp(tn_na))==5){c=tn_Ya;d=tn_Za}else if(a.search(new RegExp(tn_Aa))==5){c=tn__a;d=tn_0a}else alert("VersionInfo is missing, or unknown version number.");else{c=tn_Ya;d=tn_Za}var e=new tn_i,f=e,h=[],i=f;h.push(i);var k="",j=tn_La(a,"<");for(var g=1;g<j.length;++g){var l=tn_La(j[g],">"),o=l[0],q=tn_Xa(l[1]||"");if(k){var s=j[g].indexOf(k);if(s!=-1){var r=j[g].substring(0,s);i.nodeValue+="<"+r;h.pop();i=h[h.length-1];q=j[g].substring(s+
k.length);k=""}else{i.nodeValue+="<"+j[g];q=tn_b}}else if(o.indexOf("![CDATA[")==0){var m="![CDATA[".length,s=j[g].indexOf("]]\>");if(s!=-1){var r=j[g].substring(m,s),n=e.createCDATASection(r);i.appendChild(n)}else{var r=j[g].substring(m);q=tn_b;var n=e.createCDATASection(r);i.appendChild(n);i=n;h.push(n);k="]]\>"}}else if(o.indexOf("!--")==0){var m="!--".length,s=j[g].indexOf("--\>");if(s!=-1){var r=j[g].substring(m,s),n=e.createComment(r);i.appendChild(n)}else{var r=j[g].substring(m);q=tn_b;var n=
e.createComment(r);i.appendChild(n);i=n;h.push(n);k="--\>"}}else if(o.charAt(0)=="/"){h.pop();i=h[h.length-1]}else if(!(o.charAt(0)=="?"))if(!(o.charAt(0)=="!")){var y=o.match(b),v=c.exec(o)[1],n=e.createElement(v),p;while(p=d.exec(o)){var D=tn_Xa(p[5]||p[7]||"");n.setAttribute(p[1],D)}i.appendChild(n);if(!y){i=n;h.push(n)}}q&&i!=f&&i.appendChild(e.createTextNode(q))}return f}
function tn_2a(a,b,c){var d;if(b){d=b.call(tn_b,a);if(typeof d=="boolean"&&!d)return tn_a}for(var e=a.firstChild;e;e=e.nextSibling)if(e.nodeType==1){d=arguments.callee.call(this,e,b,c);if(typeof d=="boolean"&&!d)return tn_a}if(c){d=c.call(tn_b,a);if(typeof d=="boolean"&&!d)return tn_a}}function tn_j(a,b,c,d){this.attributes=[];this.childNodes=[];tn_j.init.call(this,a,b,c,d)}
tn_j.init=function(a,b,c,d){this.nodeType=a-0;this.nodeName=""+b;this.nodeValue=""+c;this.ownerDocument=d;this.firstChild=tn_b;this.lastChild=tn_b;this.nextSibling=tn_b;this.previousSibling=tn_b;this.parentNode=tn_b};tn_j.Ba=[];
tn_j.recycle=function(a){if(!a)return;if(a.constructor==tn_i){tn_j.recycle(a.documentElement);return}if(a.constructor!=this)return;tn_j.Ba.push(a);for(var b=0;b<a.attributes.length;++b)tn_j.recycle(a.attributes[b]);for(var c=0;c<a.childNodes.length;++c)tn_j.recycle(a.childNodes[c]);a.attributes.length=0;a.childNodes.length=0;tn_j.init.call(a,0,"","",tn_b)};tn_j.create=function(a,b,c,d){if(tn_j.Ba.length>0){var e=tn_j.Ba.pop();tn_j.init.call(e,a,b,c,d);return e}else return new tn_j(a,b,c,d)};
tn_j.prototype.appendChild=function(a){if(this.childNodes.length==0)this.firstChild=a;a.previousSibling=this.lastChild;a.nextSibling=tn_b;if(this.lastChild)this.lastChild.nextSibling=a;a.parentNode=this;this.lastChild=a;this.childNodes.push(a)};
tn_j.prototype.replaceChild=function(a,b){if(b==a)return;for(var c=0;c<this.childNodes.length;++c)if(this.childNodes[c]==b){this.childNodes[c]=a;var d=b.parentNode;b.parentNode=tn_b;a.parentNode=d;d=b.previousSibling;b.previousSibling=tn_b;a.previousSibling=d;if(a.previousSibling)a.previousSibling.nextSibling=a;d=b.nextSibling;b.nextSibling=tn_b;a.nextSibling=d;if(a.nextSibling)a.nextSibling.previousSibling=a;if(this.firstChild==b)this.firstChild=a;if(this.lastChild==b)this.lastChild=a;break}};
tn_j.prototype.insertBefore=function(a,b){if(b==a)return;if(b.parentNode!=this)return;a.parentNode&&a.parentNode.removeChild(a);var c=[];for(var d=0;d<this.childNodes.length;++d){var e=this.childNodes[d];if(e==b){c.push(a);a.parentNode=this;a.previousSibling=b.previousSibling;b.previousSibling=a;if(a.previousSibling)a.previousSibling.nextSibling=a;a.nextSibling=b;if(this.firstChild==b)this.firstChild=a}c.push(e)}this.childNodes=c};
tn_j.prototype.removeChild=function(a){var b=[];for(var c=0;c<this.childNodes.length;++c){var d=this.childNodes[c];if(d!=a)b.push(d);else{if(d.previousSibling)d.previousSibling.nextSibling=d.nextSibling;if(d.nextSibling)d.nextSibling.previousSibling=d.previousSibling;if(this.firstChild==d)this.firstChild=d.nextSibling;if(this.lastChild==d)this.lastChild=d.previousSibling}}this.childNodes=b};tn_j.prototype.hasAttributes=function(){return this.attributes.length>0};
tn_j.prototype.setAttribute=function(a,b){for(var c=0;c<this.attributes.length;++c)if(this.attributes[c].nodeName==a){this.attributes[c].nodeValue=""+b;return}this.attributes.push(tn_j.create(2,a,b,this))};tn_j.prototype.getAttribute=function(a){for(var b=0;b<this.attributes.length;++b)if(this.attributes[b].nodeName==a)return this.attributes[b].nodeValue;return tn_b};
tn_j.prototype.removeAttribute=function(a){var b=[];for(var c=0;c<this.attributes.length;++c)this.attributes[c].nodeName!=a&&b.push(this.attributes[c]);this.attributes=b};tn_j.prototype.getElementsByTagName=function(a){var b=[];tn_2a(this,function(c){c.nodeName==a&&b.push(c)},tn_b);return b};tn_j.prototype.getElementById=function(a){var b=tn_b;tn_2a(this,function(c){if(c.getAttribute("id")==a){b=c;return tn_a}},tn_b);return b};
function tn_i(){tn_j.call(this,9,"#document",tn_b,tn_b);this.documentElement=tn_b}tn_i.prototype=new tn_j(9,"#document");tn_i.prototype.clear=function(){tn_j.recycle(this.documentElement);this.documentElement=tn_b};tn_i.prototype.appendChild=function(a){tn_j.prototype.appendChild.call(this,a);this.documentElement=this.childNodes[0]};tn_i.prototype.createElement=function(a){return tn_j.create(1,a,tn_b,this)};
tn_i.prototype.createDocumentFragment=function(){return tn_j.create(11,"#document-fragment",tn_b,this)};tn_i.prototype.createTextNode=function(a){return tn_j.create(3,"#text",a,this)};tn_i.prototype.createAttribute=function(a){return tn_j.create(2,a,tn_b,this)};tn_i.prototype.createComment=function(a){return tn_j.create(8,"#comment",a,this)};tn_i.prototype.createCDATASection=function(a){return tn_j.create(4,"#cdata-section",a,this)};function tn_3a(a,b){tn_4a(new tn_k(a,b),b)}
function tn_4a(a,b){var c=b.getAttribute("select");if(c){b.removeAttribute("select");tn_5a(a,b,c);return}var d=b.getAttribute("display");if(d)if(tn_6a(d,a).d())b.removeAttribute("display");else{b.parentNode.removeChild(b);return}var e=b.getAttribute("values");if(e){b.removeAttribute("values");tn_7a(a,b,e)}var f=b.getAttribute("transclude");if(f){var h=tn_8a(f,b.ownerDocument);if(h){b.parentNode.replaceChild(h,b);tn_4a(a,h)}else b.parentNode.removeChild(b);tn_j.recycle(b);return}var i=b.getAttribute("content");
if(i){b.removeAttribute("content");tn_9a(a,b,i)}else{var k=[];for(var j=0;j<b.childNodes.length;++j)b.childNodes[j].nodeType==1&&k.push(b.childNodes[j]);for(var j=0;j<k.length;++j)tn_4a(a,k[j])}}
function tn_5a(a,b,c){var d=c.split(/;/),e=tn_6a(d[0],a).c();if(e.length>0){var f=[];for(var h=1;h<e.length;++h){var i=tn_Ma(b.ownerDocument,b);f.push(i);b.parentNode.insertBefore(i,b)}f.push(b);var k=[];for(var j=1;j<d.length;++j){var g=d[j],l=0,o;if(g.charAt(l)=="#"){o="number";l++}else o="text";var q;if(g.charAt(l)=="-"){q="descending";l++}else q="ascending";var s=tn_$a(d[j].substr(l));k.push({expr:s,type:o,order:q})}var r=a.clone(e[0],0,e);tn_ab(r,k);for(var h=0;h<r.u();++h)r.nodelist[h].nodeType==
1&&tn_4a(r.clone(r.nodelist[h],h),f[h])}else b.parentNode.removeChild(b)}function tn_7a(a,b,c){var d=c.split(/;/);for(var e=0;e<d.length;++e){var f=d[e].indexOf(":");if(f<0)continue;var h=d[e].substr(0,f),i=tn_6a(d[e].substr(f+1),a);if(h.charAt(0)=="$")a.ya(h.substr(1),i);else h&&b.setAttribute(h,i.a())}}
function tn_9a(a,b,c){while(b.firstChild)b.removeChild(b.firstChild);var d=tn_6a(c,a);if(d.type=="node-set")for(var e=0;e<d.value.length;++e){var f=d.value[e];if(f.nodeType==1)for(var h=f.firstChild;h;h=h.nextSibling){var i=tn_Ma(b.ownerDocument,h);b.appendChild(i)}else if(f.nodeType==2){var k=b.ownerDocument.createTextNode(f.nodeValue);b.appendChild(k)}}else{var k=b.ownerDocument.createTextNode(d.a());b.appendChild(k)}}function tn_6a(a,b){var c=tn_$a(a),d=c.evaluate(b);return d}
function tn_8a(a,b){var c=b.getElementById(a);if(c){var d=tn_Ma(b,c);return d}else return tn_b};function tn_$a(a){tn_bb();var b=tn_cb[a];if(b)return b;if(a.match(/^(\$|@)?\w+$/i)){var c=tn_db(a);tn_cb[a]=c;return c}if(a.match(/^\w+(\/\w+)*$/i)){var c=tn_eb(a);tn_cb[a]=c;return c}var d=a,e=[],f=tn_b,h=tn_b,i=tn_a,k=0,j=0,g=0;while(!i){k++;a=a.replace(/^\s*/,"");h=f;f=tn_b;var l=tn_b,o="";for(var q=0;q<tn_fb.length;++q){var s=tn_fb[q].re.exec(a);j++;if(s&&s.length>0&&s[0].length>o.length){l=tn_fb[q];o=s[0];break}}if(l&&(l==tn_gb||l==tn_hb||l==tn_ib||l==tn_jb)&&(!h||h.tag==tn_kb||h.tag==tn_lb||
h.tag==tn_l||h.tag==tn_mb||h.tag==tn_nb))l=tn_ob;if(l){a=a.substr(o.length);f={tag:l,match:o,prec:l.prec?l.prec:0,expr:new tn_pb(o)}}else i=tn_;while(tn_qb(e,f)){g++;tn_Ka("stack: "+tn_rb(e))}}tn_Ka("stack: "+tn_rb(e));e.length!=1&&tn_g("XPath parse error "+d+":\n"+tn_rb(e));var s=e[0].expr;tn_cb[d]=s;return s}var tn_cb={};
function tn_qb(a,b){var c=tn_b;if(a.length>0){var d=a[a.length-1],e=tn_sb[d.tag.key];if(e)for(var f=0;f<e.length;++f){var h=e[f],i=tn_tb(a,h[1]);if(i.length){c={tag:h[0],rule:h,match:i};c.prec=tn_ub(c);break}}}var k;if(c&&(!b||c.prec>b.prec||b.tag.left&&c.prec>=b.prec)){for(var f=0;f<c.match.matchlength;++f)a.pop();var j=tn_Qa(c.match,function(g){return g.expr});c.expr=c.rule[3].apply(tn_b,j);a.push(c);k=tn_}else{b&&a.push(b);k=tn_a}return k}
function tn_tb(a,b){var c=a.length,d=b.length,e,f,h=[];h.matchlength=0;var i=0;for(e=d-1,f=c-1;e>=0&&f>=0;--e,f-=i){i=0;var k=[];if(b[e]==tn_vb){e-=1;h.push(k);while(f-i>=0&&a[f-i].tag==b[e]){k.push(a[f-i]);i+=1;h.matchlength+=1}}else if(b[e]==tn_wb){e-=1;h.push(k);while(f-i>=0&&i<2&&a[f-i].tag==b[e]){k.push(a[f-i]);i+=1;h.matchlength+=1}}else if(b[e]==tn_xb){e-=1;h.push(k);if(a[f].tag==b[e])while(f-i>=0&&a[f-i].tag==b[e]){k.push(a[f-i]);i+=1;h.matchlength+=1}else return[]}else if(a[f].tag==b[e]){h.push(a[f]);
i+=1;h.matchlength+=1}else return[];tn_Ra(k);k.expr=tn_Qa(k,function(j){return j.expr})}tn_Ra(h);return e==-1?h:[]}function tn_ub(a){var b=0;if(a.rule)if(a.rule.length>=3&&a.rule[2]>=0)b=a.rule[2];else for(var c=0;c<a.rule[1].length;++c){var d=a.rule[1][c].prec||2;b=Math.max(b,d)}else if(a.tag)b=a.tag.prec||2;else if(a.length)for(var e=0;e<a.length;++e){var d=tn_ub(a[e]);b=Math.max(b,d)}return b}function tn_rb(a){var b="";for(var c=0;c<a.length;++c){if(b)b+="\n";b+=a[c].tag.label}return b}
function tn_k(a,b,c,d,e){this.node=a;this.stylesheet=b||tn_b;this.position=c||0;this.nodelist=d||[a];this.variables={};this.parent=e||tn_b;this.root=e?e.root:this.node.nodeType==9?a:a.ownerDocument}tn_k.prototype.clone=function(a,b,c){return new tn_k(a||this.node,this.stylesheet,typeof b!="undefined"?b:this.position,c||this.nodelist,this)};tn_k.prototype.ya=function(a,b){this.variables[a]=b};
tn_k.prototype.O=function(a){return typeof this.variables[a]!="undefined"?this.variables[a]:this.parent?this.parent.O(a):tn_b};tn_k.prototype.nb=function(a){this.node=this.nodelist[a];this.position=a};tn_k.prototype.u=function(){return this.nodelist.length};function tn_m(a){this.value=a;this.type="string"}tn_m.prototype.a=function(){return this.value};tn_m.prototype.d=function(){return this.value.length>0};tn_m.prototype.b=function(){return this.value-0};tn_m.prototype.c=function(){tn_g(this)};
function tn_n(a){this.value=a;this.type="boolean"}tn_n.prototype.a=function(){return""+this.value};tn_n.prototype.d=function(){return this.value};tn_n.prototype.b=function(){return this.value?1:0};tn_n.prototype.c=function(){tn_g(this)};function tn_o(a){this.value=a;this.type="number"}tn_o.prototype.a=function(){return""+this.value};tn_o.prototype.d=function(){return!!this.value};tn_o.prototype.b=function(){return this.value-0};tn_o.prototype.c=function(){tn_g(this)};
function tn_p(a){this.value=a;this.type="node-set"}tn_p.prototype.a=function(){return this.value.length==0?"":tn_h(this.value[0])};tn_p.prototype.d=function(){return this.value.length>0};tn_p.prototype.b=function(){return this.a()-0};tn_p.prototype.c=function(){return this.value};function tn_pb(a){this.value=a}tn_pb.prototype.evaluate=function(){return new tn_m(this.value)};function tn_q(){this.absolute=tn_a;this.rootExpr=tn_b;this.steps=[]}tn_q.prototype.l=function(a){this.steps.push(a)};
tn_q.prototype.ua=function(a){this.steps.unshift(a)};tn_q.prototype.evaluate=function(a){var b;b=this.rootExpr?this.rootExpr.evaluate(a).c():this.absolute?[a.root]:[a.node];var c=[];for(var d=0;d<b.length;++d){var e=b[d];tn_yb(c,this.steps,0,e,a)}return new tn_p(c)};function tn_yb(a,b,c,d,e){var f=b[c],h=e.clone(d),i=f.evaluate(h).c();for(var k=0;k<i.length;++k)c==b.length-1?a.push(i[k]):tn_yb(a,b,c+1,i[k],e)}function tn_r(a,b,c){this.axis=a;this.nodetest=b;this.predicate=c||[]}
tn_r.prototype.Ea=function(a){this.predicate.push(a)};
tn_r.prototype.evaluate=function(a){var b=a.node,c=[];if(this.axis==tn_s.ANCESTOR_OR_SELF){c.push(b);for(var d=b.parentNode;d;d=d.parentNode)c.push(d)}else if(this.axis==tn_s.ANCESTOR)for(var d=b.parentNode;d;d=d.parentNode)c.push(d);else if(this.axis==tn_s.ATTRIBUTE)tn_Sa(c,b.attributes);else if(this.axis==tn_s.CHILD)tn_Sa(c,b.childNodes);else if(this.axis==tn_s.DESCENDANT_OR_SELF){c.push(b);tn_zb(c,b)}else if(this.axis==tn_s.DESCENDANT)tn_zb(c,b);else if(this.axis==tn_s.FOLLOWING)for(var d=b;d;d=
d.parentNode)for(var e=d.nextSibling;e;e=e.nextSibling){c.push(e);tn_zb(c,e)}else if(this.axis==tn_s.FOLLOWING_SIBLING)for(var d=b.nextSibling;d;d=d.nextSibling)c.push(d);else if(this.axis==tn_s.NAMESPACE)tn_g("not implemented: axis namespace");else if(this.axis==tn_s.PARENT)b.parentNode&&c.push(b.parentNode);else if(this.axis==tn_s.PRECEDING)for(var d=b;d;d=d.parentNode)for(var e=d.previousSibling;e;e=e.previousSibling){c.push(e);tn_Ab(c,e)}else if(this.axis==tn_s.PRECEDING_SIBLING)for(var d=b.previousSibling;d;d=
d.previousSibling)c.push(d);else this.axis==tn_s.SELF?c.push(b):tn_g("ERROR -- NO SUCH AXIS: "+this.axis);var f=c;c=[];for(var h=0;h<f.length;++h){var d=f[h];this.nodetest.evaluate(a.clone(d,h,f)).d()&&c.push(d)}for(var h=0;h<this.predicate.length;++h){var f=c;c=[];for(var i=0;i<f.length;++i){var d=f[i];this.predicate[h].evaluate(a.clone(d,i,f)).d()&&c.push(d)}}return new tn_p(c)};function tn_Bb(){this.value=new tn_n(tn_)}tn_Bb.prototype.evaluate=function(){return this.value};function tn_Cb(){}
tn_Cb.prototype.evaluate=function(a){return new tn_n(a.node.nodeType==1||a.node.nodeType==2)};function tn_Db(){}tn_Db.prototype.evaluate=function(a){return new tn_n(a.node.nodeType==3)};function tn_Eb(){}tn_Eb.prototype.evaluate=function(a){return new tn_n(a.node.nodeType==8)};function tn_Fb(a){this.target=a}tn_Fb.prototype.evaluate=function(a){return new tn_n(a.node.nodeType==7&&(!this.target||a.node.nodeName==this.target))};function tn_Gb(a){this.regex=new RegExp("^"+a+":");this.nsprefix=a}
tn_Gb.prototype.evaluate=function(a){var b=a.node;return new tn_n(this.regex.test(b.nodeName))};function tn_Hb(a){this.name=a}tn_Hb.prototype.evaluate=function(a){var b=a.node;return new tn_n(b.nodeName==this.name)};function tn_Ib(a){this.expr=a}tn_Ib.prototype.evaluate=function(a){var b=this.expr.evaluate(a);return b.type=="number"?new tn_n(a.position==b.b()-1):new tn_n(b.d())};function tn_Jb(a){this.name=a;this.args=[]}tn_Jb.prototype.ea=function(a){this.args.push(a)};
tn_Jb.prototype.evaluate=function(a){var b=""+this.name.value,c=this.xpathfunctions[b];return c?c.call(this,a):new tn_n(tn_a)};
tn_Jb.prototype.xpathfunctions={last:function(a){tn_f(this.args.length==0);return new tn_o(a.u())},position:function(a){tn_f(this.args.length==0);return new tn_o(a.position+1)},count:function(a){tn_f(this.args.length==1);var b=this.args[0].evaluate(a);return new tn_o(b.c().length)},id:function(a){tn_f(this.args.length==1);var b=this.args[0].evaluate(a),c=[],d;if(b.type=="node-set"){d=[];var e=b.c();for(var f=0;f<e.length;++f){var h=tn_h(e[f]).split(/\s+/);for(var i=0;i<h.length;++i)d.push(h[i])}}else d=
b.a().split(/\s+/);var k=a.node.ownerDocument;for(var f=0;f<d.length;++f){var j=k.getElementById(d[f]);j&&c.push(j)}return new tn_p(c)},"local-name":function(){tn_g("not implmented yet: XPath function local-name()")},"namespace-uri":function(){tn_g("not implmented yet: XPath function namespace-uri()")},name:function(a){tn_f(this.args.length==1||this.args.length==0);var b;b=this.args.length==0?[a.node]:this.args[0].evaluate(a).c();return b.length==0?new tn_m(""):new tn_m(b[0].nodeName)},string:function(a){tn_f(this.args.length==
1||this.args.length==0);return this.args.length==0?new tn_m((new tn_p([a.node])).a()):new tn_m(this.args[0].evaluate(a).a())},concat:function(a){var b="";for(var c=0;c<this.args.length;++c)b+=this.args[c].evaluate(a).a();return new tn_m(b)},document:function(a){var b=this.args[0].evaluate(a).a();if(b===""&&a.stylesheet)return new tn_p([a.stylesheet]);tn_g("Can't resolve uri in document(\""+b+'")')},"starts-with":function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).a();
return new tn_n(b.indexOf(c)==0)},contains:function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).a();return new tn_n(b.indexOf(c)!=-1)},"substring-before":function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).a(),d=b.indexOf(c),e;e=d==-1?"":b.substr(0,d);return new tn_m(e)},"substring-after":function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).a(),d=b.indexOf(c),
e;e=d==-1?"":b.substr(d+c.length);return new tn_m(e)},substring:function(a){tn_f(this.args.length==2||this.args.length==3);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).b(),d;if(this.args.length==2){var e=Math.max(0,Math.round(c)-1);d=b.substr(e)}else{var f=this.args[2].evaluate(a).b(),h=Math.round(c)-1,e=Math.max(0,h),i=Math.round(f)-Math.max(0,-h);d=b.substr(e,i)}return new tn_m(d)},"string-length":function(a){var b;b=this.args.length>0?this.args[0].evaluate(a).a():(new tn_p([a.node])).a();
return new tn_o(b.length)},"normalize-space":function(a){var b;b=this.args.length>0?this.args[0].evaluate(a).a():(new tn_p([a.node])).a();b=b.replace(/^\s*/,"").replace(/\s*$/,"").replace(/\s+/g," ");return new tn_m(b)},translate:function(a){tn_f(this.args.length==3);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).a(),d=this.args[2].evaluate(a).a();for(var e=0;e<c.length;++e)b=b.replace(new RegExp(c.charAt(e),"g"),d.charAt(e));return new tn_m(b)},"boolean":function(a){tn_f(this.args.length==
1);return new tn_n(this.args[0].evaluate(a).d())},not:function(a){tn_f(this.args.length==1);var b=!this.args[0].evaluate(a).d();return new tn_n(b)},"true":function(){tn_f(this.args.length==0);return new tn_n(tn_)},"false":function(){tn_f(this.args.length==0);return new tn_n(tn_a)},lang:function(a){tn_f(this.args.length==1);var b=this.args[0].evaluate(a).a(),c,d=a.node;while(d&&d!=d.parentNode){c=d.getAttribute("xml:lang");if(c)break;d=d.parentNode}if(c){var e=new RegExp("^"+b+"$","i");return new tn_n(e.test(c)||
e.test(c.replace(/_.*$/,"")))}else return new tn_n(tn_a)},number:function(a){tn_f(this.args.length==1||this.args.length==0);return this.args.length==1?new tn_o(this.args[0].evaluate(a).b()):new tn_o((new tn_p([a.node])).b())},sum:function(a){tn_f(this.args.length==1);var b=this.args[0].evaluate(a).c(),c=0;for(var d=0;d<b.length;++d)c+=tn_h(b[d])-0;return new tn_o(c)},floor:function(a){tn_f(this.args.length==1);var b=this.args[0].evaluate(a).b();return new tn_o(Math.floor(b))},ceiling:function(a){tn_f(this.args.length==
1);var b=this.args[0].evaluate(a).b();return new tn_o(Math.ceil(b))},round:function(a){tn_f(this.args.length==1);var b=this.args[0].evaluate(a).b();return new tn_o(Math.round(b))},"ext-join":function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).c(),c=this.args[1].evaluate(a).a(),d="";for(var e=0;e<b.length;++e){if(d)d+=c;d+=tn_h(b[e])}return new tn_m(d)},"ext-if":function(a){tn_f(this.args.length==3);return this.args[0].evaluate(a).d()?this.args[1].evaluate(a):this.args[2].evaluate(a)},
"ext-cardinal":function(a){tn_f(this.args.length>=1);var b=this.args[0].evaluate(a).b(),c=[];for(var d=0;d<b;++d)c.push(a.node);return new tn_p(c)}};function tn_Kb(a,b){this.expr1=a;this.expr2=b}tn_Kb.prototype.evaluate=function(a){var b=this.expr1.evaluate(a).c(),c=this.expr2.evaluate(a).c(),d=b.length;for(var e=0;e<c.length;++e){var f=c[e],h=tn_a;for(var i=0;i<d;++i)if(b[i]==f){h=tn_;i=d}h||b.push(f)}return new tn_p(b)};function tn_Lb(a,b){this.filter=a;this.rel=b}
tn_Lb.prototype.evaluate=function(a){var b=this.filter.evaluate(a).c(),c=[];for(var d=0;d<b.length;++d){var e=this.rel.evaluate(a.clone(b[d],d,b)).c();for(var f=0;f<e.length;++f)c.push(e[f])}return new tn_p(c)};function tn_Mb(a,b){this.expr=a;this.predicate=b}tn_Mb.prototype.evaluate=function(a){var b=this.expr.evaluate(a).c();for(var c=0;c<this.predicate.length;++c){var d=b;b=[];for(var e=0;e<d.length;++e){var f=d[e];this.predicate[c].evaluate(a.clone(f,e,d)).d()&&b.push(f)}}return new tn_p(b)};
function tn_Nb(a){this.expr=a}tn_Nb.prototype.evaluate=function(a){return new tn_o(-this.expr.evaluate(a).b())};function tn_Ob(a,b,c){this.expr1=a;this.expr2=c;this.op=b}
tn_Ob.prototype.evaluate=function(a){var b;switch(this.op.value){case "or":b=new tn_n(this.expr1.evaluate(a).d()||this.expr2.evaluate(a).d());break;case "and":b=new tn_n(this.expr1.evaluate(a).d()&&this.expr2.evaluate(a).d());break;case "+":b=new tn_o(this.expr1.evaluate(a).b()+this.expr2.evaluate(a).b());break;case "-":b=new tn_o(this.expr1.evaluate(a).b()-this.expr2.evaluate(a).b());break;case "*":b=new tn_o(this.expr1.evaluate(a).b()*this.expr2.evaluate(a).b());break;case "mod":b=new tn_o(this.expr1.evaluate(a).b()%
this.expr2.evaluate(a).b());break;case "div":b=new tn_o(this.expr1.evaluate(a).b()/this.expr2.evaluate(a).b());break;case "=":b=this.compare(a,function(c,d){return c==d});break;case "!=":b=this.compare(a,function(c,d){return c!=d});break;case "<":b=this.compare(a,function(c,d){return c<d});break;case "<=":b=this.compare(a,function(c,d){return c<=d});break;case ">":b=this.compare(a,function(c,d){return c>d});break;case ">=":b=this.compare(a,function(c,d){return c>=d});break;default:tn_g("BinaryExpr.evaluate: "+
this.op.value)}return b};
tn_Ob.prototype.compare=function(a,b){var c=this.expr1.evaluate(a),d=this.expr2.evaluate(a),e;if(c.type=="node-set"&&d.type=="node-set"){var f=c.c(),h=d.c();e=tn_a;for(var i=0;i<f.length;++i)for(var k=0;k<h.length;++k)if(b(tn_h(f[i]),tn_h(h[k]))){e=tn_;k=h.length;i=f.length}}else if(c.type=="node-set"||d.type=="node-set")if(c.type=="number"){var j=c.b(),g=d.c();e=tn_a;for(var l=0;l<g.length;++l){var o=tn_h(g[l])-0;if(b(j,o)){e=tn_;break}}}else if(d.type=="number"){var g=c.c(),j=d.b();e=tn_a;for(var l=
0;l<g.length;++l){var o=tn_h(g[l])-0;if(b(o,j)){e=tn_;break}}}else if(c.type=="string"){var j=c.a(),g=d.c();e=tn_a;for(var l=0;l<g.length;++l){var o=tn_h(g[l]);if(b(j,o)){e=tn_;break}}}else if(d.type=="string"){var g=c.c(),j=d.a();e=tn_a;for(var l=0;l<g.length;++l){var o=tn_h(g[l]);if(b(o,j)){e=tn_;break}}}else e=b(c.d(),d.d());else e=c.type=="boolean"||d.type=="boolean"?b(c.d(),d.d()):c.type=="number"||d.type=="number"?b(c.b(),d.b()):b(c.a(),d.a());return new tn_n(!!e)};
function tn_Pb(a){this.value=a}tn_Pb.prototype.evaluate=function(){return new tn_m(this.value)};function tn_Qb(a){this.value=a}tn_Qb.prototype.evaluate=function(){return new tn_o(this.value)};function tn_Rb(a){this.name=a}tn_Rb.prototype.evaluate=function(a){return a.O(this.name)};function tn_t(a){return a}function tn_Sb(a,b){b.absolute=tn_;return b}function tn_Tb(a,b){b.absolute=tn_;b.ua(tn_u(a.value));return b}function tn_Ub(){var a=new tn_q;a.l(tn_u("."));a.absolute=tn_;return a}
function tn_Vb(a){var b=new tn_q;b.absolute=tn_;b.l(tn_u(a.value));return b}function tn_Wb(a){var b=new tn_q;b.l(a);return b}function tn_Xb(a,b,c){a.l(c);return a}function tn_Yb(a,b){a.l(tn_u(b.value));return a}function tn_Zb(a,b,c){var d=new tn_q;d.rootExpr=a;d.l(c);return d}function tn__b(a){return tn_u(a.value)}function tn_0b(a){return tn_u(a.value)}function tn_1b(a,b,c){return new tn_r(a.value,c)}function tn_2b(a,b){return new tn_r("attribute",b)}function tn_3b(a){return new tn_r("child",a)}
function tn_4b(a,b){a.Ea(b);return a}function tn_u(a){switch(a){case "//":return new tn_r("descendant-or-self",new tn_Bb);case ".":return new tn_r("self",new tn_Bb);case "..":return new tn_r("parent",new tn_Bb)}}function tn_5b(){return new tn_Cb}function tn_6b(a){return new tn_Gb(a.value)}function tn_7b(a){return new tn_Hb(a.value)}
function tn_8b(a){var b=a.value.replace(/\s*\($/,"");switch(b){case "node":return new tn_Bb;case "text":return new tn_Db;case "comment":return new tn_Eb;case "processing-instruction":return new tn_Fb("")}}function tn_9b(a,b){var c=a.replace(/\s*\($/,"");c!="processing-instruction"&&tn_g(c);return new tn_Fb(b.value)}function tn_$b(a,b){return new tn_Ib(b)}function tn_ac(a,b){return b}function tn_bc(a){return new tn_Jb(a)}
function tn_cc(a,b,c,d){var e=new tn_Jb(a);e.ea(c);for(var f=0;f<d.length;++f)e.ea(d[f]);return e}function tn_dc(a,b){return b}function tn_ec(a,b,c){return new tn_Kb(a,c)}function tn_fc(a,b,c){return new tn_Lb(a,c)}function tn_gc(a,b,c){c.ua(tn_u(b.value));return new tn_Lb(a,c)}function tn_hc(a,b){return b.length>0?new tn_Mb(a,b):a}function tn_ic(a,b){return new tn_Nb(b)}function tn_v(a,b,c){return new tn_Ob(a,b,c)}
function tn_jc(a){var b=a.value.substring(1,a.value.length-1);return new tn_Pb(b)}function tn_kc(a){return new tn_Qb(a.value)}function tn_lc(a,b){return new tn_Rb(b.value)}function tn_db(a){if(a.charAt(0)=="$")return new tn_Rb(a.substr(1));else if(a.charAt(0)=="@"){var b=new tn_Hb(a.substr(1)),c=new tn_r("attribute",b),d=new tn_q;d.l(c);return d}else if(a.match(/^[0-9]+$/))return new tn_Qb(a);else{var b=new tn_Hb(a),c=new tn_r("child",b),d=new tn_q;d.l(c);return d}}
function tn_eb(a){var b=tn_La(a,"/"),c=new tn_q;for(var d=0;d<b.length;++d){var e=new tn_Hb(b[d]),f=new tn_r("child",e);c.l(f)}return c}
var tn_s={ANCESTOR_OR_SELF:"ancestor-or-self",ANCESTOR:"ancestor",ATTRIBUTE:"attribute",CHILD:"child",DESCENDANT_OR_SELF:"descendant-or-self",DESCENDANT:"descendant",FOLLOWING_SIBLING:"following-sibling",FOLLOWING:"following",NAMESPACE:"namespace",PARENT:"parent",PRECEDING_SIBLING:"preceding-sibling",PRECEDING:"preceding",SELF:"self"},tn_mc=[tn_s.ANCESTOR_OR_SELF,tn_s.ANCESTOR,tn_s.ATTRIBUTE,tn_s.CHILD,tn_s.DESCENDANT_OR_SELF,tn_s.DESCENDANT,tn_s.FOLLOWING_SIBLING,tn_s.FOLLOWING,tn_s.NAMESPACE,tn_s.PARENT,
tn_s.PRECEDING_SIBLING,tn_s.PRECEDING,tn_s.SELF].join("|"),tn_nc={label:"|",prec:17,re:/^\|/},tn_lb={label:"//",prec:19,re:/^\/\//},tn_l={label:"/",prec:30,re:/^\//},tn_mb={label:"::",prec:20,re:/^::/},tn_oc={label:":",prec:1000,re:/^:/},tn_pc={label:"[axis]",re:new RegExp("^("+tn_mc+")")},tn_qc={label:"(",prec:34,re:/^\(/},tn_rc={label:")",re:/^\)/},tn_sc={label:"..",prec:34,re:/^\.\./},tn_tc={label:".",prec:34,re:/^\./},tn_kb={label:"@",prec:34,re:/^@/},tn_uc={label:",",re:/^,/},tn_jb={label:"or",
prec:10,re:/^or\b/},tn_ib={label:"and",prec:11,re:/^and\b/},tn_vc={label:"=",prec:12,re:/^=/},tn_wc={label:"!=",prec:12,re:/^!=/},tn_xc={label:">=",prec:13,re:/^>=/},tn_yc={label:">",prec:13,re:/^>/},tn_zc={label:"<=",prec:13,re:/^<=/},tn_Ac={label:"<",prec:13,re:/^</},tn_Bc={label:"+",prec:14,re:/^\+/,left:tn_},tn_Cc={label:"-",prec:14,re:/^\-/,left:tn_},tn_gb={label:"div",prec:15,re:/^div\b/,left:tn_},tn_hb={label:"mod",prec:15,re:/^mod\b/,left:tn_},tn_Dc={label:"[",prec:32,re:/^\[/},tn_Ec={label:"]",
re:/^\]/},tn_nb={label:"$",re:/^\$/},tn_Fc={label:"[ncname]",re:new RegExp("^"+tn_Ja)},tn_Gc={label:"*",prec:15,re:/^\*/,left:tn_},tn_Hc={label:"[litq]",prec:20,re:/^'[^\']*'/},tn_Ic={label:"[litqq]",prec:20,re:/^"[^\"]*"/},tn_Jc={label:"[number]",prec:35,re:/^\d+(\.\d*)?/},tn_ob={label:"[qname]",re:new RegExp("^("+tn_Ja+":)?"+tn_Ja)},tn_Kc={label:"[nodetest-start]",re:/^(processing-instruction|comment|text|node)\(/},tn_fb=[tn_lb,tn_l,tn_sc,tn_tc,tn_mb,tn_oc,tn_pc,tn_Kc,tn_qc,tn_rc,tn_Dc,tn_Ec,tn_kb,
tn_uc,tn_jb,tn_ib,tn_wc,tn_vc,tn_xc,tn_yc,tn_zc,tn_Ac,tn_Bc,tn_Cc,tn_Gc,tn_nc,tn_hb,tn_gb,tn_Hc,tn_Ic,tn_Jc,tn_ob,tn_Fc,tn_nb],tn_Lc={label:"LocationPath"},tn_w={label:"RelativeLocationPath"},tn_Mc={label:"AbsoluteLocationPath"},tn_x={label:"Step"},tn_y={label:"NodeTest"},tn_Nc={label:"Predicate"},tn_Oc={label:"Literal"},tn_z={label:"Expr"},tn_A={label:"PrimaryExpr"},tn_Pc={label:"Variablereference"},tn_Qc={label:"Number"},tn_Rc={label:"FunctionCall"},tn_Sc={label:"ArgumentRemainder"},tn_B={label:"PathExpr"},
tn_Tc={label:"UnionExpr"},tn_Uc={label:"FilterExpr"},tn_Vc={label:"Digits"},tn_Wc=[tn_Lc,tn_w,tn_Mc,tn_x,tn_y,tn_Nc,tn_Oc,tn_z,tn_A,tn_Pc,tn_Qc,tn_Rc,tn_Sc,tn_B,tn_Tc,tn_Uc,tn_Vc],tn_wb={label:"?"},tn_vb={label:"*"},tn_xb={label:"+"},tn_Xc=[[tn_Lc,[tn_w],18,tn_t],[tn_Lc,[tn_Mc],18,tn_t],[tn_Mc,[tn_l,tn_w],18,tn_Sb],[tn_Mc,[tn_lb,tn_w],18,tn_Tb],[tn_Mc,[tn_l],0,tn_Ub],[tn_Mc,[tn_lb],0,tn_Vb],[tn_w,[tn_x],31,tn_Wb],[tn_w,[tn_w,tn_l,tn_x],31,tn_Xb],[tn_w,[tn_w,tn_lb,tn_x],31,tn_Yb],[tn_w,[tn_A,tn_l,
tn_x],31,tn_Zb],[tn_x,[tn_tc],33,tn__b],[tn_x,[tn_sc],33,tn_0b],[tn_x,[tn_pc,tn_mb,tn_y],33,tn_1b],[tn_x,[tn_kb,tn_y],33,tn_2b],[tn_x,[tn_y],33,tn_3b],[tn_x,[tn_x,tn_Nc],33,tn_4b],[tn_y,[tn_Gc],33,tn_5b],[tn_y,[tn_Fc,tn_oc,tn_Gc],33,tn_6b],[tn_y,[tn_ob],33,tn_7b],[tn_y,[tn_Kc,tn_rc],33,tn_8b],[tn_y,[tn_Kc,tn_Oc,tn_rc],33,tn_9b],[tn_Nc,[tn_Dc,tn_z,tn_Ec],33,tn_$b],[tn_A,[tn_Pc],33,tn_t],[tn_A,[tn_qc,tn_z,tn_rc],33,tn_ac],[tn_A,[tn_Oc],30,tn_t],[tn_A,[tn_Qc],30,tn_t],[tn_A,[tn_Rc],30,tn_t],[tn_Rc,[tn_ob,
tn_qc,tn_rc],-1,tn_bc],[tn_Rc,[tn_ob,tn_qc,tn_z,tn_Sc,tn_vb,tn_rc],-1,tn_cc],[tn_Sc,[tn_uc,tn_z],-1,tn_dc],[tn_Tc,[tn_B],20,tn_t],[tn_Tc,[tn_Tc,tn_nc,tn_B],20,tn_ec],[tn_B,[tn_Lc],20,tn_t],[tn_B,[tn_Uc],19,tn_t],[tn_B,[tn_Uc,tn_l,tn_w],20,tn_fc],[tn_B,[tn_Uc,tn_lb,tn_w],20,tn_gc],[tn_Uc,[tn_A,tn_Nc,tn_vb],20,tn_hc],[tn_z,[tn_A],16,tn_t],[tn_z,[tn_Tc],16,tn_t],[tn_z,[tn_Cc,tn_z],-1,tn_ic],[tn_z,[tn_z,tn_jb,tn_z],-1,tn_v],[tn_z,[tn_z,tn_ib,tn_z],-1,tn_v],[tn_z,[tn_z,tn_vc,tn_z],-1,tn_v],[tn_z,[tn_z,
tn_wc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_Ac,tn_z],-1,tn_v],[tn_z,[tn_z,tn_zc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_yc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_xc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_Bc,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_Cc,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_Gc,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_gb,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_hb,tn_z],-1,tn_v,tn_],[tn_Oc,[tn_Hc],-1,tn_jc],[tn_Oc,[tn_Ic],-1,tn_jc],[tn_Qc,[tn_Jc],-1,tn_kc],[tn_Pc,[tn_nb,tn_ob],200,tn_lc]],tn_sb=[];
function tn_bb(){if(tn_sb.length)return;tn_Xc.sort(function(i,k){var j=i[1].length,g=k[1].length;return j<g?1:j>g?-1:0});var a=1;for(var b=0;b<tn_Wc.length;++b)tn_Wc[b].key=a++;for(b=0;b<tn_fb.length;++b)tn_fb[b].key=a++;function c(i,k,j){i[k]||(i[k]=[]);i[k].push(j)}for(b=0;b<tn_Xc.length;++b){var d=tn_Xc[b],e=d[1];for(var f=e.length-1;f>=0;--f)if(e[f]==tn_xb){c(tn_sb,e[f-1].key,d);break}else if(e[f]==tn_vb||e[f]==tn_wb){c(tn_sb,e[f-1].key,d);--f}else{c(tn_sb,e[f].key,d);break}}var h=0;tn_Pa(tn_sb,
function(i){if(i)h+=i.length})}function tn_zb(a,b){for(var c=b.firstChild;c;c=c.nextSibling){a.push(c);arguments.callee(a,c)}}function tn_Ab(a,b){for(var c=b.lastChild;c;c=c.previousSibling){a.push(c);arguments.callee(a,c)}}
function tn_ab(a,b){if(b.length==0)return;var c=[];for(var d=0;d<a.u();++d){var e=a.nodelist[d],f={node:e,key:[]},h=a.clone(e,0,[e]);for(var i=0;i<b.length;++i){var k=b[i],j=k.expr.evaluate(h),g;if(k.type=="text")g=j.a();else if(k.type=="number")g=j.b();f.key.push({value:g,order:k.order})}f.key.push({value:d,order:"ascending"});c.push(f)}c.sort(tn_Yc);var l=[];for(var d=0;d<c.length;++d)l.push(c[d].node);a.nodelist=l;a.nb(0)}
function tn_Yc(a,b){for(var c=0;c<a.key.length;++c){var d=a.key[c].order=="descending"?-1:1;if(a.key[c].value>b.key[c].value)return+1*d;else if(a.key[c].value<b.key[c].value)return-1*d}return 0}function tn_C(a,b){var c=tn_$a(a),d=c.evaluate(b);return d};function tn_Zc(a,b){var c=(new tn_i).createDocumentFragment();tn__c(new tn_k(a,b),b,c);var d=tn_Ta(c);return d}
function tn__c(a,b,c){var d=c.nodeType==9?c:c.ownerDocument,e=b.nodeName.split(/:/);if(e.length==1||e[0]!="xsl")tn_0c(a,b,c,d);else switch(e[1]){case "apply-imports":alert("not implemented: "+e[1]);break;case "apply-templates":var f=tn_D(b,"select"),h;h=f?tn_C(f,a).c():a.node.childNodes;var i=a.clone(h[0],0,h);tn_1c(i,b);tn_2c(i,b);var k=tn_D(b,"mode"),j=b.ownerDocument.documentElement,g=[];for(var l=0;l<j.childNodes.length;++l){var o=j.childNodes[l];o.nodeType==1&&o.nodeName=="xsl:template"&&o.getAttribute("mode")==
k&&g.push(o)}for(var q=0;q<i.u();++q){var s=i.nodelist[q];for(var l=0;l<g.length;++l)tn__c(i.clone(s,q),g[l],c)}break;case "attribute":var r=tn_D(b,"name"),m=tn_3c(r,a),n=d.createDocumentFragment();tn_E(a,b,n);var y=tn_h(n);c.setAttribute(m,y);break;case "attribute-set":alert("not implemented: "+e[1]);break;case "call-template":var m=tn_D(b,"name"),j=b.ownerDocument.documentElement,v=a.clone();tn_1c(v,b);for(var l=0;l<j.childNodes.length;++l){var o=j.childNodes[l];if(o.nodeType==1&&o.nodeName=="xsl:template"&&
o.getAttribute("name")==m){tn_E(v,o,c);break}}break;case "choose":tn_4c(a,b,c);break;case "comment":var n=d.createDocumentFragment();tn_E(a,b,n);var p=tn_h(n),D=d.createComment(p);c.appendChild(D);break;case "copy":var n=tn_5c(c,a.node,d);n&&tn_E(a,b,n);break;case "copy-of":var f=tn_D(b,"select"),y=tn_C(f,a);if(y.type=="node-set"){var h=y.c();for(var l=0;l<h.length;++l)tn_6c(c,h[l],d)}else{var n=d.createTextNode(y.a());c.appendChild(n)}break;case "decimal-format":alert("not implemented: "+e[1]);break;
case "element":var r=tn_D(b,"name"),m=tn_3c(r,a),n=d.createElement(m);c.appendChild(n);tn_E(a,b,n);break;case "fallback":alert("not implemented: "+e[1]);break;case "for-each":tn_7c(a,b,c);break;case "if":var E=tn_D(b,"test"),u=tn_C(E,a);u!=tn_b&&u.d()&&tn_E(a,b,c);break;case "import":alert("not implemented: "+e[1]);break;case "include":alert("not implemented: "+e[1]);break;case "key":alert("not implemented: "+e[1]);break;case "message":alert("not implemented: "+e[1]);break;case "namespace-alias":alert("not implemented: "+
e[1]);break;case "number":alert("not implemented: "+e[1]);break;case "otherwise":alert("error if here: "+e[1]);break;case "output":break;case "preserve-space":break;case "processing-instruction":alert("not implemented: "+e[1]);break;case "sort":break;case "strip-space":alert("not implemented: "+e[1]);break;case "stylesheet":case "transform":tn_E(a,b,c);break;case "template":var z=tn_D(b,"match");z&&tn_8c(z,a)&&tn_E(a,b,c);break;case "text":var t=tn_h(b),n=d.createTextNode(t);c.appendChild(n);break;
case "value-of":var f=tn_D(b,"select"),y=tn_C(f,a).a(),n=d.createTextNode(y);c.appendChild(n);break;case "param":tn_9c(a,b,tn_a);break;case "variable":tn_9c(a,b,tn_);break;case "when":alert("error if here: "+e[1]);break;case "with-param":alert("error if here: "+e[1]);break;default:alert("error if here: "+e[1]);break}}function tn_1c(a,b){for(var c=0;c<b.childNodes.length;++c){var d=b.childNodes[c];d.nodeType==1&&d.nodeName=="xsl:with-param"&&tn_9c(a,d,tn_)}}
function tn_2c(a,b){var c=[];for(var d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(e.nodeType==1&&e.nodeName=="xsl:sort"){var f=tn_D(e,"select"),h=tn_$a(f),i=tn_D(e,"data-type")||"text",k=tn_D(e,"order")||"ascending";c.push({expr:h,type:i,order:k})}}tn_ab(a,c)}function tn_9c(a,b,c){var d=tn_D(b,"name"),e=tn_D(b,"select"),f;if(b.childNodes.length>0){var h=b.ownerDocument.createDocumentFragment();tn_E(a,b,h);f=new tn_p([h])}else f=e?tn_C(e,a):new tn_m("");if(c||!a.O(d))a.ya(d,f)}
function tn_4c(a,b,c){for(var d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(e.nodeType!=1)continue;else if(e.nodeName=="xsl:when"){var f=tn_D(e,"test");if(tn_C(f,a).d()){tn_E(a,e,c);break}}else if(e.nodeName=="xsl:otherwise"){tn_E(a,e,c);break}}}function tn_7c(a,b,c){var d=tn_D(b,"select"),e=tn_C(d,a).c(),f=a.clone(e[0],0,e);tn_2c(f,b);for(var h=0;h<f.u();++h){var i=f.nodelist[h];tn_E(f.clone(i,h),b,c)}}
function tn_E(a,b,c){var d=a.clone();for(var e=0;e<b.childNodes.length;++e)tn__c(d,b.childNodes[e],c)}function tn_0c(a,b,c,d){if(b.nodeType==3){if(tn_$c(b)){var e=d.createTextNode(b.nodeValue);c.appendChild(e)}}else if(b.nodeType==1){var e=d.createElement(b.nodeName);for(var f=0;f<b.attributes.length;++f){var h=b.attributes[f];if(h){var i=h.nodeName,k=tn_3c(h.nodeValue,a);e.setAttribute(i,k)}}c.appendChild(e);tn_E(a,b,e)}else tn_E(a,b,c)}
function tn_$c(a){if(!a.nodeValue.match(/^\s*$/))return tn_;var b=a.parentNode;if(b.nodeName=="xsl:text")return tn_;while(b&&b.nodeType==1){var c=b.getAttribute("xml:space");if(c)if(c=="default")return tn_a;else if(c=="preserve")return tn_;b=b.parentNode}return tn_a}function tn_3c(a,b){var c=tn_La(a,"{");if(c.length==1)return a;var d="";for(var e=0;e<c.length;++e){var f=tn_La(c[e],"}");if(f.length!=2){d+=c[e];continue}var h=tn_C(f[0],b).a();d+=h+f[1]}return d}
function tn_D(a,b){var c=a.getAttribute(b);return c?tn_Xa(c):c}function tn_6c(a,b,c){if(b.nodeType==11||b.nodeType==9)for(var d=0;d<b.childNodes.length;++d)arguments.callee(a,b.childNodes[d],c);else{var e=tn_5c(a,b,c);if(e){for(var d=0;d<b.attributes.length;++d)arguments.callee(e,b.attributes[d],c);for(var d=0;d<b.childNodes.length;++d)arguments.callee(e,b.childNodes[d],c)}}}
function tn_5c(a,b,c){if(b.nodeType==1){var d=c.createElement(b.nodeName);a.appendChild(d);return d}if(b.nodeType==3){var d=c.createTextNode(b.nodeValue);a.appendChild(d)}else if(b.nodeType==4){var d=c.createCDATASection(b.nodeValue);a.appendChild(d)}else if(b.nodeType==8){var d=c.createComment(b.nodeValue);a.appendChild(d)}else b.nodeType==2&&a.setAttribute(b.nodeName,b.nodeValue);return tn_b}
function tn_8c(a,b){var c=tn_$a(a),d;if(c.steps&&!c.absolute&&c.steps.length==1&&c.steps[0].axis=="child"&&c.steps[0].predicate.length==0)d=c.steps[0].nodetest.evaluate(b).d();else{d=tn_a;var e=b.node;while(!d&&e){var f=c.evaluate(b.clone(e,0,[e])).c();for(var h=0;h<f.length;++h)if(f[h]==b.node){d=tn_;break}e=e.parentNode}}return d};function tn_ad(a,b){window[a]=b}tn_ad("nxslProcess",tn_3a);tn_ad("xmlParse",tn_1a);tn_ad("xsltProcess",tn_Zc);tn_ad("xmlText",tn_Ta);tn_ad("xmlImportNode",tn_Ma);var tn_bd="http://www.google.com/images/infowindow/",tn_cd=tn_bd+"transparent.png",tn_dd=Number.MAX_VALUE;var tn_ed="windo";function tn_F(a,b,c,d,e){var f=((b?b.ownerDocument:tn_b)||document).createElement(a);c&&tn_G(f,c);d&&tn_fd(f,d);if(b&&!e){tn_H(b,f);if(b[tn_ed])f[tn_ed]=b[tn_ed]}return f}function tn_gd(a,b){var c=((b?b.ownerDocument:tn_b)||document).createTextNode(a);b&&tn_H(b,c);return c}function tn_I(a){return tn_J(a)+"px"}function tn_G(a,b){var c=a.style;c.position="absolute";c.left=tn_I(b.x);c.top=tn_I(b.y)}function tn_fd(a,b){var c=a.style;c.width=tn_I(b.width);c.height=tn_I(b.height)}
function tn_K(a,b){a.style.width=tn_I(b)}function tn_L(a,b){a.style.height=tn_I(b)}function tn_M(a){a.style.display="none"}function tn_N(a){a.style.display=""}function tn_hd(a){a.style.visibility="hidden"}function tn_id(a){a.style.visibility=""}function tn_jd(a){a.style.position="absolute"}function tn_kd(a){tn_ld(a,"hidden")}function tn_ld(a,b){a.style.overflow=b}var tn_O=Math.min,tn_P=Math.max,tn_J=Math.round,tn_md=Math.abs;
function tn_Q(a,b){try{a.style.cursor=b}catch(c){b=="pointer"&&tn_Q(a,"hand")}}function tn_nd(a){tn_od(a,"gmnoscreen");tn_pd(a,"gmnoprint")}function tn_qd(a,b,c){return window.setTimeout(function(){b.apply(a)},c)}function tn_rd(a){var b=a.target||a.srcElement;if(b.nodeType==3)b=b.parentNode;return b}function tn_H(a,b){a.appendChild(b)}function tn_R(a){if(a.parentNode){a.parentNode.removeChild(a);tn_sd(a)}}function tn_td(a){var b;while(b=a.firstChild){tn_sd(b);a.removeChild(b)}}
function tn_ud(a,b){if(a.innerHTML!=b){tn_td(a);a.innerHTML=b}}function tn_vd(a){if(tn_S.k())a.style.MozUserSelect="none";else{a.unselectable="on";a.onselectstart=tn_wd}}function tn_xd(a,b){var c=a.length;for(var d=0;d<c;++d)b(a[d],d)}function tn_yd(a,b,c){for(var d in a)if(c||!a.hasOwnProperty||a.hasOwnProperty(d))b(d,a[d])}function tn_zd(a,b,c,d){var e=c||0,f=d||b.length;for(var h=e;h<f;++h)a.push(b[h])}function tn_wd(){return tn_a}
function tn_Ad(a,b){if(tn_S.type==1)a.style.filter="alpha(opacity="+tn_J(b*100)+")";else a.style.opacity=b}function tn_Bd(a,b,c){var d=tn_F("div",a,b,c);d.style.backgroundColor="black";tn_Ad(d,0.35);return d}function tn_T(a,b){var c=(a?a.ownerDocument:tn_b)||document;if(a.currentStyle){var d=tn_Cd(b);return a.currentStyle[d]}else if(c.defaultView&&c.defaultView.getComputedStyle){var e=c.defaultView.getComputedStyle(a,"");return e?e.getPropertyValue(b):""}else{var d=tn_Cd(b);return a.style[d]}}
var tn_Dd="__mapsBaseCssDummy__";function tn_Ed(a,b,c){var d=c?c:tn_T(a,b);if(typeof d=="number")return d;else if(isNaN(parseInt(d,10)))return d;else if(d.length>2&&d.substring(d.length-2)=="px")return parseInt(d,10);else{var e=a.ownerDocument.getElementById(tn_Dd);if(e)a.parentNode.appendChild(e);else{var e=tn_F("div",a,new tn_c(0,0),new tn_U(0,0));e.id=tn_Dd;tn_hd(e)}e.style.width="0px";e.style.width=d;return e.offsetWidth}}var tn_Fd="border-left-width",tn_Gd="border-top-width";
function tn_Hd(a){return new tn_U(tn_Id(a,tn_Fd),tn_Id(a,tn_Gd))}function tn_Id(a,b){var c=tn_T(a,b);if(isNaN(parseInt(c,10)))return 0;return tn_Ed(a,b,c)}function tn_Cd(a){return a.replace(/-(\w)/g,function(b,c){return(""+c).toUpperCase()})}function tn_Jd(a){a.length=0}function tn_Kd(a){var b=tn_a;if(a&&typeof a=="object")b=typeof Window=="function"?a instanceof Window:typeof a.navigator=="object"&&typeof a.history=="object"&&typeof a.document=="object";return b}
function tn_Ld(a){var b;b=tn_Kd(a)?a:a&&a[tn_ed]?a[tn_ed]:window;return b}function tn_Md(a,b){var c=tn_Ld(b);a[tn_ed]=c;return c};function tn_Nd(a,b,c){tn_Od([a],function(d){b(d[0])},c)}
function tn_Od(a,b,c){var d=c||screen.width,e=tn_F("div",window.document.body,new tn_c(-screen.width,-screen.height),new tn_U(d,screen.height)),f=[];for(var h=0;h<a.length;h++){var i=tn_F("div",e,tn_c.ORIGIN);tn_H(i,a[h]);f.push(i)}window.setTimeout(function(){var k=[],j=new tn_U(0,0);for(var g=0;g<f.length;g++){var l=f[g],o=new tn_U(l.offsetWidth,l.offsetHeight);k.push(o);l.removeChild(a[g]);tn_R(l);j.width=tn_P(j.width,o.width);j.height=tn_P(j.height,o.height)}tn_R(e);f=tn_b;b(k,j)},0)};function tn_Pd(a,b,c,d,e,f,h){var i;if(e&&tn_S.type==1){i=tn_F("div",b,c,d);i.style.overflow="hidden";if(d&&f)i.sizingMethod="scale";var k=tn_F("img",i);tn_hd(k);tn_V(k,tn_Qd,tn_Rd)}else{i=tn_F("img",b,c,d);h&&tn_V(i,tn_Qd,tn_Sd)}if(h)i.hideAndTrackLoading=tn_;tn_vd(i);if(tn_S.type==1)i.galleryImg="no";i.style.border=tn_I(0);i.style.padding=tn_I(0);i.style.margin=tn_I(0);i.oncontextmenu=tn_Td;tn_Ud(i,a);return i}
function tn_Rd(){var a=this.parentNode;a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod="+(a.sizingMethod?a.sizingMethod:"crop")+',src="'+this.src+'")';if(a.hideAndTrackLoading)a.loaded=tn_}function tn_Ud(a,b){if(a.tagName=="DIV"){a.firstChild.src=b;a.src=b;if(a.hideAndTrackLoading){a.style.filter="";a.loaded=tn_a}}else if(a.hideAndTrackLoading&&b!=tn_cd){if(b!=tn_cd){a.loaded=tn_a;a.pendingSrc=b}else a.pendingSrc=tn_b;a.src=tn_cd}else a.src=b}
function tn_Sd(){var a=this;if(a.src==tn_cd&&a.pendingSrc){a.src=a.pendingSrc;a.pendingSrc=tn_b}else a.loaded=tn_}function tn_Vd(a,b){return tn_bd+a+(b?".gif":".png")};var tn_W="click",tn_Wd="contextmenu",tn_Xd="dblclick",tn_Qd="load",tn_Yd="mousedown",tn_Zd="mousemove",tn__d="mouseout",tn_0d="mouseup",tn_1d="mousewheel",tn_2d="DOMMouseScroll",tn_3d="unload",tn_4d="closeclick",tn_5d="maximizeclick",tn_6d="restoreclick",tn_7d="maximizeend",tn_8d="restoreend",tn_9d="dragstart",tn_$d="drag",tn_ae="dragend",tn_be="move",tn_ce="clearlisteners",tn_de="logclick";var tn_ee=tn_a;function tn_X(){this.f=[]}function tn_fe(){}tn_X.instance=function(a){a||(a=window);if(!a.gEventListenerPool)a.gEventListenerPool=new tn_X;return a.gEventListenerPool};tn_X.remove=function(a){tn_X.instance(tn_Ld(a)).hb(a)};tn_X.prototype.hb=function(a){var b=this.f.pop(),c=a.Ma();if(c<this.f.length){this.f[c]=b;b.K(c)}a.K(-1)};tn_X.push=function(a){tn_X.instance(tn_Ld(a)).eb(a)};tn_X.prototype.eb=function(a){this.f.push(a);a.K(this.f.length-1)};
tn_X.prototype.clear=function(){for(var a=0;a<this.f.length;++a)this.f[a].K(-1);this.f=[]};function tn_ge(a,b,c){var d=new tn_Y(a,b,c,0);tn_X.push(d);return d}function tn_he(a){a.remove();tn_X.remove(a)}function tn_ie(a){tn_Z(a,tn_ce);tn_xd(tn_je(a),function(b){b.remove();tn_X.remove(b)})}function tn_je(a,b){var c=[],d=a.__e_;if(d)if(b)d[b]&&tn_zd(c,d[b]);else tn_yd(d,function(e,f){tn_zd(c,f)});return c}
function tn_ke(a,b,c){var d=tn_b,e=a.__e_;if(e){d=e[b];if(!d){d=[];if(c)e[b]=d}}else{d=[];if(c){a.__e_={};a.__e_[b]=d}}return d}function tn_Z(a,b){var c=[];tn_zd(c,arguments,2);tn_xd(tn_je(a,b),function(d){if(tn_ee)d.apply(a,c);else try{d.apply(a,c)}catch(e){}})}
function tn_V(a,b,c){var d;if(tn_S.type==2&&b==tn_Xd){a["on"+b]=c;d=new tn_Y(a,b,c,3)}else if(a.addEventListener){a.addEventListener(b,c,tn_a);d=new tn_Y(a,b,c,1)}else if(a.attachEvent){var e=tn_le(a,c);a.attachEvent("on"+b,e);d=new tn_Y(a,b,e,2)}else{a["on"+b]=c;d=new tn_Y(a,b,c,3)}var f=tn_Ld(a);if(a!=f||b!=tn_3d)tn_X.push(d);return d}function tn__(a,b,c,d){var e=tn_me(c,d);return tn_V(a,b,e)}function tn_ne(a,b,c){tn__(a,tn_W,b,c);tn_S.type==1&&tn__(a,tn_Xd,b,c)}
function tn_me(a,b){return function(c){if(!c)c=window.event;if(c&&!c.target)c.target=c.srcElement;b.call(a,c,this)}}function tn_le(a,b){return function(){return b.apply(a,arguments)}}function tn_Y(a,b,c,d){tn_f(a);tn_f(typeof c=="function");var e=this;e.p=a;e.N=b;e.Q=c;e.Fb=d;e.Ra=-1;tn_Md(e,a);tn_ke(a,b,tn_).push(e)}
tn_Y.prototype.remove=function(){var a=this;switch(a.Fb){case 1:a.p.removeEventListener(a.N,a.Q,tn_a);break;case 2:a.p.detachEvent("on"+a.N,a.Q);break;case 3:a.p["on"+a.N]=tn_b;break}tn_Oa(tn_ke(a.p,a.N),a);a.p=tn_b;a.Q=tn_b;a.remove=tn_fe;a.apply=tn_fe};tn_Y.prototype.Ma=function(){return this.Ra};tn_Y.prototype.K=function(a){this.Ra=a};tn_Y.prototype.apply=function(a,b){return this.Q.apply(a,b)};function tn_sd(a){tn_2a(a,tn_ie)}
function tn_oe(a){a.type==tn_W&&tn_Z(document,tn_de,a);if(tn_S.type==1){window.event.cancelBubble=tn_;window.event.returnValue=tn_a}else{a.preventDefault();a.stopPropagation()}}function tn_pe(a){a.type==tn_W&&tn_Z(document,tn_de,a);if(tn_S.type==1)window.event.cancelBubble=tn_;else a.stopPropagation()}function tn_Td(a){if(tn_S.type==1)window.event.returnValue=tn_a;else a.preventDefault()};var tn_S,tn_qe=["opera","msie","safari","firefox","mozilla"],tn_re=["x11;","macintosh","windows"];
function tn_se(a){this.type=-1;this.os=-1;this.version=0;this.revision=0;var a=a.toLowerCase();for(var b=0;b<tn_qe.length;b++){var c=tn_qe[b];if(a.indexOf(c)!=-1){this.type=b;var d=new RegExp(c+"[ /]?([0-9]+(.[0-9]+)?)");if(d.exec(a)!=tn_b)this.version=parseFloat(RegExp.$1);break}}for(var b=0;b<tn_re.length;b++){var c=tn_re[b];if(a.indexOf(c)!=-1){this.os=b;break}}if(this.type==4||this.type==3)if(/\brv:\s*(\d+\.\d+)/.exec(a))this.revision=parseFloat(RegExp.$1)}
tn_se.prototype.k=function(){return this.type==3||this.type==4};tn_S=new tn_se(navigator.userAgent);tn_c.ORIGIN=new tn_c(0,0);tn_c.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function tn_U(a,b){this.width=a;this.height=b}tn_U.ZERO=new tn_U(0,0);tn_U.prototype.toString=function(){return"("+this.width+", "+this.height+")"};function tn_te(a){this.minX=this.minY=tn_dd;this.maxX=this.maxY=-tn_dd;var b=arguments;if(a&&a.length)for(var c=0;c<a.length;c++)this.extend(a[c]);else if(b.length>=4){this.minX=b[0];this.minY=b[1];this.maxX=b[2];this.maxY=b[3]}}
tn_te.prototype.min=function(){return new tn_c(this.minX,this.minY)};tn_te.prototype.max=function(){return new tn_c(this.maxX,this.maxY)};tn_te.prototype.toString=function(){return"("+this.min()+", "+this.max()+")"};tn_te.prototype.extend=function(a){var b=this;b.minX=tn_O(b.minX,a.x);b.maxX=tn_P(b.maxX,a.x);b.minY=tn_O(b.minY,a.y);b.maxY=tn_P(b.maxY,a.y)};
tn_te.intersection=function(a,b){return new tn_te([new tn_c(tn_P(a.minX,b.minX),tn_P(a.minY,b.minY)),new tn_c(tn_O(a.maxX,b.maxX),tn_O(a.maxY,b.maxY))])};function tn_pd(a,b){var c=a.className?""+a.className:"";if(c){var d=c.split(/\s+/),e=tn_a;for(var f=0;f<d.length;++f)if(d[f]==b){e=tn_;break}e||d.push(b);a.className=d.join(" ")}else a.className=b}function tn_od(a,b){var c=a.className?""+a.className:"";if(!c||c.indexOf(b)==-1)return;var d=c.split(/\s+/);for(var e=0;e<d.length;++e)d[e]==b&&d.splice(e--,1);a.className=d.join(" ")};tn_ia=function(){};function tn_ue(){}tn_ue.monitor=function(){};tn_ue.monitorAll=function(){};tn_ue.dump=function(){};function tn_0(){var a=tn_F("div",document.body),b=a.style;b.position="absolute";b.left=tn_I(7);b.bottom=tn_I(4);b.zIndex=10000;var c=tn_Bd(a,new tn_c(2,2)),d=tn_F("div",a);b=d.style;b.position="relative";b.zIndex=1;b.fontFamily="Verdana,Arial,sans-serif";b.fontSize="small";b.border="1px solid black";var e=[["Clear",this.clear],["Close",this.close]],f=tn_F("div",d);b=f.style;b.position="relative";b.zIndex=2;b.backgroundColor="#979797";b.color="white";b.fontSize="85%";b.padding=tn_I(2);tn_Q(f,"default");
tn_vd(f);tn_gd("Log",f);for(var h=0;h<e.length;h++){var i=e[h];tn_gd(" - ",f);var k=tn_F("span",f);k.style.textDecoration="underline";tn_gd(i[0],k);tn_ne(k,this,i[1]);tn_Q(k,"pointer")}tn__(f,tn_Yd,this,this.Ha);var j=tn_F("div",d);b=j.style;b.backgroundColor="white";b.width="80em";b.height="10em";b.overflow=tn_S.k()?"-moz-scrollbars-vertical":"auto";tn_V(j,tn_Yd,tn_pe);this.S=j;this.o=a;this.j=c}tn_0.instance=function(){var a=tn_0.p;if(!a){a=new tn_0;tn_0.p=a}return a};
tn_0.prototype.write=function(a,b){var c=this.Ia();if(b){c=tn_F("span",c);c.style.color=b}tn_gd(a,c);this.ib()};tn_0.prototype.clear=function(){this.S.innerHTML=""};tn_0.prototype.close=function(){tn_R(this.o)};tn_0.prototype.Ha=function(){if(!this.ub){this.ub=new tn_1(this.o);this.o.style.bottom=""}};
tn_0.prototype.Ia=function(){var a=tn_F("div",this.S),b=a.style;b.fontSize="85%";b.borderBottom="1px solid silver";b.paddingBottom=tn_I(2);var c=tn_F("div",a);c.style.color="gray";c.style.fontSize="75%";tn_gd(this.rb(),c);return a};tn_0.prototype.ib=function(){this.S.scrollTop=this.S.scrollHeight;this.pb()};tn_0.prototype.rb=function(){var a=new Date;return this.H(a.getHours(),2)+":"+this.H(a.getMinutes(),2)+":"+this.H(a.getSeconds(),2)+":"+this.H(a.getMilliseconds(),3)};
tn_0.prototype.H=function(a,b){var c=a.toString();while(c.length<b)c="0"+c;return c};tn_0.prototype.pb=function(){tn_fd(this.j,new tn_U(this.o.offsetWidth,this.o.offsetHeight))};function tn_1(a,b){tn_1.wb||tn_1.vb();var c=tn_Md(this,a);b=b||{};this.F=b.draggableCursor||tn_1.F;this.z=b.draggingCursor||tn_1.z;this.r=a;this.o=b.container;this.cb=b.left;this.db=b.top;this.M=tn_a;this.v=new tn_c(0,0);this.G=tn_a;this.L=new tn_c(0,0);this.Ab=tn_me(this,this.ab);this.Bb=tn_me(this,this.qa);this.Db=tn_me(this,this.ra);tn_S.k()&&tn__(c,tn__d,this,this.bb);this.f=[];this.fb(a)}
tn_1.vb=function(){var a,b;if(tn_S.k()){a="-moz-grab";b="-moz-grabbing"}else{a="url("+tn_bd+"openhand.cur), default";b="url("+tn_bd+"closedhand.cur), move"}this.F=this.F||a;this.z=this.z||b;this.wb=tn_};tn_1.getDraggingCursor=function(){return tn_1.z};tn_1.va=function(a){this.F=a};tn_1.wa=function(a){this.z=a};tn_1.prototype.va=tn_1.va;tn_1.prototype.wa=tn_1.wa;
tn_1.prototype.fb=function(a){for(var b=0;b<this.f.length;++b)tn_he(this.f[b]);this.sa&&tn_Q(this.r,this.sa);this.r=a;this.ha=tn_b;this.f=[];if(!a)return;tn_jd(a);this.moveTo(typeof this.cb=="number"?this.cb:a.offsetLeft,typeof this.db=="number"?this.db:a.offsetTop);this.ha=a.setCapture?a:tn_Ld(a);this.f.push(tn_V(a,tn_Yd,this.Ab));this.f.push(tn__(a,tn_0d,this,this.Za));this.f.push(tn__(a,tn_W,this,this.Ya));this.f.push(tn__(a,tn_Xd,this,this.$a));this.sa=a.style.cursor;this.ba()};
tn_1.prototype.moveTo=function(a,b){a=tn_J(a);b=tn_J(b);if(this.left!=a||this.top!=b){this.left=a;this.top=b;var c=this.r.style;c.left=tn_I(a);c.top=tn_I(b);tn_Z(this,tn_be)}};tn_1.prototype.$a=function(a){tn_Z(this,tn_Xd,a)};tn_1.prototype.Ya=function(a){this.M&&!a.cancelDrag&&tn_Z(this,tn_W,a)};tn_1.prototype.Za=function(a){this.M&&tn_Z(this,tn_0d,a)};tn_1.prototype.ab=function(a){tn_Z(this,tn_Yd,a);if(a.cancelDrag)return;if(!this.Ta(a))return;this.kb(a);this.Fa(a);tn_oe(a)};
tn_1.prototype.qa=function(a){if(!this.G)return;if(tn_S.os==0){if(a==tn_b)return;if(this.dragDisabled){this.savedMove={};this.savedMove.clientX=a.clientX;this.savedMove.clientY=a.clientY;return}tn_qd(this,function(){this.dragDisabled=tn_a;this.qa(this.savedMove)},30);this.dragDisabled=tn_;this.savedMove=tn_b}var b=this.left+(a.clientX-this.v.x),c=this.top+(a.clientY-this.v.y),d=0,e=0,f=this.o;if(f){var h=this.r,i=tn_P(0,tn_O(b,f.offsetWidth-h.offsetWidth));d=i-b;b=i;var k=tn_P(0,tn_O(c,f.offsetHeight-
h.offsetHeight));e=k-c;c=k}this.moveTo(b,c);this.v.x=a.clientX+d;this.v.y=a.clientY+e;tn_Z(this,tn_$d,a)};tn_1.prototype.ra=function(a){this.gb();this.Ka(a);var b=(new Date).getTime();b-this.tb<=500&&tn_md(this.L.x-a.clientX)<=2&&tn_md(this.L.y-a.clientY)<=2&&tn_Z(this,tn_W,a)};tn_1.prototype.bb=function(a){!a.relatedTarget&&this.G&&this.ra(a)};tn_1.prototype.ba=function(){var a;a=this.G?this.z:this.M?this.sa:this.F;tn_Q(this.r,a)};
tn_1.prototype.Ta=function(a){var b=a.button==0||a.button==1;if(this.M||!b){tn_oe(a);return tn_a}return tn_};tn_1.prototype.kb=function(a){this.v.x=a.clientX;this.v.y=a.clientY;this.r.setCapture&&this.r.setCapture();this.tb=(new Date).getTime();this.L.x=a.clientX;this.L.y=a.clientY};tn_1.prototype.gb=function(){document.releaseCapture&&document.releaseCapture()};tn_1.prototype.Fa=function(a){this.G=tn_;this.Cb=tn_V(this.ha,tn_Zd,this.Bb);this.Eb=tn_V(this.ha,tn_0d,this.Db);tn_Z(this,tn_9d,a);this.ba()};
tn_1.prototype.Ka=function(a){this.G=tn_a;tn_he(this.Cb);tn_he(this.Eb);tn_Z(this,tn_0d,a);tn_Z(this,tn_ae,a);this.ba()};var tn_ve="overflow",tn_we="position",tn_xe="visible",tn_ye="static",tn_ze="BODY";
function tn_Ae(a,b){var c=new tn_c(0,0);while(a&&a!=b){a.nodeName==tn_ze&&tn_Be(c,a);var d=tn_Hd(a);c.x+=d.width;c.y+=d.height;if(a.nodeName!=tn_ze||!tn_S.k()){c.x+=a.offsetLeft;c.y+=a.offsetTop}if(tn_S.k()&&tn_S.revision>=1.8&&a.offsetParent&&a.offsetParent.nodeName!=tn_ze&&tn_T(a.offsetParent,tn_ve)!=tn_xe){var d=tn_Hd(a.offsetParent);c.x+=d.width;c.y+=d.height}if(a.offsetParent){c.x-=a.offsetParent.scrollLeft;c.y-=a.offsetParent.scrollTop}if(tn_S.type!=1&&tn_Ce(a)){if(tn_S.k()){c.x-=self.pageXOffset;
c.y-=self.pageYOffset;var e=tn_Hd(a.offsetParent.parentNode);c.x+=e.width;c.y+=e.height}break}if(tn_S.type==2&&a.offsetParent){var d=tn_Hd(a.offsetParent);c.x-=d.width;c.y-=d.height}a=a.offsetParent}if(tn_S.type==1&&!b&&document.documentElement){c.x+=document.documentElement.clientLeft;c.y+=document.documentElement.clientTop}if(b&&a==tn_b){var f=tn_Ae(b);return new tn_c(c.x-f.x,c.y-f.y)}else return c}
function tn_Ce(a){if(a.offsetParent&&a.offsetParent.nodeName==tn_ze&&tn_T(a.offsetParent,tn_we)==tn_ye)if(tn_S.type==0&&tn_T(a,tn_we)!=tn_ye)return tn_;else if(tn_S.type!=0&&tn_T(a,tn_we)=="absolute")return tn_;return tn_a}
function tn_Be(a,b){var c=tn_a;if(tn_S.k()){c=tn_T(b,tn_ve)!=tn_xe&&tn_T(b.parentNode,tn_ve)!=tn_xe;var d=tn_T(b,tn_we)!=tn_ye;if(d||c){a.x+=tn_Ed(b,"margin-left");a.y+=tn_Ed(b,"margin-top");var e=tn_Hd(b.parentNode);a.x+=e.width;a.y+=e.height}if(d){a.x+=tn_Ed(b,"left");a.y+=tn_Ed(b,"top")}}if((tn_S.k()||tn_S.type==1)&&document.compatMode!="BackCompat"||c)if(self.pageYOffset){a.x-=self.pageXOffset;a.y-=self.pageYOffset}else{a.x-=document.documentElement.scrollLeft;a.y-=document.documentElement.scrollTop}}
function tn_De(a,b){if(typeof a.offsetX!="undefined"){var c=tn_rd(a),d=tn_Ae(c,b),e=new tn_c(a.offsetX,a.offsetY);if(tn_S.type==2){var f=tn_Hd(c);e.x-=f.width;e.y-=f.height}return new tn_c(d.x+e.x,d.y+e.y)}else if(typeof a.clientX!="undefined"){var h=tn_S.type==2?new tn_c(a.pageX-self.pageXOffset,a.pageY-self.pageYOffset):new tn_c(a.clientX,a.clientY),i=tn_Ae(b);return new tn_c(h.x-i.x,h.y-i.y)}else return tn_c.ORIGIN};function tn_Ee(a){this.ticks=a;this.tick=0}tn_Ee.prototype.reset=function(){this.tick=0};tn_Ee.prototype.next=function(){this.tick++;var a=Math.PI*(this.tick/this.ticks-0.5);return(Math.sin(a)+1)/2};tn_Ee.prototype.more=function(){return this.tick<this.ticks};tn_Ee.prototype.extend=function(){if(this.tick>this.ticks/3)this.tick=tn_J(this.ticks/3)};var tn_Fe=tn_bd+"iw_sprite.css",tn_Ge=tn_a;function tn_He(a,b,c){this.name=a;if(typeof b=="string"){var d=tn_F("div",tn_b);tn_ud(d,b);b=d}this.contentElem=b;b.style.zIndex=9500;this.onclick=c}function tn_2(){this.U=new tn_d(0,0,0,0);this.T=tn_U.ZERO;this.g=[];this.m=[];this.$=[];this.Aa=[];this.s=0;this.q=0;this.n=this.fa(tn_U.ZERO);this.i={};this.oa=tn_a;this.da=tn_a;this.ca=tn_a;this.za=new tn_c(8,8);this.na="ltr"}
tn_2.prototype.create=function(a,b){var c=this.i,d=tn_Ie(c,a,[["iw_n",628,6,0,0,"iw_n1"],["iw_n",628,6,0,0,"iw_n2"],["iw_w",6,598,0,0],["iw_e",6,598,0,0],["iw_s0",628,6,0,0,"iw_s1"],["iw_s0",628,6,0,0,"iw_s2"],["iw_c",628,598,0,0]]),e=new tn_U(6,6);tn_3(c,d,"iw_nw",e);tn_3(c,d,"iw_ne",e);tn_3(c,d,"iw_xtap",new tn_U(32,21));tn_3(c,d,"iw_xtap_l",new tn_U(32,21));tn_3(c,d,"iw_xtap_u",new tn_U(32,21));tn_3(c,d,"iw_xtap_ul",new tn_U(32,21));tn_3(c,d,"iw_xtap_rd",new tn_U(21,32));tn_3(c,d,"iw_xtap_ld",
new tn_U(21,32));tn_3(c,d,"iw_sw0",e,"iw_sw");tn_3(c,d,"iw_se0",e,"iw_se");tn_nd(d);this.e=d;var f=new tn_U(8,8),h=tn_Ie(c,b,[["iws_n",628,8,0,0,"iws_n1"],["iws_n",628,8,0,0,"iws_n2"],["iws_w",8,598,0,0],["iws_e",8,598,0,0],["iws_s",628,8,0,0,"iws_s1"],["iws_s",628,8,0,0,"iws_s2"],["iws_c",628,598,0,0]]);tn_3(c,h,"iws_nw",f);tn_3(c,h,"iws_ne",f);tn_3(c,h,"iws_sw",f);tn_3(c,h,"iws_se",f);tn_3(c,h,"iws_tap",new tn_U(37,16));tn_3(c,h,"iws_tap_l",new tn_U(32,16));tn_3(c,h,"iws_tap_u",new tn_U(37,26));
tn_3(c,h,"iws_tap_ul",new tn_U(32,26));tn_3(c,h,"iws_tap_rd",new tn_U(16,37));tn_3(c,h,"iws_tap_ld",new tn_U(26,37));tn_3(c,h,"iws_tab_dl",new tn_U(8,28));tn_3(c,h,"iws_tab_dr",new tn_U(14,28));tn_3(c,h,"iws_tab_l",new tn_U(8,28));tn_3(c,h,"iws_tab_r",new tn_U(14,28));tn_M(c.iws_tab_dl);tn_M(c.iws_tab_dr);tn_M(c.iws_tab_l);tn_M(c.iws_tab_r);tn_nd(h);this.j=h;var i=new tn_U(14,13),k=tn_3(c,d,"close",i);k.style.zIndex=10000;tn_Q(k,"pointer");tn_ne(k,this,this.Xa);var j=tn_3(c,d,"maximize",i);j.style.zIndex=
10000;tn_hd(j);tn_Q(j,"pointer");tn_ne(j,this,this.maximize);var g=tn_3(c,d,"restore",i);g.style.zIndex=10001;tn_hd(g);tn_Q(g,"pointer");tn_ne(g,this,this.restore);tn__(d,tn_Yd,this,this.ia);tn__(d,tn_Xd,this,this.La);tn__(d,tn_W,this,this.ia);tn__(d,tn_Wd,this,tn_pe);tn__(d,tn_1d,this,tn_pe);tn__(d,tn_2d,this,tn_pe);this.ob();this.hide()};tn_2.prototype.remove=function(){tn_R(this.j);tn_R(this.e)};
tn_2.prototype.Da=function(a){if(a){tn_N(this.i.maximize);tn_N(this.i.restore)}else{tn_M(this.i.maximize);tn_M(this.i.restore)}};tn_2.prototype.Z=function(a){this.i.close.style.visibility=a?"visible":"hidden"};tn_2.prototype.lb=function(a){this.na=a===tn_||a==="rtl"?"rtl":"ltr"};tn_2.prototype.Va=function(a){this.oa=a};tn_2.prototype.Wa=function(a){this.B=a};tn_2.prototype.Ca=function(a){this.da=a};
tn_2.prototype.W=function(a,b){if(!a.getClientRects)return this.X(tn_ka(a));var c=this.A(),d=this.i,e=c.width,f=c.height,h=window.innerWidth||document.body.scrollWidth,i=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,k=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_M(d.iw_xtap);tn_M(d.iw_xtap_l);tn_M(d.iw_xtap_u);tn_M(d.iw_xtap_ul);tn_M(d.iw_xtap_ld);tn_M(d.iw_xtap_rd);tn_M(d.iws_tap);tn_M(d.iws_tap_l);tn_M(d.iws_tap_u);tn_M(d.iws_tap_ul);
tn_M(d.iws_tap_ld);tn_M(d.iws_tap_rd);var j,g,l=0,o=0,q,s,r,m,n,y,v,p=a.getClientRects(),D=tn_ka(a),E=p[0].top-D.y;for(var u=0;u<p.length;++u){if(u>0&&p[u].bottom==p[u-1].bottom)if(p[u].left==p[u-1].right){p[u].left=p[u-1].left;p[u].top=tn_O(p[u].top,p[u-1].top)}else if(p[u].right==p[u-1].left){p[u].right=p[u-1].right;p[u].top=tn_O(p[u].top,p[u-1].top)}if(!m||p[u].left<=m.left)m=p[u];if(!n||p[u].right>=n.right)n=p[u];if(!y||p[u].top<=y.top)y=p[u];if(!v||p[u].bottom>=v.bottom)v=p[u]}var z=m.left-D.x,
t,w,A,B=0;if(this.ca&&21+e+6+12+n.right<h){s=tn_;j=d.iw_xtap_ld;g=d.iws_tap_ld;t=n;this.I=0}else if(this.ca&&18+e+21<m.left){r=tn_;j=d.iw_xtap_rd;g=d.iws_tap_rd;o=5;t=m;this.I=6+e+21}else{if(this.da&&21+f+6+12+(this.g.length>1?20:0)>D.y-(this.B?k:0)){j=d.iw_xtap_u;g=d.iws_tap_u;q=tn_;l=0;t=v}else{j=d.iw_xtap;g=d.iws_tap;l=0;t=y}if(tn_J((t.left+t.right)/2)+32+6+12>h){if(j==d.iw_xtap_u){j=d.iw_xtap_ul;g=d.iws_tap_ul}else{j=d.iw_xtap_l;g=d.iws_tap_l}o=5;l=32}w=tn_J((e-32)/2);if(this.oa||this.B)if(w+
6+12+l>tn_J((t.left+t.right)/2)){var C=tn_J((t.left+t.right)/2)-(this.B?0:i)-6-12-l;if(C<0){B=tn_O(-C,tn_J((t.left+t.right)/2));C=0}w=C}else if(tn_J((t.left+t.right)/2)-l+e-w+6+12>h){if(q){j=d.iw_xtap_ul;g=d.iws_tap_ul}else{j=d.iw_xtap_l;g=d.iws_tap_l}o=5;l=32;var C=tn_J((t.left+t.right)/2)-(this.B?0:i)-l+e+6+12-h;if(C>e-32){B=tn_P(e-32-C,-tn_J((t.left+t.right)/2)+(this.B?0:i));C=e-32}w=C}A=e-32-w;this.I=6+w+l}tn_N(j);tn_N(g);var H=this.T=b||tn_U.ZERO,G=this.I-B,J=s||r?6:q?0:this.ja().height+(this.g.length>
1?20:0);G-=H.width;J-=H.height;var K=new tn_c((s?t.right:r?t.left:tn_J((t.left+t.right)/2))-G-z,(s||r?tn_J((t.top+t.bottom)/2):q?t.bottom:t.top)-J-E);this.Ib=K;tn_G(this.e,K);tn_G(this.j,K);this.U=undefined;this.pa=a;return this.ta(s,r,q,w,A,j,g,o)};
tn_2.prototype.X=function(a,b){var c=this.A(),d=this.i,e=c.width,f=c.height,h=document.body.scrollWidth,i=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,k=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_M(d.iw_xtap);tn_M(d.iw_xtap_l);tn_M(d.iw_xtap_u);tn_M(d.iw_xtap_ul);tn_M(d.iw_xtap_ld);tn_M(d.iw_xtap_rd);tn_M(d.iws_tap);tn_M(d.iws_tap_l);tn_M(d.iws_tap_u);tn_M(d.iws_tap_ul);tn_M(d.iws_tap_ld);tn_M(d.iws_tap_rd);var j,g,l=0,o=0,q,s,r,
m,n,y=0,v=this.ca;if(v&&21+e+6+12+a.x+a.w<i+h){s=tn_;j=d.iw_xtap_ld;g=d.iws_tap_ld}else if(v&&18+e+21+i<a.x){r=tn_;j=d.iw_xtap_rd;g=d.iws_tap_rd;o=5}else{if(this.da&&21+f+6+12+(this.g.length>1?20:0)+(this.B?k:0)>a.y){j=d.iw_xtap_u;g=d.iws_tap_u;l=0;q=tn_}else{j=d.iw_xtap;g=d.iws_tap;l=0}if(a.x+a.w/2+32+6+12>i+h){if(j==d.iw_xtap_u){j=d.iw_xtap_ul;g=d.iws_tap_ul}else{j=d.iw_xtap_l;g=d.iws_tap_l}o=5;l=32}m=tn_J((e-32)/2);if(this.oa)if(m+6+12+l+i>a.x+tn_J(a.w/2)){var p=a.x+tn_J(a.w/2)-6-12-l-i;if(p<0){y=
tn_O(-p,tn_J(a.w/2));p=0}m=p}else if(a.x+tn_J(a.w/2)-l+e-m+6+12>i+h){if(q){j=d.iw_xtap_ul;g=d.iws_tap_ul}else{j=d.iw_xtap_l;g=d.iws_tap_l}o=5;l=32;var p=a.x+tn_J(a.w/2)-l+e+6+12-h-i;if(p>e-32){y=tn_P(e-32-p,-tn_J(a.w/2));p=e-32}m=p}n=e-32-m}tn_N(j);tn_N(g);this.I=s?0:r?6+e+21:6+m+l;var D=this.T=b||tn_U.ZERO,E=this.I-y,u=s||r?6:q?0:this.ja().height+(this.g.length>1?20:0);E-=D.width;u-=D.height;var z=new tn_c(a.x+(s?a.w:r?0:a.w/2)-E,a.y+(s||r?a.h/2:q?a.h:0)-u);this.Ib=z;tn_G(this.e,z);tn_G(this.j,z);
this.U=a;this.pa=undefined;return this.ta(s,r,q,m,n,j,g,o)};
tn_2.prototype.ta=function(a,b,c,d,e,f,h,i){var k=!(a||b||c);this.aa=f;this.Y=h;var j=this.A(),g=this.i,l=j.width,o=j.height,q=this.g.length>1?this.s:0;if(c){tn_K(g.iw_n1,tn_P(d,0));tn_K(g.iw_n2,tn_P(e,0));tn_K(g.iw_s1,l-q);tn_K(g.iw_s2,0);tn_K(g.iws_n1,tn_P(d,0));tn_K(g.iws_n2,tn_P(e,0));tn_K(g.iws_s1,l-q);tn_K(g.iws_s2,0)}else if(k){tn_K(g.iw_n1,l-q);tn_K(g.iw_n2,0);tn_K(g.iw_s1,tn_P(d,0));tn_K(g.iw_s2,tn_P(e,0));tn_K(g.iws_n1,l-q);tn_K(g.iws_n2,0);tn_K(g.iws_s1,tn_P(d,0));tn_K(g.iws_s2,tn_P(e,
0))}else{tn_K(g.iw_n1,l);tn_K(g.iw_n2,0);tn_K(g.iw_s1,l-q);tn_K(g.iw_s2,0);tn_K(g.iws_n1,l);tn_K(g.iws_n2,0);tn_K(g.iws_s1,l-q);tn_K(g.iws_s2,0)}tn_fd(g.iw_c,j);if(a){tn_L(g.iw_w,tn_P(o-32,0));tn_L(g.iw_e,tn_P(o,32));tn_L(g.iws_w,tn_P(o-32,0));tn_L(g.iws_e,tn_P(o,32))}else if(b){tn_L(g.iw_e,tn_P(o-32,0));tn_L(g.iw_w,tn_P(o,32));tn_L(g.iws_e,tn_P(o-32,0));tn_L(g.iws_w,tn_P(o,32))}else{tn_L(g.iw_w,o);tn_L(g.iw_e,o);tn_L(g.iws_w,o);tn_L(g.iws_e,o)}var s=a?15:0,r=s+5-2,m=s+6,n=m+5,y=m+l,v=y+5,p=a?0:b?
y:m+d,D=p+i,E=p+32,u=E+5,z=c?15:!a&&!b&&this.g.length>1?20:0,t=z+5-2,w=z+6,A=w+5,B=w+(a||b?tn_P(o,32):o),C=B+5,H=c||a||b?B:0,G=H+5-(c||a||b?0:2),J=c||a||b?B+6-1:0,K=new tn_c(m,B),I=new tn_c(n,C),L=new tn_c(m,z),Z=new tn_c(n,t);tn_G(g.iw_nw,new tn_c(s,z));tn_G(g.iws_nw,new tn_c(r,t));if(k){tn_G(g.iw_n1,new tn_c(m+q,z));tn_G(g.iws_n1,new tn_c(n+q,t));tn_G(g.iw_s1,K);tn_G(g.iws_s1,I);tn_G(g.iw_s2,new tn_c(E,B));tn_G(g.iws_s2,new tn_c(u,C));tn_M(g.iws_tab_dl);tn_M(g.iws_tab_dr);tn_N(g.iws_tab_l);tn_N(g.iws_tab_r);
tn_G(g.iws_tab_l,new tn_c(r,G));tn_G(g.iws_tab_r,new tn_c(n+q-14,G))}else{tn_G(g.iw_n1,L);tn_G(g.iws_n1,Z);tn_G(g.iw_s2,K);tn_G(g.iws_s2,I);tn_G(g.iw_s1,new tn_c(m+q,B));tn_G(g.iws_s1,new tn_c(n+q,C));tn_N(g.iws_tab_dl);tn_N(g.iws_tab_dr);tn_M(g.iws_tab_l);tn_M(g.iws_tab_r);tn_G(g.iws_tab_dl,new tn_c(r,G));tn_G(g.iws_tab_dr,new tn_c(n+q-14,G))}if(c){tn_G(g.iw_n2,new tn_c(E,z));tn_G(g.iws_n2,new tn_c(u,t))}else{tn_G(g.iw_n2,L);tn_G(g.iws_n2,Z)}tn_G(g.iw_ne,new tn_c(y,z));tn_G(g.iws_ne,new tn_c(v,t));
tn_G(g.iw_w,new tn_c(s,w+(a?32:0)));tn_G(g.iws_w,new tn_c(r,A+(a?32:0)));tn_G(g.iw_c,new tn_c(m,w));tn_G(g.iws_c,new tn_c(n,A));tn_K(g.iw_c,y-m);tn_L(g.iw_c,B-w);tn_K(g.iws_c,v-n);tn_L(g.iws_c,C-A);tn_G(g.iw_e,new tn_c(y,w+(b?32:0)));tn_G(g.iws_e,new tn_c(v,A+(b?32:0)));tn_G(g.iw_sw,new tn_c(s,B));tn_G(g.iws_sw,new tn_c(r,C));tn_G(g.iw_se,new tn_c(y,B));tn_G(g.iws_se,new tn_c(v,C));if(a){tn_G(f,new tn_c(0,w));tn_G(h,new tn_c(0,w))}else if(b){tn_G(f,new tn_c(y,w));tn_G(h,new tn_c(v,w))}else if(c){tn_G(f,
new tn_c(p,0));tn_G(h,new tn_c(D,0))}else{tn_G(f,new tn_c(p,B));tn_G(h,new tn_c(D,C))}var U;U=this.na=="rtl"?0+m:y-14+0;var $=w-0;tn_G(g.close,new tn_c(U,$));if(g.close.style.visibility!="hidden")if(this.na=="rtl")U+=16;else U-=16;var aa=new tn_c(U,$);tn_G(g.maximize,aa);tn_G(g.restore,aa);this.za=new tn_c(s+8,z+8);for(var F=0;F<this.m.length;F++){var ba=this.m[F];tn_G(ba,this.za)}if(this.g.length<2){tn_M(g.iws_tab_l);tn_M(g.iws_tab_r);tn_M(g.iws_tab_dl);tn_M(g.iws_tab_dr);tn_N(g.iw_sw);tn_N(g.iws_sw);
tn_N(g.iw_nw);tn_N(g.iws_nw)}else{if(k){tn_M(g.iw_nw);tn_M(g.iws_nw);tn_N(g.iw_sw);tn_N(g.iws_sw)}else{tn_M(g.iw_sw);tn_M(g.iws_sw);tn_N(g.iw_nw);tn_N(g.iws_nw)}for(var F=0;F<this.g.length;++F){var S=this.g[F],x=S.images,X=S.textWidth,O=S.labelNode,Y=O.style,M;if(F>0)M=this.Aa[F-1];tn_M(x.iw_tabback_dl);tn_M(x.iw_tabback_dm);tn_M(x.iw_tabback_dr);tn_M(x.iw_tabback_l);tn_M(x.iw_tabback_m);tn_M(x.iw_tabback_r);tn_M(x.iw_tab_dl);tn_M(x.iw_tab_dm);tn_M(x.iw_tab_dr);tn_M(x.iw_tab_l);tn_M(x.iw_tab_m);tn_M(x.iw_tab_r);
tn_M(x.iws_tab_m);tn_M(x.iws_tab_dm);if(M){tn_M(M.iws_tab_do);tn_M(M.iws_tab_o)}else{tn_M(x.iw_tab_1l);tn_M(x.iw_tab_1dl);tn_M(x.iw_tabback_1l);tn_M(x.iw_tabback_1dl);tn_M(x.iws_tab_1l);tn_M(x.iws_tab_1dl)}var P,N,Q,V,R,T=this.e.style.zIndex;if(k){if(this.q==F){P=F==0?x.iw_tab_1l:x.iw_tab_l;N=x.iw_tab_m;Q=x.iw_tab_r;++T}else{P=F==0?x.iw_tabback_1l:x.iw_tabback_l;N=x.iw_tabback_m;Q=x.iw_tabback_r}V=x.iws_tab_m;if(M)R=M.iws_tab_o;Y.paddingTop=tn_I(4);Y.paddingBottom=tn_I(0)}else{if(this.q==F){P=F==
0?x.iw_tab_1dl:x.iw_tab_dl;N=x.iw_tab_dm;Q=x.iw_tab_dr;++T}else{P=F==0?x.iw_tabback_1dl:x.iw_tabback_dl;N=x.iw_tabback_dm;Q=x.iw_tabback_dr}V=x.iws_tab_dm;if(M)R=M.iws_tab_do;Y.paddingTop=tn_I(4);Y.paddingBottom=""}tn_N(P);tn_N(N);tn_N(Q);tn_N(V);var W=S.offset+(F==0?6:11);tn_G(P,new tn_c(s+S.offset,H));tn_G(N,new tn_c(s+W,H));tn_K(N,X);tn_G(V,new tn_c(r+2+W,G));tn_K(V,X);tn_G(Q,new tn_c(s+W+X,H));if(R){tn_N(R);tn_G(R,new tn_c(r+W-14+2,G));R.parentNode||tn_H(this.j,R)}P.style.zIndex=T;N.style.zIndex=
T;Q.style.zIndex=T;var ca=X+2+3;tn_K(O,ca);tn_G(O,new tn_c(s+W-2,J));tn_N(O);O.style.zIndex=T+1;!O.parentNode&&S.textWidth>0&&tn_H(this.e,O)}}};tn_2.prototype.J=function(){if(this.pa)this.W(this.pa,this.T);else this.U&&this.X(this.U,this.T)};tn_2.prototype.A=function(){return new tn_U(tn_P(this.n.width,this.s),this.n.height)};tn_2.prototype.reset=function(a,b,c,d,e){this.D(c,b,e);this.X(a,d);this.show();tn_hd(this.i.restore)};
tn_2.prototype.hide=function(){this.aa&&tn_M(this.aa);this.Y&&tn_M(this.Y);tn_M(this.e);tn_M(this.j)};tn_2.prototype.show=function(){if(this.Ua()){tn_N(this.e);tn_N(this.j);this.aa&&tn_N(this.aa);this.Y&&tn_N(this.Y)}};tn_2.prototype.ob=function(){this.Jb=tn_};tn_2.prototype.Ua=function(){return this.e.style.display=="none"};tn_2.prototype.jb=function(a){if(a==this.q)return;this.xa(a);var b=this.m;tn_xd(b,tn_M);tn_N(b[a]);var c=this;window.setTimeout(function(){c.J()},0)};
tn_2.prototype.Xa=function(){tn_Z(this,tn_4d)};tn_2.prototype.maximize=function(a){if(this.R)return;tn_Z(this,tn_5d);tn_id(this.i.restore);this.qb=this.n;this.Hb=this.g;this.Gb=this.q;this.C=this.C||new tn_U(628,598);var b=new tn_U(4+this.C.width,4+this.C.height);if(tn_S.k())b.width+=1;this.ma(b,a)};tn_2.prototype.restore=function(a){if(!this.R)return;tn_Z(this,tn_6d);tn_hd(this.i.restore);this.D(this.C,this.Hb,this.Gb);this.xb=this.qb;this.ma(this.qb,a)};
tn_2.prototype.ma=function(a,b){this.la=new tn_Ee(b===tn_?1:10);this.P=this.n;this.Oa=a;this.ga()};tn_2.prototype.ga=function(){var a=this.la.next();this.la.more()&&tn_qd(this,this.ga,10);var b=this.P.width+(this.Oa.width-this.P.width)*a,c=this.P.height+(this.Oa.height-this.P.height)*a;this.V(new tn_U(b,c));this.J();this.sb();this.la.more()||this.Na()};tn_2.prototype.Na=function(){if(this.R){this.R=tn_a;tn_Z(this,tn_8d)}else{this.R=tn_;tn_Z(this,tn_7d);this.D(this.C,this.zb,this.yb)}};
tn_2.prototype.V=function(a){var b=this.n=this.fa(a);return b};tn_2.prototype.La=function(a){if(tn_S.type==1)tn_oe(a);else{var b=tn_De(a,this.e);b.y<=this.ka()&&tn_oe(a)}};tn_2.prototype.ia=function(a){if(tn_S.type==1)tn_pe(a);else{var b=tn_De(a,this.e);if(b.y<=this.ka())a.cancelDrag=tn_}};tn_2.prototype.ka=function(){return this.A().height+12};tn_2.prototype.ja=function(){var a=this.A();return new tn_U(a.width+12,a.height+21+6)};
tn_2.prototype.D=function(a,b,c){this.Ga();this.xb=a;var d=new tn_U(4+a.width,4+a.height);if(tn_S.k())d.width+=1;var e=this.V(d),f=[];this.g=f;var h=c||0,i=new tn_U(e.width+-4,e.height+-4),k=this.za,j=this.m=[];for(var g=0;g<b.length;g++){var l=tn_F("div",this.e,k,i);tn_kd(l);g!=h&&tn_M(l);l.style.zIndex=10;tn_H(l,b[g].contentElem);j.push(l)}if(b.length>1){var o=[],q=new tn_U(11,26),s=new tn_U(14,26);this.Sa();for(var g=0;g<b.length;++g){var r={images:b[g].images||{},textWidth:b[g].textWidth||0,offset:b[g].offset||
0,name:b[g].name,contentElem:b[g].contentElem,onclick:b[g].onclick},m=r.images;tn_Ie(m,this.e,[["iw_tabback_dm",1,26,0,0],["iw_tabback_m",1,26,0,0],["iw_tab_dm",1,26,0,0],["iw_tab_m",1,26,0,0]]);tn_3(m,this.e,"iw_tabback_dl",q);tn_3(m,this.e,"iw_tabback_dr",s);tn_3(m,this.e,"iw_tabback_l",q);tn_3(m,this.e,"iw_tabback_r",s);tn_3(m,this.e,"iw_tab_dl",q);tn_3(m,this.e,"iw_tab_dr",s);tn_3(m,this.e,"iw_tab_l",q);tn_3(m,this.e,"iw_tab_r",s);tn_Ie(m,this.j,[["iws_tab_dm",1,28,0,0],["iws_tab_m",1,28,0,0]]);
function n(t,w){tn_M(w);t.$.push(w)}if(g==0){var y=new tn_U(6,26);tn_3(m,this.e,"iw_tab_1dl",y);tn_3(m,this.e,"iw_tab_1l",y);tn_3(m,this.e,"iw_tabback_1dl",y);tn_3(m,this.e,"iw_tabback_1l",y);var v=new tn_U(8,28);tn_3(m,this.j,"iws_tab_1dl",v);tn_3(m,this.j,"iws_tab_1l",v);n(this,m.iw_tab_1dl);n(this,m.iw_tab_1l);n(this,m.iw_tabback_1dl);n(this,m.iw_tabback_1l);n(this,m.iws_tab_1dl);n(this,m.iws_tab_1l)}n(this,m.iw_tabback_dl);n(this,m.iw_tabback_dm);n(this,m.iw_tabback_dr);n(this,m.iw_tabback_l);
n(this,m.iw_tabback_m);n(this,m.iw_tabback_r);n(this,m.iw_tab_dl);n(this,m.iw_tab_dm);n(this,m.iw_tab_dr);n(this,m.iw_tab_l);n(this,m.iw_tab_m);n(this,m.iw_tab_r);n(this,m.iws_tab_dm);n(this,m.iws_tab_m);var p=document.createElement("div");r.labelNode=p;tn_L(p,20);var D=p.style;tn_kd(p);D.fontWeight="bold";D.fontFamily="Arial,sans-serif";D.fontSize=tn_I(12);D.textAlign="center";D.display="inline";tn_Je(p);tn_gd(r.name,p);(function(t,w,A,B){tn_ne(B,t,function(){t.jb(w);A&&A()})})(this,g,b[g].onclick,
p);this.$.push(p);o.push(p);this.g.push(r);if(g>0){var E={},u=new tn_U(14,28);tn_3(E,this.j,"iws_tab_do",u);tn_3(E,this.j,"iws_tab_o",u);n(this,E.iws_tab_do);n(this,E.iws_tab_o);this.Aa.push(E)}}var z=this;tn_Od(o,function(t){var w;if(t.length==f.length){for(var A=0;A<t.length;++A){var B=w=f[A];if(t[A].width!=0)B.textWidth=tn_P(0,t[A].width-2-3);tn_N(B.labelNode);tn_H(z.e,B.labelNode);if(A>0){var C=f[A-1];B.offset=C.offset+C.textWidth+(A==1?6:11)+14-11}}z.s=w.offset+w.textWidth+ +14+11-6;if(z.s+30>
e.width){z.V(new tn_U(z.s+30,e.height));var H=new tn_U(z.s+30+-4,e.height+-4);for(var A=0;A<z.m.length;++A)tn_fd(z.m[A],H)}}z.xa(h);z.J()})}else{var r={images:b[0].images||{},textWidth:b[0].textWidth||0,offset:b[0].offset||0,name:b[0].name,contentElem:b[0].contentElem,onclick:b[0].onclick};this.g.push(r);this.J()}};tn_2.prototype.sb=function(){var a=new tn_U(this.n.width+-4,this.n.height+-4);for(var b=0;b<this.m.length;b++){var c=this.m[b];tn_fd(c,a)}};
tn_2.prototype.mb=function(a,b,c){this.C=a;this.zb=b;this.yb=c;tn_id(this.i.maximize)};tn_2.prototype.Ga=function(){var a=this.m;tn_xd(a,tn_R);tn_Jd(a);var b=this.$;tn_xd(b,tn_R);tn_Jd(b);this.q=0};tn_2.prototype.fa=function(a){return new tn_U(tn_P(a.width,32),tn_P(a.height,0))};tn_2.prototype.Sa=function(){this.$=[];this.Aa=[];this.s=0};tn_2.prototype.xa=function(a){tn_Je(this.g[this.q].labelNode);this.q=a;tn_Ke(this.g[a].labelNode)};
function tn_Ke(a){var b=a.style;b.color="";b.textDecoration="";tn_Q(a,"")}function tn_Je(a){var b=a.style;b.color="#0000cc";b.textDecoration="underline";tn_Q(a,"pointer")}function tn_Ie(a,b,c){var d=tn_F("div",b);for(var e=0;e<c.length;e++){var f=c[e],h=new tn_U(f[1],f[2]),i=new tn_c(f[3],f[4]),k=tn_Vd(f[0]),j=tn_Pd(k,d,i,h,tn_,tn_);a[f[5]||f[0]]=j}return d}
function tn_3(a,b,c,d,e){if(tn_S.type==1&&tn_S.version<7){var f=tn_Pd(tn_Vd(c),b,new tn_c(0,0),d,tn_,tn_);a[e||c]=f;return f}if(!tn_Ge){tn_Ge=tn_;var h=document.createElement("link");h.rel="stylesheet";h.type="text/css";h.href=tn_Fe;document.getElementsByTagName("head")[0].appendChild(h)}var i=document.createElement("div");i.className="SPRITE_"+c;b.appendChild(i);a[e||c]=i;return i};if(window.jstiming)window.jstiming.report=function(a,b){var c="";if(window.jstiming.pt){c+="&srt="+window.jstiming.pt;delete window.jstiming.pt}if(window.external&&window.external.tran)c+="&tran="+window.external.tran;var d=a.t,e=d.start;delete d.start;var f=[];for(var h in d)f.push(h+"."+(d[h]-e));if(b)for(var i in b)c+="&"+i+"="+b[i];(new Image).src=["http://csi.gstatic.com/csi?v=3","&s=translate&action=",a.name,c,"&rt=",f.join(",")].join("")};var tn_Le="google-feedback-frame",tn_4,tn_5=tn_b,tn_6,tn_Me,tn_Ne,tn_Oe=tn_a,tn_Pe=tn_a,tn_7=tn_a,tn_8=tn_a,tn_9={};tn_9.right="left";tn_9.left="right";tn_9.ltr="rtl";tn_9.rtl="ltr";function tn_Qe(a){return a.substring(0,1).toUpperCase()+a.substring(1)}
var _intlStrings={_originalText:"Original Text:",_interfaceDirection:"ltr",_interfaceAlign:"left",_langpair:"",_suggestTranslation:"Suggest a translation",_submit:"Submit",_feedbackUrl:"http://translate.google.com/translate_suggestion",_suggestThanks:"Thank you for helping us improve the quality of our translations.",_reverse:tn_a};
function tn_Re(a){if(a.nodeType==3)return a.nodeValue;else if(a.nodeType==1){var b=new String;for(var c=0;c<a.childNodes.length;++c)b+=tn_Re(a.childNodes[c]);return b}else return undefined}
function _setupIW(){if(tn_Oe)return;tn_4=new tn_2;tn_6=document.createElement("div");tn_6.id="google-infowindow";tn_Me=document.createElement("span");tn_6.onmouseover=tn_Se;tn_6.onmouseout=tn_Te;document.body.appendChild(tn_Me);document.body.appendChild(tn_6);var a=document.createElement("div");document.body.appendChild(a);tn_M(a);a.innerHTML='<iframe id="'+tn_Le+'" name="'+tn_Le+'"></iframe>';tn_4.create(tn_6,tn_Me);tn_6.firstChild.style.zIndex=9000;tn_Me.firstChild.style.zIndex=8999;tn_4.Z(tn_);
tn_4.Va(tn_);tn_4.Wa(tn_);tn_4.Ca(tn_);tn_4.Da(tn_a);tn_4.lb(_intlStrings._interfaceDirection);tn_ge(tn_4,tn_4d,function(){tn_Te(tn_);tn_8&&tn_Ue(tn_a)});tn_Oe=tn_}var tn_$=tn_b;function tn_Se(){tn_Pe=tn_;tn_Ve(tn_5)}
function tn_Ve(a){if(!a)return;if(tn_$!==tn_b){window.clearTimeout(tn_$);tn_$=tn_b}if(tn_7)return;if(tn_5==a){if(tn_8)return;tn_Ne=tn_5.style.backgroundColor;tn_5.style.backgroundColor="#E6ECF9";return}if(tn_8){tn_4.restore(tn_);tn_8=tn_a}var b,c;for(var d=0;d<a.childNodes.length;++d)if(a.childNodes[d].className=="google-src-text"){b=a.childNodes[d].cloneNode(tn_);c=a.cloneNode(tn_);c.removeChild(c.childNodes[d]);b.className="google-src-active-text";break}if(!b)return;tn_4.Z(tn_);tn_Ne=a.style.backgroundColor;
a.style.backgroundColor="#E6ECF9";var e=document.createElement("div"),f=document.createElement("div"),h=document.createElement("img"),i=document.createElement("div");i.appendChild(h);h.width=48;h.height=17;h.border=0;h.style.padding="0px";h.style.border="0px solid black";i.style.margin="0px";i.style.marginBottom="-17px";i.style.padding="0px";i.style.textAlign=tn_9[_intlStrings._interfaceAlign];h.src="http://www.google.com/images/logo_smallest.png";h.style["margin"+tn_Qe(_intlStrings._interfaceAlign)]=
"6px";h.style["margin"+tn_Qe(tn_9[_intlStrings._interfaceAlign])]=tn_I(18);e.appendChild(i);e.appendChild(f);f.appendChild(document.createTextNode(_intlStrings._originalText));f.style.color="#A0A0A0";f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.fontSize="smaller";f.style.minHeight="17px";f.style.fontFamily="arial,sans-serif";f.style["margin"+tn_Qe(tn_9[_intlStrings._interfaceAlign])]=tn_I(72);e.appendChild(b);e.style.zIndex=10000;if(_intlStrings._langpair.length==
0){tn_5=a;tn_Nd(e,function(L){tn_4.hide();tn_4.D(L,[new tn_He(_intlStrings._originalText,e)]);tn_4.W(tn_5);tn_4.show()},(document.width||document.body.scrollWidth)/2)}else{var k=e.cloneNode(tn_),j=document.createElement("div");j.appendChild(k);var g=document.createElement("div"),l=document.createElement("span"),o=document.createElement("div");o.style.direction=_intlStrings._interfaceDirection;o.style.textAlign=_intlStrings._interfaceAlign;o.style.marginTop=tn_I(10);g.appendChild(o);var q=document.createElement("img");
q.src="http://www.google.com/mb/plus_sm.gif";q.width=12;q.height=12;q.border=0;q.style.border="none";o.appendChild(q);o.appendChild(document.createTextNode(" "));o.appendChild(l);l.appendChild(document.createTextNode(_intlStrings._suggestTranslation));l.style.direction=_intlStrings._interfaceDirection;l.style.textAlign=_intlStrings._interfaceAlign;l.style.color="#77c";l.style.textDecoration="underline";l.style.fontFamily="arial,sans-serif";l.style.fontSize="smaller";o.onclick=tn_We;tn_Q(l,"pointer");
e.appendChild(g);var s=document.createElement("div"),r=document.createElement("div"),m=document.createElement("span");r.style.direction=_intlStrings._interfaceDirection;r.style.textAlign=_intlStrings._interfaceAlign;r.style.marginTop=tn_I(10);r.style.marginBottom=tn_I(6);s.appendChild(r);var n=document.createElement("img");n.src="http://www.google.com/mb/minus_sm.gif";n.width=12;n.height=12;n.border=0;n.style.border="none";r.appendChild(n);r.appendChild(document.createTextNode(" "));r.appendChild(m);
m.appendChild(document.createTextNode(_intlStrings._suggestTranslation));m.style.direction=_intlStrings._interfaceDirection;m.style.textAlign=_intlStrings._interfaceAlign;m.style.color="#77c";m.style.textDecoration="underline";m.style.fontFamily="arial,sans-serif";m.style.fontSize="smaller";r.onclick=function(){tn_Ue(tn_)};tn_Q(m,"pointer");var y=document.createElement("div"),v=document.createElement("form");v.style.marginBottom="0px";v.style.paddingBottom="0px";v.target=tn_Le;v.method="post";v.action=
_intlStrings._feedbackUrl;y.appendChild(v);var p=document.createElement("input");p.type="hidden";p.name="gtrans";v.appendChild(p);var D,E;if(_intlStrings._reverse){E=tn_Re(c);D=tn_Re(b)}else{D=tn_Re(c);E=tn_Re(b)}p.value=D;var u=document.createElement("input");u.type="hidden";u.value=E;u.name="text";v.appendChild(u);var z=document.createElement("input");z.name="langpair";z.type="hidden";z.value=_intlStrings._langpair;v.appendChild(z);var t=document.createElement("input");t.name="u";t.type="hidden";
var w=document.createElement("input");w.name="oe";w.type="hidden";var A=window.location.href,B=A.indexOf("u=");if(B>-1){v.appendChild(t);var C=A.indexOf("&",B+2);t.value=C==-1?window.unescape(A.substring(B+2)):window.unescape(A.substring(B+2,C))}if(document.charset){w.value=document.charset;v.appendChild(w)}else if(document.characterSet){w.value=document.characterSet;v.appendChild(w)}else{var H=A.indexOf("oe=");if(H>-1){v.appendChild(w);var C=A.indexOf("&",H+3);w.value=C==-1?window.unescape(A.substring(H+
3)):window.unescape(A.substring(H+3,C))}}var G=document.createElement("textarea");G.rows=3;G.name="utrans";G.value=D;v.appendChild(G);var J=document.createElement("div");J.style.direction=_intlStrings._interfaceDirection;J.style.textAlign=tn_9[_intlStrings._interfaceAlign];J.style.marginTop=tn_I(6);J.style.marginBottom="0px";v.appendChild(J);var K=document.createElement("input");K.type="submit";K.value=_intlStrings._submit;J.appendChild(K);var I=document.createElement("div");I.appendChild(document.createElement("hr"));
I.appendChild(document.createTextNode(_intlStrings._suggestThanks));I.style.direction=_intlStrings._interfaceDirection;I.style.textAlign=_intlStrings._interfaceAlign;I.style.fontFamily="arial,sans-serif";I.style.fontSize="smaller";I.style.overflow="auto";I.style.marginTop="10px";tn_M(I);s.appendChild(y);j.appendChild(s);j.appendChild(I);v.onsubmit=function(){window.setTimeout(function(){tn_M(s);tn_N(I)},1);tn_7=tn_a;return tn_};tn_5=a;tn_Od([j,e],function(L){G.style.width=tn_I(L[0].width);tn_4.hide();
tn_4.D(L[1],[new tn_He(_intlStrings._originalText,e)]);tn_4.mb(L[0],[new tn_He(_intlStrings._originalText,j)]);tn_4.W(tn_5);tn_4.Z(tn_);tn_4.show()},(document.width||document.body.scrollWidth)/2)}}function tn_Xe(a){if(!tn_Oe)return;tn_Pe=tn_;if(tn_7)return;if(tn_$!==tn_b){window.clearTimeout(tn_$);tn_$=tn_b}if(tn_5==a){tn_Ne=tn_5.style.backgroundColor;tn_5.style.backgroundColor="#E6ECF9";return}tn_$=window.setTimeout(function(){tn_Ve(a)},500)}
function tn_Te(a){if(!tn_Oe)return;if(a!==tn_)tn_Pe=tn_a;if(tn_7)return;if(tn_5&&tn_5.style)tn_5.style.backgroundColor=tn_Ne;if(tn_$){window.clearTimeout(tn_$);tn_$=tn_b}if(a!==tn_)tn_$=window.setTimeout(tn_Ye,250);else tn_Ye()}function tn_Ye(){if(tn_7)return;tn_4.hide();if(tn_8){tn_4.restore(tn_);tn_8=tn_a}tn_5=tn_b}function tn_We(){tn_7=tn_;tn_8=tn_;var a=tn_ge(tn_4,tn_7d,function(){tn_he(a)});tn_4.maximize()}
function tn_Ue(a){var b=tn_ge(tn_4,tn_8d,function(){tn_he(b);tn_8=tn_a;if(a)window.setTimeout(function(){tn_7=tn_a;tn_Pe||tn_Te(tn_)},500);else{tn_7=tn_a;tn_Pe||tn_Te(tn_)}});tn_4.restore()}function _csi(a,b,c){var d={};d.sl=a;d.tl=b;d.url=c;var e=window.jstiming.load;e.tick("prt");e.tick("ol");e.name="w";window.jstiming.report(e,d)}var _tipon=tn_Xe,_tipoff=tn_Te,tn_Ze=window.jstiming.load;tn_Ze.tick("jl");
