#!/bin/sh

# This script runs through the directory tree for a set of WinAVR /
# AVR Studio 4 projects and tweaks the Makefiles so they'll work with
# avr-gcc under UNIX, Linux, or OSX.

# It's not the cleanest example of how to script, but keeping the changes
# separate makes it easier to read and understand what changes the script
# is actually making, and why.

# Remove all the .o.d files - This must be done before running a
# "make clean" in each project directory since the Makefiles look at
# the .o.d files, even when making clean.
find . -name "*.o.d" -exec rm {} \;

# Fix all makefiles:
for i in `find . -name "Makefile" -print`
do
# Change avr-gcc.exe to avr-gcc
sed s/"avr-gcc.exe"/"avr-gcc"/g $i > tmp1
# Remove -gdwarf-2
sed s/"-gdwarf-2 "/""/g tmp1 > tmp2
# Disable avr-size
sed s/"avr-size"/"# avr-size"/g tmp2 > $i
#clean up
rm tmp1 tmp2
done



