#!/bin/sh 
if [ -z "$1" -o "$1" = "-h" -o "$1" = "--help" ]; then
	echo "prg_load_uc -- load a .hex file into a atmega168 microcontroller"
	echo ""
	echo "Usage: prg_load_uc [-h] File.hex"
	echo ""
	echo "OPTIONS: -h this help"
	echo ""
	echo "This script can be easily adapted to different programmer types"
	exit 0
fi
pfile="$1"

set -x
avrdude -p m168 -c avrusb500 -e -F -B 2 -U flash:w:"$pfile"
set +x


