//==============================================================================
// File:           bootldr.h
// Compiler:       IAR Atmel AVR C/EC++ Compiler
// Output Size:    -
// Created:        03/25/11
//
// Description:    This file is generated by 'create' tool and is to be included
//                 in the 'bootldr' project. It contains the settings to
//                 configure the boot loader according to the configurations
//                 used in the encrypted file.
//==============================================================================


#ifndef BOOTLDR_H
#define BOOTLDR_H


#define PAGE_SIZE 256
#define MEM_SIZE 129024
#define CRC_CHECK
#define SIGNATURE 0xF31C1404
#define BUFFER_SIZE 276
#define INITIALVECTOR_HI 0x1754FE11
#define INITIALVECTOR_LO 0x111AD165
#define KEY_COUNT 3


#endif // BOOTLDR_H
