/* definitions generated by preprocessor.xls, copy into defines.h */	

#include <avr/io.h>	

#define	_ATMEGA128	// device select: _ATMEGAxxxx
#define	_B1024	// boot size select: _Bxxxx (words), powers of two only			
		
/* define pin for enter-self-prog-mode */		
#define	PROGPORT	PORTF
#define	PROGPIN	PINF
#define	PROG_NO	PF0
		
/* baud rate register value calculation */		
#define	CPU_FREQ	8000000
#define	BAUD_RATE	57600 // Higher speed not possible with FT232R connected at ATmega128L
#define	BRREG_VALUE	16 
#define ENABLE_U2X

/* Time(ms) to wait before reading the pbutton and making the choice of either entering the program mode or normal operation*/
//#define BOOT_WAIT 1000
		
/* definitions for UART control */		
#define	BAUD_RATE_LOW_REG	UBRR0L
#define UART_CONTROL_REGA	UCSR0A
#define	UART_CONTROL_REGB	UCSR0B
#define	ENABLE_TRANSMITTER_BIT	TXEN0
#define	ENABLE_RECEIVER_BIT	RXEN0
#define	UART_STATUS_REG	UCSR0A
#define	TRANSMIT_COMPLETE_BIT	TXC0
#define	RECEIVE_COMPLETE_BIT	RXC0
#define	UART_DATA_REG	UDR0
		
/* definitions for SPM control */		
#define	SPMCR_REG	SPMCSR
#define	PAGESIZE	256
#define	APP_END	129024
#define	LARGE_MEMORY	
		
/* definitions for device recognition */		
#define	PARTCODE	0x44
#define	SIGNATURE_BYTE_1	0x1E
#define	SIGNATURE_BYTE_2	0x97
#define	SIGNATURE_BYTE_3	0x02
			
