######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 22 17:40:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Qtalkusb.hh
FORMS += Qtalkusb.ui
SOURCES += FlashImage.cc main.cc MCUTarget.cc
