.TH "FunkOS_Timer" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunkOS_Timer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timer.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunkOS_Timer\fP ()"
.br
.ti -1c
.RI "void \fBCreate\fP (USHORT usTicks_, USHORT usOffset_, \fBTIMER_CALLBACK\fP pfCallback_)"
.br
.ti -1c
.RI "\fBTIMER_STATE\fP \fBGetState\fP (void)"
.br
.ti -1c
.RI "void \fBStart\fP (void)"
.br
.ti -1c
.RI "void \fBStop\fP (void)"
.br
.ti -1c
.RI "void \fBTick\fP (void)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FunkOS_Timer::FunkOS_Timer ()"Initialize the timer event table to default values. 
.SH "Member Function Documentation"
.PP 
.SS "void FunkOS_Timer::Create (USHORT usTicks_, USHORT usOffset_, \fBTIMER_CALLBACK\fP pfCallback_)"Sets the timer event to execute at a specified interval. Must be added to the timer list before it will be executed.
.PP
\fBParameters:\fP
.RS 4
\fIusTicks_\fP - the time (in system ticks) between triggering the callback 
.br
\fIusOffset_\fP - the phase offset of the event (in system ticks) 
.br
\fIpfCallback_\fP - function pointer to the lighweight thread 
.RE
.PP

.SS "\fBTIMER_STATE\fP FunkOS_Timer::GetState (void)"
.SS "void FunkOS_Timer::Start (void)"Start the timer event specified 
.SS "void FunkOS_Timer::Stop (void)"
.SS "void FunkOS_Timer::Tick (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
