.TH "C:/Projects/R3/kernel++/heap.cpp" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/heap.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'taskport.h'\fP
.br
\fC#include 'heap.h'\fP
.br

.SH "Detailed Description"
.PP 
Description: Static block-size heap implementation 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
