.TH "C:/Projects/R3/kernel++/heap.h" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/heap.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Description: static block-size heap configuration 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
