.TH "C:/Projects/R3/kernel++/message.h" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/message.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'semaphore.h'\fP
.br
\fC#include 'types.h'\fP
.br
\fC#include 'kernelcfg.h'\fP
.br

.SH "Detailed Description"
.PP 
Description: Threadsafe message queue 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
