.TH "C:/Projects/R3/kernel++/mutex.cpp" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/mutex.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mutex.h'\fP
.br
\fC#include 'types.h'\fP
.br
\fC#include 'task.h'\fP
.br
\fC#include 'taskport.h'\fP
.br
\fC#include 'kernelcfg.h'\fP
.br

.SH "Detailed Description"
.PP 
Description: Mutual exclusion semaphore implementation for FunkOS 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
