.TH "C:/Projects/R3/kernel++/mutex.h" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/mutex.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'task.h'\fP
.br
\fC#include 'taskport.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFunkOS_Mutex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Declaration of the mutual exclusion semaphore API for FunkOS 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
