.TH "C:/Projects/R3/kernel++/scheduler.cpp" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/scheduler.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'kernelcfg.h'\fP
.br
\fC#include 'task.h'\fP
.br
\fC#include 'taskport.h'\fP
.br
\fC#include 'scheduler.h'\fP
.br
\fC#include 'kernelswi.h'\fP
.br
\fC#include 'kerneltimer.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFunkOS_Task\fP * \fBm_pclCurrentTask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: C++ RTOS scheduler implementation 
.SH "Variable Documentation"
.PP 
.SS "\fBFunkOS_Task\fP* \fBm_pclCurrentTask\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
