.TH "C:/Projects/R3/kernel++/timer.h" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/timer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFunkOS_Timer\fP"
.br
.ti -1c
.RI "class \fBFunkOS_TimerList\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNUM_TIMERS\fP   4"
.br
.RI "\fIThis defines the size of the event table. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBTIMER_CALLBACK\fP )(void)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTIMER_STATE\fP { \fBTIMER_STATE_UNINIT\fP, \fBTIMER_STATE_CLOSED\fP, \fBTIMER_STATE_OPEN\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Fixed-frequency event API 
.SH "Define Documentation"
.PP 
.SS "#define NUM_TIMERS   4"
.PP
This defines the size of the event table. 
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* \fBTIMER_CALLBACK\fP)(void)"
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTIMER_STATE\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fITIMER_STATE_UNINIT \fP\fP
Table entry has not been defined. 
.TP
\fB\fITIMER_STATE_CLOSED \fP\fP
Table entry is disabled. 
.TP
\fB\fITIMER_STATE_OPEN \fP\fP
Table entry is enabled. 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
