.TH "C:/Projects/R3/kernel++/watchdog.cpp" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/watchdog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'watchdog.h'\fP
.br
\fC#include 'kernelwdt.h'\fP
.br
\fC#include 'kernelcfg.h'\fP
.br

.SH "Detailed Description"
.PP 
Description: Portable multitasking watchdog timer implementation. Allows for the system watchdog kick to only trigger when every task meets its deadlines. Can be configured to 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
