.TH "C:/Projects/R3/kernel++/watchdog.h" 3 "20 Mar 2010" "Version R3" "FunkOS++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel++/watchdog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFunkOS_Watchdog\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNUM_WDT_ENTRIES\fP   ((USHORT) 20)"
.br
.ti -1c
.RI "#define \fBTIME_PER_KICK_MS\fP   ((USHORT) 200)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBWATCHDOG_STATE\fP { \fBWDT_TASK_UNINIT\fP =  0, \fBWDT_TASK_IDLE\fP, \fBWDT_TASK_ACTIVE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Portable multitasking watchdog timer interface 
.SH "Define Documentation"
.PP 
.SS "#define NUM_WDT_ENTRIES   ((USHORT) 20)"
.SS "#define TIME_PER_KICK_MS   ((USHORT) 200)"
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBWATCHDOG_STATE\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIWDT_TASK_UNINIT \fP\fP
.TP
\fB\fIWDT_TASK_IDLE \fP\fP
.TP
\fB\fIWDT_TASK_ACTIVE \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS++ from the source code.
