set XX=
set OD=AVR
set OE=O
IF not "%OPATH%"=="" goto :OPATHOK
set OPATH=%PATH%
:OPATHOK
path=\WINAVR\BIN;\WINAVR\AVR\BIN;\HOME\CC\AVRBAT;%OPATH%
SET INCLUDE=\HOME\CC\INCLUDE
md \EXAVR
set OD=AVR
set OE=O
