<ASSEMBLER_INFO>
 <VERSION>2.1.7</VERSION>
 <DEVICE>ATmega16</DEVICE>
 <WORKING_DIR>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer</WORKING_DIR>
 <INCLUDE_PATH>
  <DIR>C:\avrgcc\avr\include</DIR>
  <DIR>C:\Program Files\Atmel\AVR Tools\AvrAssembler2\Appnotes</DIR>
 </INCLUDE_PATH>
 <SOURCE_FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</SOURCE_FILE>
 <INCLUDED_FILES>
  <FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\m16def.inc</FILE>
  <FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\characters.inc</FILE>
  <FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE>
 </INCLUDED_FILES>
 <OBJECT_FILES>
  <FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.obj</FILE>
 </OBJECT_FILES>
 <HEX_FILES>
  <FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.hex</FILE>
  <FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.eep</FILE>
 </HEX_FILES>
 <OUTPUT_FILES>
  <FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.map</FILE>
 </OUTPUT_FILES>
 <LABELS>
  <NORMAL_CHARACTER_PATTERNS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\characters.inc</FILE><LINE>4</LINE></NORMAL_CHARACTER_PATTERNS>
  <horigin><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>2</LINE></horigin>
  <vorigin><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>3</LINE></vorigin>
  <new><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>4</LINE></new>
  <current><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>5</LINE></current>
  <old><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>6</LINE></old>
  <new_ext><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>7</LINE></new_ext>
  <current_ext><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>8</LINE></current_ext>
  <graphl><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>9</LINE></graphl>
  <graphb><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>10</LINE></graphb>
  <graphr><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>11</LINE></graphr>
  <grapht><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>12</LINE></grapht>
  <fgcol><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>13</LINE></fgcol>
  <fgact><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>14</LINE></fgact>
  <bgcol><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>15</LINE></bgcol>
  <bgact><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>16</LINE></bgact>
  <ftcol><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>17</LINE></ftcol>
  <btcol><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>18</LINE></btcol>
  <screenw><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>19</LINE></screenw>
  <screenh><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>20</LINE></screenh>
  <textwl><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>21</LINE></textwl>
  <textwb><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>22</LINE></textwb>
  <textwr><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>23</LINE></textwr>
  <textwt><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>24</LINE></textwt>
  <incurh><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>25</LINE></incurh>
  <incurv><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>26</LINE></incurv>
  <pattern><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>27</LINE></pattern>
  <dx><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>28</LINE></dx>
  <dy><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>29</LINE></dy>
  <error><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>30</LINE></error>
  <startx><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>32</LINE></startx>
  <starty><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>33</LINE></starty>
  <endx><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>34</LINE></endx>
  <endy><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>35</LINE></endy>
  <cstartx><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>36</LINE></cstartx>
  <cstarty><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>37</LINE></cstarty>
  <cendx><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>38</LINE></cendx>
  <cendy><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>39</LINE></cendy>
  <final_y><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>40</LINE></final_y>
  <fill_block><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>41</LINE></fill_block>
  <plot_command><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>43</LINE></plot_command>
  <ZMASK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>44</LINE></ZMASK>
  <ZSTART><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>45</LINE></ZSTART>
  <ZMEMC><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>46</LINE></ZMEMC>
  <ignore_char><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>48</LINE></ignore_char>
  <cursor_pattern><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>49</LINE></cursor_pattern>
  <old_cursor_pattern><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>50</LINE></old_cursor_pattern>
  <mode><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>51</LINE></mode>
  <tv><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>52</LINE></tv>
  <char_table><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>54</LINE></char_table>
  <vduque><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>55</LINE></vduque>
  <line_count><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>59</LINE></line_count>
  <time><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>60</LINE></time>
  <user_flag><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>61</LINE></user_flag>
  <user_chars><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>62</LINE></user_chars>
  <top_of_data><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>63</LINE></top_of_data>
  <buffer><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\sram.inc</FILE><LINE>65</LINE></buffer>
  <BOOT_MESSAGE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>133</LINE></BOOT_MESSAGE>
  <VERSION_MESSAGE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>136</LINE></VERSION_MESSAGE>
  <USER_EEPROM><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>142</LINE></USER_EEPROM>
  <RESET><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>171</LINE></RESET>
  <EXT_INT0><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1190</LINE></EXT_INT0>
  <EXT_INT1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1194</LINE></EXT_INT1>
  <TIM2_COMP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1198</LINE></TIM2_COMP>
  <TIM2_OVF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1202</LINE></TIM2_OVF>
  <TIM1_CAPT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1206</LINE></TIM1_CAPT>
  <TIM1_COMPA><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1209</LINE></TIM1_COMPA>
  <TIM1_COMPB><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1213</LINE></TIM1_COMPB>
  <TIM1_OVF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1217</LINE></TIM1_OVF>
  <TIM0_OVF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1228</LINE></TIM0_OVF>
  <SPI_STC><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1257</LINE></SPI_STC>
  <USART_RXC><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1261</LINE></USART_RXC>
  <USART_UDRE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1401</LINE></USART_UDRE>
  <USART_TXC><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1405</LINE></USART_TXC>
  <ADCC><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1409</LINE></ADCC>
  <EE_RDY><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1414</LINE></EE_RDY>
  <ANA_COMP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1418</LINE></ANA_COMP>
  <TWSI><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1422</LINE></TWSI>
  <EXT_INT2><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1426</LINE></EXT_INT2>
  <TIM0_COMP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1430</LINE></TIM0_COMP>
  <SPM_RDY><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1434</LINE></SPM_RDY>
  <MAIN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>180</LINE></MAIN>
  <DISPLAY_ON><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>343</LINE></DISPLAY_ON>
  <SCROLL_DISPLAY><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>304</LINE></SCROLL_DISPLAY>
  <RST_WINDOWS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1361</LINE></RST_WINDOWS>
  <DEFAULT_COLOURS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3825</LINE></DEFAULT_COLOURS>
  <CLEAR_SCREEN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>259</LINE></CLEAR_SCREEN>
  <EEPROM_STRING><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3963</LINE></EEPROM_STRING>
  <USART_Init><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3910</LINE></USART_Init>
  <TIMER1_INIT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3924</LINE></TIMER1_INIT>
  <TIMER0_INIT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3940</LINE></TIMER0_INIT>
  <WAIT_FOR_DATA><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>238</LINE></WAIT_FOR_DATA>
  <TESTLOOP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>247</LINE></TESTLOOP>
  <DELAY><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3896</LINE></DELAY>
  <OSWRCH><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>450</LINE></OSWRCH>
  <NEXT_row><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>262</LINE></NEXT_row>
  <TAB><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>415</LINE></TAB>
  <NEXT_column><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>266</LINE></NEXT_column>
  <l_side><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>277</LINE></l_side>
  <r_side><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>271</LINE></r_side>
  <CLOCK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>384</LINE></CLOCK>
  <increment_row><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>282</LINE></increment_row>
  <SEND_SCROLL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>294</LINE></SEND_SCROLL>
  <TWO_SIDE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>360</LINE></TWO_SIDE>
  <SEND_INSTRUCTION><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>328</LINE></SEND_INSTRUCTION>
  <CLEAR_LINE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>308</LINE></CLEAR_LINE>
  <NEXT_COLUMN_CLEAR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>312</LINE></NEXT_COLUMN_CLEAR>
  <NEXT_BYTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>315</LINE></NEXT_BYTE>
  <SEND_DATA><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>333</LINE></SEND_DATA>
  <FETCH_DATA><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>338</LINE></FETCH_DATA>
  <DISPLAY_OFF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>352</LINE></DISPLAY_OFF>
  <NO_SIDE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>366</LINE></NO_SIDE>
  <LEFT_SIDE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>372</LINE></LEFT_SIDE>
  <RIGHT_SIDE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>378</LINE></RIGHT_SIDE>
  <SET_row><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>424</LINE></SET_row>
  <SET_column><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>438</LINE></SET_column>
  <GRAPHIC_CHAR_OUT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>490</LINE></GRAPHIC_CHAR_OUT>
  <PROCESS_SCROLL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>987</LINE></PROCESS_SCROLL>
  <GET_CHARACTER_ADDRESS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>937</LINE></GET_CHARACTER_ADDRESS>
  <NEXT_SLICE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>464</LINE></NEXT_SLICE>
  <NORMAL_CHARS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>474</LINE></NORMAL_CHARS>
  <OSWRCH_OUT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>486</LINE></OSWRCH_OUT>
  <PREPARE_PENDING><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>980</LINE></PREPARE_PENDING>
  <GRAPHIC_CHARACTER_MODE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>624</LINE></GRAPHIC_CHARACTER_MODE>
  <SKIP_34><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>497</LINE></SKIP_34>
  <LOAD><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3298</LINE></LOAD>
  <NEXT_GRAPHIC_SLICE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>508</LINE></NEXT_GRAPHIC_SLICE>
  <SKIP_64><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>519</LINE></SKIP_64>
  <OUTPUT_GRAPHIC_SLICE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>587</LINE></OUTPUT_GRAPHIC_SLICE>
  <SKIP_12><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>517</LINE></SKIP_12>
  <SKIP_14><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>524</LINE></SKIP_14>
  <GCURS_RIGHT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>673</LINE></GCURS_RIGHT>
  <GRAPHIC_USER_DEF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>532</LINE></GRAPHIC_USER_DEF>
  <SKIP_35><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>538</LINE></SKIP_35>
  <SKIP_25><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>556</LINE></SKIP_25>
  <NEXT_USER_GRAPHIC_SLICE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>560</LINE></NEXT_USER_GRAPHIC_SLICE>
  <SKIP_29><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>570</LINE></SKIP_29>
  <SKIP_28><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>568</LINE></SKIP_28>
  <SKIP_32><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>575</LINE></SKIP_32>
  <RS232_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1293</LINE></RS232_DONE>
  <OUTPUT_GRAPHIC_DOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>596</LINE></OUTPUT_GRAPHIC_DOT>
  <NO_DOT_TO_PLOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>609</LINE></NO_DOT_TO_PLOT>
  <WIND><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3311</LINE></WIND>
  <GADDR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3266</LINE></GADDR>
  <PLBYTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3176</LINE></PLBYTE>
  <SKIP_11><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>613</LINE></SKIP_11>
  <C_BLACK_CHOICES><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>642</LINE></C_BLACK_CHOICES>
  <C_PLOT_CLEAR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>657</LINE></C_PLOT_CLEAR>
  <C_PLOT_INVERTED><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>652</LINE></C_PLOT_INVERTED>
  <SKIP_33><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>666</LINE></SKIP_33>
  <C_PLOT_BLACK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>662</LINE></C_PLOT_BLACK>
  <SKIP_19><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>697</LINE></SKIP_19>
  <SKIP_20><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>711</LINE></SKIP_20>
  <TIMES_16><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>883</LINE></TIMES_16>
  <GCURS_DOWN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>833</LINE></GCURS_DOWN>
  <GCURS_LEFT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>726</LINE></GCURS_LEFT>
  <SKIP_21><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>752</LINE></SKIP_21>
  <SKIP_24><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>766</LINE></SKIP_24>
  <GCURS_UP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>781</LINE></GCURS_UP>
  <SKIP_17><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>807</LINE></SKIP_17>
  <SKIP_18><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>818</LINE></SKIP_18>
  <SKIP_15><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>857</LINE></SKIP_15>
  <SKIP_16><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>868</LINE></SKIP_16>
  <GCURS_RET><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>898</LINE></GCURS_RET>
  <NARROW_CHARS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>959</LINE></NARROW_CHARS>
  <DONE_CHARACTER_ADDRESS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>971</LINE></DONE_CHARACTER_ADDRESS>
  <SCROLL_NOW><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>991</LINE></SCROLL_NOW>
  <SLOW_SCROLL_DOWN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1000</LINE></SLOW_SCROLL_DOWN>
  <SCROLL_NEXT_CHAR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1007</LINE></SCROLL_NEXT_CHAR>
  <SKIP_30><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1027</LINE></SKIP_30>
  <COPY_CHARACTER><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1069</LINE></COPY_CHARACTER>
  <PASTE_CHARACTER><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1128</LINE></PASTE_CHARACTER>
  <SLOW_SCROLL_UP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1034</LINE></SLOW_SCROLL_UP>
  <SCROLL_UP_NEXT_CHAR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1042</LINE></SCROLL_UP_NEXT_CHAR>
  <SKIP_31><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1062</LINE></SKIP_31>
  <NEXT_BiTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1086</LINE></NEXT_BiTE>
  <NEXT_BLOTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1135</LINE></NEXT_BLOTE>
  <SCROLL_UP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1143</LINE></SCROLL_UP>
  <FLASH_CURSOR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1152</LINE></FLASH_CURSOR>
  <NEXT_BLYTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1170</LINE></NEXT_BLYTE>
  <DONE_CLICK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1253</LINE></DONE_CLICK>
  <OTHER_WAY_IN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1266</LINE></OTHER_WAY_IN>
  <VDU_CHECK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1351</LINE></VDU_CHECK>
  <NO_QUEUE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1280</LINE></NO_QUEUE>
  <PROCESS_QUEUE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1448</LINE></PROCESS_QUEUE>
  <CONTROL1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1303</LINE></CONTROL1>
  <BS_DELETE1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1306</LINE></BS_DELETE1>
  <USER_DEF1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1309</LINE></USER_DEF1>
  <CONTROL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3614</LINE></CONTROL>
  <BS_DELETE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1334</LINE></BS_DELETE>
  <USER_DEF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1642</LINE></USER_DEF>
  <BACKSPACE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1312</LINE></BACKSPACE>
  <SKIP_23><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1319</LINE></SKIP_23>
  <SKIP_22><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1324</LINE></SKIP_22>
  <NOT_TOP_ROW><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1330</LINE></NOT_TOP_ROW>
  <DELETE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1337</LINE></DELETE>
  <NEXT_BOTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1344</LINE></NEXT_BOTE>
  <VDU_OFF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1356</LINE></VDU_OFF>
  <SET_UP_QUEUE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1440</LINE></SET_UP_QUEUE>
  <FINISH_PROCESS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1479</LINE></FINISH_PROCESS>
  <PROCESS_TEXT_COLOUR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1503</LINE></PROCESS_TEXT_COLOUR>
  <PROCESS_GRAPHIC_COLOUR1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1482</LINE></PROCESS_GRAPHIC_COLOUR1>
  <PROCESS_TAB><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1546</LINE></PROCESS_TAB>
  <PROCESS_MODE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1515</LINE></PROCESS_MODE>
  <PROCESS_DEFINE1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1500</LINE></PROCESS_DEFINE1>
  <PROCESS_GRAPHIC_WINDOW1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1485</LINE></PROCESS_GRAPHIC_WINDOW1>
  <PROCESS_PLOT1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1494</LINE></PROCESS_PLOT1>
  <FX_DECODE1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1497</LINE></FX_DECODE1>
  <PROCESS_TEXT_WINDOW1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1491</LINE></PROCESS_TEXT_WINDOW1>
  <PROCESS_GRAPHIC_ORIGIN1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1488</LINE></PROCESS_GRAPHIC_ORIGIN1>
  <PROCESS_GRAPHIC_COLOUR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1691</LINE></PROCESS_GRAPHIC_COLOUR>
  <PROCESS_GRAPHIC_WINDOW><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1725</LINE></PROCESS_GRAPHIC_WINDOW>
  <PROCESS_GRAPHIC_ORIGIN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1711</LINE></PROCESS_GRAPHIC_ORIGIN>
  <PROCESS_TEXT_WINDOW><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1573</LINE></PROCESS_TEXT_WINDOW>
  <PROCESS_PLOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1819</LINE></PROCESS_PLOT>
  <FX_DECODE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3363</LINE></FX_DECODE>
  <PROCESS_DEFINE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1619</LINE></PROCESS_DEFINE>
  <BLACK_BACK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1510</LINE></BLACK_BACK>
  <MODE_2><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1541</LINE></MODE_2>
  <MODE_0><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1537</LINE></MODE_0>
  <DUFF_TAB><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1568</LINE></DUFF_TAB>
  <WINDOW_DUFF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1612</LINE></WINDOW_DUFF>
  <RS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3880</LINE></RS>
  <SKIP_01><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1631</LINE></SKIP_01>
  <SKIP_02><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1634</LINE></SKIP_02>
  <SKIP_03><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1661</LINE></SKIP_03>
  <SKIP_04><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1664</LINE></SKIP_04>
  <NORMAL_USER_CHARS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1673</LINE></NORMAL_USER_CHARS>
  <USERDEF_OUT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1685</LINE></USERDEF_OUT>
  <GCOL_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1701</LINE></GCOL_DONE>
  <BACKGROUND_COLOUR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1704</LINE></BACKGROUND_COLOUR>
  <CONVERT_TO_PIXELS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3045</LINE></CONVERT_TO_PIXELS>
  <SKIP_50><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1733</LINE></SKIP_50>
  <SKIP_51><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1737</LINE></SKIP_51>
  <SKIP_52><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1747</LINE></SKIP_52>
  <SKIP_53><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1751</LINE></SKIP_53>
  <SKIP_54><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1761</LINE></SKIP_54>
  <SKIP_55><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1765</LINE></SKIP_55>
  <SKIP_56><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1770</LINE></SKIP_56>
  <SKIP_57><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1780</LINE></SKIP_57>
  <SKIP_58><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1784</LINE></SKIP_58>
  <SKIP_59><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1789</LINE></SKIP_59>
  <TEMPOUT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1794</LINE></TEMPOUT>
  <WAIT_1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1796</LINE></WAIT_1>
  <WAIT_2><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1801</LINE></WAIT_2>
  <WAIT_3><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1806</LINE></WAIT_3>
  <WAIT_4><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1811</LINE></WAIT_4>
  <ADD_X_OFFSET><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3017</LINE></ADD_X_OFFSET>
  <ADD_X_ORIGIN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3024</LINE></ADD_X_ORIGIN>
  <ADD_Y_OFFSET><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3031</LINE></ADD_Y_OFFSET>
  <ADD_Y_ORIGIN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3038</LINE></ADD_Y_ORIGIN>
  <WORK_OUT_PLOT_STYLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1875</LINE></WORK_OUT_PLOT_STYLE>
  <FINISH_PLOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2984</LINE></FINISH_PLOT>
  <PLOT_INVERTED><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1914</LINE></PLOT_INVERTED>
  <BACKGROUND_SETTINGS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1887</LINE></BACKGROUND_SETTINGS>
  <CHECK_COLOUR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1891</LINE></CHECK_COLOUR>
  <BLACK_CHOICES><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1903</LINE></BLACK_CHOICES>
  <PLOT_CLEAR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1919</LINE></PLOT_CLEAR>
  <PLOT_BLACK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1924</LINE></PLOT_BLACK>
  <PLOT_STYLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1928</LINE></PLOT_STYLE>
  <PLOT_TABLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1945</LINE></PLOT_TABLE>
  <SKIP_61><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1941</LINE></SKIP_61>
  <PLOT_LINE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2576</LINE></PLOT_LINE>
  <OMIT_FINAL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2570</LINE></OMIT_FINAL>
  <DOTTED_LINE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2574</LINE></DOTTED_LINE>
  <DOT_OMIT_FINAL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2568</LINE></DOT_OMIT_FINAL>
  <OMIT_INITIAL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2564</LINE></OMIT_INITIAL>
  <OMIT_BOTH><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2558</LINE></OMIT_BOTH>
  <DOT_OMIT_INITIAL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2562</LINE></DOT_OMIT_INITIAL>
  <DOT_OMIT_BOTH><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2556</LINE></DOT_OMIT_BOTH>
  <PLOT_POINT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2859</LINE></PLOT_POINT>
  <PLOT_RECTANGLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2878</LINE></PLOT_RECTANGLE>
  <PLOT_CIRCLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1985</LINE></PLOT_CIRCLE>
  <FILL_CIRCLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2285</LINE></FILL_CIRCLE>
  <LAST_CIRCLE_DOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1979</LINE></LAST_CIRCLE_DOT>
  <PLOT_CIRCLE_DOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2088</LINE></PLOT_CIRCLE_DOT>
  <INITIALISE_CIRCLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2501</LINE></INITIALISE_CIRCLE>
  <PLOT_FOUR_DOTS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2220</LINE></PLOT_FOUR_DOTS>
  <INTO_LOOP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2009</LINE></INTO_LOOP>
  <CIRCLE_LOOP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>1995</LINE></CIRCLE_LOOP>
  <PLOT_OTHER_DOTS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2153</LINE></PLOT_OTHER_DOTS>
  <SKIP_302><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2026</LINE></SKIP_302>
  <INCREASE_CIRCLE_Y><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2076</LINE></INCREASE_CIRCLE_Y>
  <INCREASE_CIRCLE_Y_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2084</LINE></INCREASE_CIRCLE_Y_DONE>
  <SKIP_301><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2108</LINE></SKIP_301>
  <SKIP_303><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2125</LINE></SKIP_303>
  <SKIP_304><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2139</LINE></SKIP_304>
  <SKIP_305><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2149</LINE></SKIP_305>
  <SKIP_306><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2173</LINE></SKIP_306>
  <SKIP_307><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2190</LINE></SKIP_307>
  <SKIP_308><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2204</LINE></SKIP_308>
  <SKIP_309><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2215</LINE></SKIP_309>
  <CIRCLE_DOT_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2217</LINE></CIRCLE_DOT_DONE>
  <SKIP_310><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2236</LINE></SKIP_310>
  <SKIP_311><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2251</LINE></SKIP_311>
  <SKIP_312><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2267</LINE></SKIP_312>
  <SKIP_313><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2281</LINE></SKIP_313>
  <FILL_MIDDLE_ONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2446</LINE></FILL_MIDDLE_ONE>
  <FILL_CIRCLE_LOOP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2290</LINE></FILL_CIRCLE_LOOP>
  <INTO_FILL_LOOP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2302</LINE></INTO_FILL_LOOP>
  <FINISH_FILL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2383</LINE></FINISH_FILL>
  <FILL_MIDDLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2481</LINE></FILL_MIDDLE>
  <SKIP_322><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2318</LINE></SKIP_322>
  <INCREASE_FILL_Y><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2372</LINE></INCREASE_FILL_Y>
  <FILL_SIDES><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2394</LINE></FILL_SIDES>
  <INCREASE_FILL_Y_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2380</LINE></INCREASE_FILL_Y_DONE>
  <VERTICAL_LINE_LOAD><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3058</LINE></VERTICAL_LINE_LOAD>
  <SKIP_300><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2531</LINE></SKIP_300>
  <mpy16u><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>4032</LINE></mpy16u>
  <WIND_LOAD><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3307</LINE></WIND_LOAD>
  <LINE_OK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2592</LINE></LINE_OK>
  <NEWX_MORE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2612</LINE></NEWX_MORE>
  <SKIP_201><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2611</LINE></SKIP_201>
  <NEWY_MORE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2635</LINE></NEWY_MORE>
  <SKIP_200><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2632</LINE></SKIP_200>
  <DX_MORE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2648</LINE></DX_MORE>
  <HORIZONTAL_QUADRANT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2699</LINE></HORIZONTAL_QUADRANT>
  <VERTICAL_QUADRANT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2653</LINE></VERTICAL_QUADRANT>
  <SWAP_PARAMETERS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2806</LINE></SWAP_PARAMETERS>
  <PLOT_FIRST_DOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2760</LINE></PLOT_FIRST_DOT>
  <V_U_NEXT_POINT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2665</LINE></V_U_NEXT_POINT>
  <SKIP_120><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2669</LINE></SKIP_120>
  <V_ERROR_POSITIVE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2686</LINE></V_ERROR_POSITIVE>
  <DECREASE_X><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2794</LINE></DECREASE_X>
  <INCREASE_X><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2787</LINE></INCREASE_X>
  <V_NOT_LAST_DOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2747</LINE></V_NOT_LAST_DOT>
  <LAST_DOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2753</LINE></LAST_DOT>
  <H_U_NEXT_POINT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2711</LINE></H_U_NEXT_POINT>
  <SKIP_100><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2715</LINE></SKIP_100>
  <ERROR_POSITIVE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2732</LINE></ERROR_POSITIVE>
  <DECREASE_Y><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2782</LINE></DECREASE_Y>
  <INCREASE_Y><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2775</LINE></INCREASE_Y>
  <NOT_LAST_DOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2741</LINE></NOT_LAST_DOT>
  <PLOT_NEXT_DOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2799</LINE></PLOT_NEXT_DOT>
  <H_U_POINT_OK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2768</LINE></H_U_POINT_OK>
  <SKIP_101><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2779</LINE></SKIP_101>
  <SKIP_121><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2791</LINE></SKIP_121>
  <POINT_OK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2868</LINE></POINT_OK>
  <RECT2_IN_WINDOW><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2906</LINE></RECT2_IN_WINDOW>
  <RECTANGLE_OK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2918</LINE></RECTANGLE_OK>
  <RECT1_IN_WINDOW><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2943</LINE></RECT1_IN_WINDOW>
  <X_OK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2952</LINE></X_OK>
  <Y_OK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2961</LINE></Y_OK>
  <FILL_SAFE_RECTANGLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2967</LINE></FILL_SAFE_RECTANGLE>
  <NEXT_RECTANGLE_SLICE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>2973</LINE></NEXT_RECTANGLE_SLICE>
  <VPLOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3129</LINE></VPLOT>
  <VERTICAL_LINE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3067</LINE></VERTICAL_LINE>
  <IN_WINDOW_TOO><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3088</LINE></IN_WINDOW_TOO>
  <IN_WINDOW><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3116</LINE></IN_WINDOW>
  <SKIP_77><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3126</LINE></SKIP_77>
  <QUICK_IN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3138</LINE></QUICK_IN>
  <NEXT_PIXEL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3151</LINE></NEXT_PIXEL>
  <NEXT_GRAPHIC_BYTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3158</LINE></NEXT_GRAPHIC_BYTE>
  <V_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3170</LINE></V_DONE>
  <SET_PAGE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3232</LINE></SET_PAGE>
  <SET_BYTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3246</LINE></SET_BYTE>
  <MASKING_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3216</LINE></MASKING_DONE>
  <GADDR_LOAD><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3257</LINE></GADDR_LOAD>
  <SKIP_68><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3279</LINE></SKIP_68>
  <WIND_LEFT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3330</LINE></WIND_LEFT>
  <WIND_RIGHT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3328</LINE></WIND_RIGHT>
  <TEST_VERTICAL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3333</LINE></TEST_VERTICAL>
  <WIND_BELOW><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3346</LINE></WIND_BELOW>
  <WIND_ABOVE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3344</LINE></WIND_ABOVE>
  <VERTICAL_OK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3349</LINE></VERTICAL_OK>
  <EIGABS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3355</LINE></EIGABS>
  <EIG><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3358</LINE></EIG>
  <FX_ZERO><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3413</LINE></FX_ZERO>
  <READ_TAB><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3434</LINE></READ_TAB>
  <CHARACTER_COMPARE1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3454</LINE></CHARACTER_COMPARE1>
  <STAR_TV1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3399</LINE></STAR_TV1>
  <CHANGE_CURSOR1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3403</LINE></CHANGE_CURSOR1>
  <READ_PALETTE1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3401</LINE></READ_PALETTE1>
  <READ_EEPROM1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3407</LINE></READ_EEPROM1>
  <WRITE_EEPROM1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3409</LINE></WRITE_EEPROM1>
  <CHANGE_CHAR_WIDTH><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3469</LINE></CHANGE_CHAR_WIDTH>
  <CHANGE_LINE_COUNT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3463</LINE></CHANGE_LINE_COUNT>
  <COUNTRY_FLAG><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3459</LINE></COUNTRY_FLAG>
  <CHANGE_USER_FLAG1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3405</LINE></CHANGE_USER_FLAG1>
  <FX_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3395</LINE></FX_DONE>
  <STAR_TV><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3519</LINE></STAR_TV>
  <READ_PALETTE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3504</LINE></READ_PALETTE>
  <CHANGE_CURSOR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3497</LINE></CHANGE_CURSOR>
  <CHANGE_USER_FLAG><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3513</LINE></CHANGE_USER_FLAG>
  <READ_EEPROM><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3484</LINE></READ_EEPROM>
  <WRITE_EEPROM><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3490</LINE></WRITE_EEPROM>
  <NO_RESET><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3417</LINE></NO_RESET>
  <SKIP_09><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3422</LINE></SKIP_09>
  <EEPROM_read><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3977</LINE></EEPROM_read>
  <SKIP_08><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3428</LINE></SKIP_08>
  <SKIP_06><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3445</LINE></SKIP_06>
  <SKIP_05><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3447</LINE></SKIP_05>
  <CHARACTER_COMPARE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3533</LINE></CHARACTER_COMPARE>
  <FX_CHANGE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3528</LINE></FX_CHANGE>
  <NEW_WIDTH_OK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3478</LINE></NEW_WIDTH_OK>
  <EEPROM_write><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3988</LINE></EEPROM_write>
  <SKIP_07><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3507</LINE></SKIP_07>
  <NEXT_CHARACTER><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3545</LINE></NEXT_CHARACTER>
  <NEXT_COMPARE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3550</LINE></NEXT_COMPARE>
  <SKIP_40><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3556</LINE></SKIP_40>
  <SKIP_42><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3561</LINE></SKIP_42>
  <FOUND><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3601</LINE></FOUND>
  <NEXT_USER_CHARACTER><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3574</LINE></NEXT_USER_CHARACTER>
  <NEXT_USER_COMPARE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3579</LINE></NEXT_USER_COMPARE>
  <SKIP_41><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3585</LINE></SKIP_41>
  <SKIP_43><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3590</LINE></SKIP_43>
  <SKIP_9><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3604</LINE></SKIP_9>
  <CONTROL_TABLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3627</LINE></CONTROL_TABLE>
  <SKIP_26><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3622</LINE></SKIP_26>
  <NUL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3663</LINE></NUL>
  <SOH><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3666</LINE></SOH>
  <STX><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3671</LINE></STX>
  <ETX><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3675</LINE></ETX>
  <EOT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3679</LINE></EOT>
  <ENQ><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3685</LINE></ENQ>
  <ACK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3693</LINE></ACK>
  <BEL><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3697</LINE></BEL>
  <BS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3700</LINE></BS>
  <HT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3704</LINE></HT>
  <LF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3721</LINE></LF>
  <VT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3736</LINE></VT>
  <FF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3752</LINE></FF>
  <CR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3757</LINE></CR>
  <SO><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3768</LINE></SO>
  <SI><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3772</LINE></SI>
  <DLE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3776</LINE></DLE>
  <DC1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3806</LINE></DC1>
  <DC2><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3811</LINE></DC2>
  <DC3><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3816</LINE></DC3>
  <DC4><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3821</LINE></DC4>
  <NAK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3835</LINE></NAK>
  <SYN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3839</LINE></SYN>
  <ETB><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3845</LINE></ETB>
  <CAN><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3850</LINE></CAN>
  <EM><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3855</LINE></EM>
  <SUB_><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3860</LINE></SUB_>
  <ESC><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3864</LINE></ESC>
  <FS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3869</LINE></FS>
  <GS><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3875</LINE></GS>
  <US><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3887</LINE></US>
  <GRAPHIC_HT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3717</LINE></GRAPHIC_HT>
  <HT_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3714</LINE></HT_DONE>
  <GRAPHIC_LF><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3732</LINE></GRAPHIC_LF>
  <LF_DONE><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3729</LINE></LF_DONE>
  <GRAPHIC_VT><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3748</LINE></GRAPHIC_VT>
  <AT_TOP><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3744</LINE></AT_TOP>
  <GRAPHIC_CR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3764</LINE></GRAPHIC_CR>
  <CLEAR_TO_BLACK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3787</LINE></CLEAR_TO_BLACK>
  <CLG><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3791</LINE></CLG>
  <COLBACK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3900</LINE></COLBACK>
  <ROWBACK><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3903</LINE></ROWBACK>
  <PRINT_CHAR><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>3972</LINE></PRINT_CHAR>
  <m16u_1><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>4038</LINE></m16u_1>
  <noad8><FILE>C:\Documents and Settings\Neil.LATITUDE\My Documents\Model Engineering\Electronics\code\computer\computer.asm</FILE><LINE>4041</LINE></noad8>
 </LABELS>
</ASSEMBLER_INFO>
