Imports Microsoft.VisualBasic
Imports System

Namespace DeveloperTerminal
	Public Class XMLData
		#Region "COM port parameters"

		Public COMPort As String = "Not Initialized"
		Public Baud As Integer = 0
		Public Databits As Integer = 0
		Public Parity As String = "Not Initialized"
		Public Stopbits As String = "Not Initialized"
		Public Handshake As String = "Not Initialized"

		#End Region

		#Region "Terminal Characters"
		Public TerminalCharacters As String = ""
		#End Region

		#Region "Initialize Macros"

		' Initialize the Macro text
		Public MacroText1 As String = " "
		Public MacroText2 As String = " "
		Public MacroText3 As String = " "
		Public MacroText4 As String = " "
		Public MacroText5 As String = " "
		Public MacroText6 As String = " "
		Public MacroText7 As String = " "
		Public MacroText8 As String = " "
		Public MacroText9 As String = " "
		Public MacroText10 As String = " "
		Public MacroText11 As String = " "
		Public MacroText12 As String = " "
		Public MacroText13 As String = " "
		Public MacroText14 As String = " "
		Public MacroText15 As String = " "
		Public MacroText16 As String = " "
		Public MacroText17 As String = " "
		Public MacroText18 As String = " "
		Public MacroText19 As String = " "
		Public MacroText20 As String = " "
		Public MacroText21 As String = " "
		Public MacroText22 As String = " "
		Public MacroText23 As String = " "
		Public MacroText24 As String = " "
		Public MacroText25 As String = " "
		Public MacroText26 As String = " "
		Public MacroText27 As String = " "
		Public MacroText28 As String = " "
		Public MacroText29 As String = " "
		Public MacroText30 As String = " "
		Public MacroText31 As String = " "
		Public MacroText32 As String = " "
		Public MacroText33 As String = " "
		Public MacroText34 As String = " "
		Public MacroText35 As String = " "
		Public MacroText36 As String = " "
		Public MacroText37 As String = " "
		Public MacroText38 As String = " "
		Public MacroText39 As String = " "
		Public MacroText40 As String = " "
		Public MacroText41 As String = " "
		Public MacroText42 As String = " "
		Public MacroText43 As String = " "
		Public MacroText44 As String = " "
		Public MacroText45 As String = " "
		Public MacroText46 As String = " "
		Public MacroText47 As String = " "
		Public MacroText48 As String = " "
		Public MacroText49 As String = " "
		Public MacroText50 As String = " "
		Public MacroText51 As String = " "
		Public MacroText52 As String = " "

		' Initialize the Macro Data
		Public MacroData1 As String = " "
		Public MacroData2 As String = " "
		Public MacroData3 As String = " "
		Public MacroData4 As String = " "
		Public MacroData5 As String = " "
		Public MacroData6 As String = " "
		Public MacroData7 As String = " "
		Public MacroData8 As String = " "

		Public MacroData9 As String = " "
		Public MacroData10 As String = " "
		Public MacroData11 As String = " "
		Public MacroData12 As String = " "
		Public MacroData13 As String = " "
		Public MacroData14 As String = " "
		Public MacroData15 As String = " "
		Public MacroData16 As String = " "
		Public MacroData17 As String = " "
		Public MacroData18 As String = " "
		Public MacroData19 As String = " "
		Public MacroData20 As String = " "
		Public MacroData21 As String = " "
		Public MacroData22 As String = " "
		Public MacroData23 As String = " "
		Public MacroData24 As String = " "
		Public MacroData25 As String = " "
		Public MacroData26 As String = " "
		Public MacroData27 As String = " "
		Public MacroData28 As String = " "
		Public MacroData29 As String = " "
		Public MacroData30 As String = " "
		Public MacroData31 As String = " "
		Public MacroData32 As String = " "
		Public MacroData33 As String = " "
		Public MacroData34 As String = " "
		Public MacroData35 As String = " "
		Public MacroData36 As String = " "
		Public MacroData37 As String = " "
		Public MacroData38 As String = " "
		Public MacroData39 As String = " "
		Public MacroData40 As String = " "
		Public MacroData41 As String = " "
		Public MacroData42 As String = " "
		Public MacroData43 As String = " "
		Public MacroData44 As String = " "
		Public MacroData45 As String = " "
		Public MacroData46 As String = " "
		Public MacroData47 As String = " "
		Public MacroData48 As String = " "
		Public MacroData49 As String = " "
		Public MacroData50 As String = " "
		Public MacroData51 As String = " "
		Public MacroData52 As String = " "

		' Initialize the Macro Type
		Public MacroType1 As String = " "
		Public MacroType2 As String = " "
		Public MacroType3 As String = " "
		Public MacroType4 As String = " "
		Public MacroType5 As String = " "
		Public MacroType6 As String = " "
		Public MacroType7 As String = " "
		Public MacroType8 As String = " "
		Public MacroType9 As String = " "
		Public MacroType10 As String = " "
		Public MacroType11 As String = " "
		Public MacroType12 As String = " "
		Public MacroType13 As String = " "
		Public MacroType14 As String = " "
		Public MacroType15 As String = " "
		Public MacroType16 As String = " "
		Public MacroType17 As String = " "
		Public MacroType18 As String = " "
		Public MacroType19 As String = " "
		Public MacroType20 As String = " "
		Public MacroType21 As String = " "
		Public MacroType22 As String = " "
		Public MacroType23 As String = " "
		Public MacroType24 As String = " "
		Public MacroType25 As String = " "
		Public MacroType26 As String = " "
		Public MacroType27 As String = " "
		Public MacroType28 As String = " "
		Public MacroType29 As String = " "
		Public MacroType30 As String = " "
		Public MacroType31 As String = " "
		Public MacroType32 As String = " "
		Public MacroType33 As String = " "
		Public MacroType34 As String = " "
		Public MacroType35 As String = " "
		Public MacroType36 As String = " "
		Public MacroType37 As String = " "
		Public MacroType38 As String = " "
		Public MacroType39 As String = " "
		Public MacroType40 As String = " "
		Public MacroType41 As String = " "
		Public MacroType42 As String = " "
		Public MacroType43 As String = " "
		Public MacroType44 As String = " "
		Public MacroType45 As String = " "
		Public MacroType46 As String = " "
		Public MacroType47 As String = " "
		Public MacroType48 As String = " "
		Public MacroType49 As String = " "
		Public MacroType50 As String = " "
		Public MacroType51 As String = " "
		Public MacroType52 As String = " "

		#End Region
	End Class
End Namespace
