.TH "__gui_base_struct" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gui_base_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fooey.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusLeft\fP"
.br
.RI "\fIDefine the position and size of a control. \fP"
.ti -1c
.RI "USHORT \fBusTop\fP"
.br
.ti -1c
.RI "USHORT \fBusRight\fP"
.br
.ti -1c
.RI "USHORT \fBusBottom\fP"
.br
.ti -1c
.RI "USHORT \fBusCtrlID\fP"
.br
.RI "\fIDefine a unique ID for each control. \fP"
.ti -1c
.RI "UCHAR \fBucGroup\fP"
.br
.RI "\fIDepth grouping. \fP"
.ti -1c
.RI "UCHAR \fBeType\fP"
.br
.RI "\fIDefine the behaviour of the control when specialized. \fP"
.ti -1c
.RI "BOOL \fBbRedraw\fP"
.br
.RI "\fIWhether or not the target needs to be redrawn. \fP"
.ti -1c
.RI "BOOL \fBbHasFocus\fP"
.br
.RI "\fIWhether or not this is the active control. \fP"
.ti -1c
.RI "\fBWIDGET_INIT\fP \fBpfInit\fP"
.br
.RI "\fIInitializer function. \fP"
.ti -1c
.RI "\fBWIDGET_DRAW\fP \fBpfDraw\fP"
.br
.RI "\fIFunction to render the control. \fP"
.ti -1c
.RI "\fBWIDGET_CONTROL\fP \fBpfControl\fP"
.br
.RI "\fIEvent handler for the control (universal input behaviour). \fP"
.ti -1c
.RI "\fBWIDGET_DESTROY\fP \fBpfDestroy\fP"
.br
.RI "\fIDestructor function. \fP"
.ti -1c
.RI "void * \fBpstOwner\fP"
.br
.RI "\fIPointer back to the GUI manager. \fP"
.ti -1c
.RI "struct \fB__gui_base_struct\fP * \fBpstParent\fP"
.br
.RI "\fIpointer to the direct parent \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "BOOL \fBbHasFocus\fP"
.PP
Whether or not this is the active control. 
.SS "BOOL \fBbRedraw\fP"
.PP
Whether or not the target needs to be redrawn. 
.SS "UCHAR \fBeType\fP"
.PP
Define the behaviour of the control when specialized. 
.SS "\fBWIDGET_CONTROL\fP \fBpfControl\fP"
.PP
Event handler for the control (universal input behaviour). 
.SS "\fBWIDGET_DESTROY\fP \fBpfDestroy\fP"
.PP
Destructor function. 
.SS "\fBWIDGET_DRAW\fP \fBpfDraw\fP"
.PP
Function to render the control. 
.SS "\fBWIDGET_INIT\fP \fBpfInit\fP"
.PP
Initializer function. 
.SS "void* \fBpstOwner\fP"
.PP
Pointer back to the GUI manager. 
.SS "struct \fB__gui_base_struct\fP* \fBpstParent\fP"
.PP
pointer to the direct parent 
.SS "UCHAR \fBucGroup\fP"
.PP
Depth grouping. 
.SS "USHORT \fBusBottom\fP"
.SS "USHORT \fBusCtrlID\fP"
.PP
Define a unique ID for each control. 
.SS "USHORT \fBusLeft\fP"
.PP
Define the position and size of a control. 
.SS "USHORT \fBusRight\fP"
.SS "USHORT \fBusTop\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
