.TH "_Plumb_Struct" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Plumb_Struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <plumber.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "UCHAR \fBaucData\fP [PIPE_SIZE]"
.br
.RI "\fISize of the pipe (in bytes). \fP"
.ti -1c
.RI "UCHAR \fBucLen\fP"
.br
.RI "\fILength of the data in the pipe. \fP"
.ti -1c
.RI "BOOL \fBbInUse\fP"
.br
.RI "\fIIs the pipe in use. \fP"
.ti -1c
.RI "struct \fB_Plumb_Struct\fP * \fBpstNext\fP"
.br
.RI "\fIThe next pipe in the list. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "UCHAR \fBaucData\fP[PIPE_SIZE]"
.PP
Size of the pipe (in bytes). 
.SS "BOOL \fBbInUse\fP"
.PP
Is the pipe in use. 
.SS "struct \fB_Plumb_Struct\fP* \fBpstNext\fP"
.PP
The next pipe in the list. 
.SS "UCHAR \fBucLen\fP"
.PP
Length of the data in the pipe. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
