.TH "_Task_Struct" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Task_Struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pipsqueak.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "WORD * \fBpwStack\fP"
.br
.RI "\fIPointer to the task's stack. \fP"
.ti -1c
.RI "USHORT \fBusStackSize\fP"
.br
.RI "\fISize of the stack (in minimum address units). \fP"
.ti -1c
.RI "USHORT \fBusTicks\fP"
.br
.RI "\fIMaximum number of ticks to execute before switching to the next task. \fP"
.ti -1c
.RI "\fBTASK_FUNC\fP \fBpfHandler\fP"
.br
.RI "\fITask's handler function pointer. \fP"
.ti -1c
.RI "struct \fB_Task_Struct\fP * \fBpstNext\fP"
.br
.RI "\fIPointer to the next task in the list (automatically handled by Task_AddTask). \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBTASK_FUNC\fP \fBpfHandler\fP"
.PP
Task's handler function pointer. 
.SS "struct \fB_Task_Struct\fP* \fBpstNext\fP"
.PP
Pointer to the next task in the list (automatically handled by Task_AddTask). 
.SS "WORD* \fBpwStack\fP"
.PP
Pointer to the task's stack. 
.SS "USHORT \fBusStackSize\fP"
.PP
Size of the stack (in minimum address units). 
.SS "USHORT \fBusTicks\fP"
.PP
Maximum number of ticks to execute before switching to the next task. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
