.TH "C:/Projects/R3/graphics/colorspace.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/graphics/colorspace.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDRAW_COLOR_24BIT\fP   0"
.br
.ti -1c
.RI "#define \fBDRAW_COLOR_16BIT\fP   1"
.br
.ti -1c
.RI "#define \fBDRAW_COLOR_8BIT\fP   0"
.br
.ti -1c
.RI "#define \fBDRAW_COLOR_1BIT\fP   0"
.br
.ti -1c
.RI "#define \fBCOLOR\fP   USHORT"
.br
.ti -1c
.RI "#define \fBMAX_RED\fP   (0x001F)"
.br
.ti -1c
.RI "#define \fBMAX_GREEN\fP   (0x003F)"
.br
.ti -1c
.RI "#define \fBMAX_BLUE\fP   (0x001F)"
.br
.ti -1c
.RI "#define \fBMASK_RED\fP(R)   (((USHORT)R & 0x001F) << 11)"
.br
.ti -1c
.RI "#define \fBMASK_BLUE\fP(B)   ((USHORT)B & 0x001F)"
.br
.ti -1c
.RI "#define \fBMASK_GREEN\fP(G)   (((USHORT)G & 0x003F) << 5)"
.br
.ti -1c
.RI "#define \fBRGB_COLOR\fP(R, G, B)   ( MASK_BLUE(B) | MASK_GREEN(G) | MASK_RED(R) )"
.br
.ti -1c
.RI "#define \fBBYTES_PER_PIXEL\fP   (2)"
.br
.ti -1c
.RI "#define \fBCOLOR_RED\fP   RGB_COLOR(MAX_RED, 		0, 				0)"
.br
.ti -1c
.RI "#define \fBCOLOR_BLUE\fP   RGB_COLOR(0, 			0, 				MAX_BLUE)"
.br
.ti -1c
.RI "#define \fBCOLOR_GREEN\fP   RGB_COLOR(0, 			MAX_GREEN,		0)"
.br
.ti -1c
.RI "#define \fBCOLOR_YELLOW\fP   RGB_COLOR(MAX_RED,		MAX_GREEN,		0)"
.br
.ti -1c
.RI "#define \fBCOLOR_WHITE\fP   RGB_COLOR(MAX_RED,		MAX_GREEN,		MAX_BLUE)"
.br
.ti -1c
.RI "#define \fBCOLOR_BLACK\fP   RGB_COLOR(0,			0,				0)"
.br
.ti -1c
.RI "#define \fBCOLOR_GREY75\fP   RGB_COLOR(MAX_RED*3/4,	MAX_GREEN*3/4,	MAX_BLUE*3/4)"
.br
.ti -1c
.RI "#define \fBCOLOR_GREY50\fP   RGB_COLOR(MAX_RED/2,	MAX_GREEN/2,	MAX_BLUE/2)"
.br
.ti -1c
.RI "#define \fBCOLOR_GREY25\fP   RGB_COLOR(MAX_RED/4,	MAX_GREEN/4,	MAX_BLUE/4)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Color space definitions, color definition macros, and common colors 
.SH "Define Documentation"
.PP 
.SS "#define BYTES_PER_PIXEL   (2)"
.SS "#define COLOR   USHORT"
.SS "#define COLOR_BLACK   RGB_COLOR(0,			0,				0)"
.SS "#define COLOR_BLUE   RGB_COLOR(0, 			0, 				MAX_BLUE)"
.SS "#define COLOR_GREEN   RGB_COLOR(0, 			MAX_GREEN,		0)"
.SS "#define COLOR_GREY25   RGB_COLOR(MAX_RED/4,	MAX_GREEN/4,	MAX_BLUE/4)"
.SS "#define COLOR_GREY50   RGB_COLOR(MAX_RED/2,	MAX_GREEN/2,	MAX_BLUE/2)"
.SS "#define COLOR_GREY75   RGB_COLOR(MAX_RED*3/4,	MAX_GREEN*3/4,	MAX_BLUE*3/4)"
.SS "#define COLOR_RED   RGB_COLOR(MAX_RED, 		0, 				0)"
.SS "#define COLOR_WHITE   RGB_COLOR(MAX_RED,		MAX_GREEN,		MAX_BLUE)"
.SS "#define COLOR_YELLOW   RGB_COLOR(MAX_RED,		MAX_GREEN,		0)"
.SS "#define DRAW_COLOR_16BIT   1"
.SS "#define DRAW_COLOR_1BIT   0"
.SS "#define DRAW_COLOR_24BIT   0"
.SS "#define DRAW_COLOR_8BIT   0"
.SS "#define MASK_BLUE(B)   ((USHORT)B & 0x001F)"
.SS "#define MASK_GREEN(G)   (((USHORT)G & 0x003F) << 5)"
.SS "#define MASK_RED(R)   (((USHORT)R & 0x001F) << 11)"
.SS "#define MAX_BLUE   (0x001F)"
.SS "#define MAX_GREEN   (0x003F)"
.SS "#define MAX_RED   (0x001F)"
.SS "#define RGB_COLOR(R, G, B)   ( MASK_BLUE(B) | MASK_GREEN(G) | MASK_RED(R) )"
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
