.TH "DISPLAY_DRIVER_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DISPLAY_DRIVER_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <display.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDRIVER_STRUCT\fP * \fBpstDriver\fP"
.br
.ti -1c
.RI "USHORT \fBusResX\fP"
.br
.ti -1c
.RI "USHORT \fBusResY\fP"
.br
.ti -1c
.RI "UCHAR \fBucBPP\fP"
.br
.ti -1c
.RI "USHORT \fBusAccelerationFlags\fP"
.br
.ti -1c
.RI "\fBDRAW_PIXEL_FUNC\fP \fBpfDrawPixel\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDRAW_PIXEL_FUNC\fP \fBpfDrawPixel\fP"
.SS "\fBDRIVER_STRUCT\fP* \fBpstDriver\fP"
.SS "UCHAR \fBucBPP\fP"
.SS "USHORT \fBusAccelerationFlags\fP"
.SS "USHORT \fBusResX\fP"
.SS "USHORT \fBusResY\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
