.TH "C:/Projects/R3/graphics/display.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/graphics/display.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'driver.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBDISPLAY_DRIVER_STRUCT\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBACCELERATED_CLEAR\fP   (0x0001)"
.br
.ti -1c
.RI "#define \fBACCELERATED_POINT\fP   (0x0002)"
.br
.ti -1c
.RI "#define \fBACCELERATED_LINE\fP   (0x0004)"
.br
.ti -1c
.RI "#define \fBACCELERATED_CIRCLE\fP   (0x0008)"
.br
.ti -1c
.RI "#define \fBACCELERATED_ELLPISE\fP   (0x0010)"
.br
.ti -1c
.RI "#define \fBACCELERATED_RECTANGLE\fP   (0x0020)"
.br
.ti -1c
.RI "#define \fBACCELERATED_TEXT\fP   (0x0040)"
.br
.ti -1c
.RI "#define \fBACCELERATED_CONSOLE_TEXT\fP   (0x0080)"
.br
.ti -1c
.RI "#define \fBACCELERATED_STAMP\fP   (0x0100)"
.br
.ti -1c
.RI "#define \fBACCELERATED_BITMAP\fP   (0x0200)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBDRAW_PIXEL_FUNC\fP )(void *pstThis_, void *pstPixel_)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDISPLAY_EVENT\fP { \fBDISPLAY_EVENT_PIXEL\fP =  DRIVER_EVENTS, \fBDISPLAY_EVENT_CLEAR\fP, \fBDISPLAY_EVENT_LINE\fP, \fBDISPLAY_EVENT_RECTANGLE\fP, \fBDISPLAY_EVENT_CIRCLE\fP, \fBDISPLAY_EVENT_ELLIPSE\fP, \fBDISPLAY_EVENT_BITMAP\fP, \fBDISPLAY_EVENT_STAMP\fP, \fBDISPLAY_EVENT_TEXT\fP, \fBDISPLAY_EVENT_CONSOLE_TEXT\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Display driver type - used as a bridge between the display hardware itself and the hardware abstraction layer. 
.SH "Define Documentation"
.PP 
.SS "#define ACCELERATED_BITMAP   (0x0200)"
.SS "#define ACCELERATED_CIRCLE   (0x0008)"
.SS "#define ACCELERATED_CLEAR   (0x0001)"
.SS "#define ACCELERATED_CONSOLE_TEXT   (0x0080)"
.SS "#define ACCELERATED_ELLPISE   (0x0010)"
.SS "#define ACCELERATED_LINE   (0x0004)"
.SS "#define ACCELERATED_POINT   (0x0002)"
.SS "#define ACCELERATED_RECTANGLE   (0x0020)"
.SS "#define ACCELERATED_STAMP   (0x0100)"
.SS "#define ACCELERATED_TEXT   (0x0040)"
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* \fBDRAW_PIXEL_FUNC\fP)(void *pstThis_, void *pstPixel_)"
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDISPLAY_EVENT\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIDISPLAY_EVENT_PIXEL \fP\fP
.TP
\fB\fIDISPLAY_EVENT_CLEAR \fP\fP
.TP
\fB\fIDISPLAY_EVENT_LINE \fP\fP
.TP
\fB\fIDISPLAY_EVENT_RECTANGLE \fP\fP
.TP
\fB\fIDISPLAY_EVENT_CIRCLE \fP\fP
.TP
\fB\fIDISPLAY_EVENT_ELLIPSE \fP\fP
.TP
\fB\fIDISPLAY_EVENT_BITMAP \fP\fP
.TP
\fB\fIDISPLAY_EVENT_STAMP \fP\fP
.TP
\fB\fIDISPLAY_EVENT_TEXT \fP\fP
.TP
\fB\fIDISPLAY_EVENT_CONSOLE_TEXT \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
