.TH "DRAW_RECTANGLE_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DRAW_RECTANGLE_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <draw.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusLeft\fP"
.br
.ti -1c
.RI "USHORT \fBusTop\fP"
.br
.ti -1c
.RI "USHORT \fBusRight\fP"
.br
.ti -1c
.RI "USHORT \fBusBottom\fP"
.br
.ti -1c
.RI "COLOR \fBuLineColor\fP"
.br
.ti -1c
.RI "BOOL \fBbFill\fP"
.br
.ti -1c
.RI "COLOR \fBuFillColor\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "BOOL \fBbFill\fP"
.SS "COLOR \fBuFillColor\fP"
.SS "COLOR \fBuLineColor\fP"
.SS "USHORT \fBusBottom\fP"
.SS "USHORT \fBusLeft\fP"
.SS "USHORT \fBusRight\fP"
.SS "USHORT \fBusTop\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
