.TH "DRAW_LINE_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DRAW_LINE_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <draw.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusX1\fP"
.br
.ti -1c
.RI "USHORT \fBusX2\fP"
.br
.ti -1c
.RI "USHORT \fBusY1\fP"
.br
.ti -1c
.RI "USHORT \fBusY2\fP"
.br
.ti -1c
.RI "COLOR \fBuColor\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "COLOR \fBuColor\fP"
.SS "USHORT \fBusX1\fP"
.SS "USHORT \fBusX2\fP"
.SS "USHORT \fBusY1\fP"
.SS "USHORT \fBusY2\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
