.TH "C:/Projects/R3/kernel/driver.c" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel/driver.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'driver.h'\fP
.br
\fC#include 'taskport.h'\fP
.br
\fC#include 'mutex.h'\fP
.br
\fC#include 'kernelcfg.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDriver_Init\fP (\fBDRIVER_STRUCT\fP *pstDriver_)"
.br
.ti -1c
.RI "void \fBDriver_Start\fP (\fBDRIVER_STRUCT\fP *pstDriver_)"
.br
.ti -1c
.RI "void \fBDriver_Stop\fP (\fBDRIVER_STRUCT\fP *pstDriver_)"
.br
.ti -1c
.RI "void \fBDriver_RemoveControlFunc\fP (\fBDRIVER_STRUCT\fP *pstDriver_)"
.br
.ti -1c
.RI "void \fBDriver_AddControlFunc\fP (\fBDRIVER_STRUCT\fP *pstDriver_, void *pfDriverControl_)"
.br
.ti -1c
.RI "UCHAR \fBDriver_Control\fP (\fBDRIVER_STRUCT\fP *pstDriver_, USHORT usID_, void *pvData_)"
.br
.ti -1c
.RI "USHORT \fBDriver_Read\fP (\fBDRIVER_STRUCT\fP *pstDriver_, UCHAR *pucData_, USHORT usLen_)"
.br
.ti -1c
.RI "USHORT \fBDriver_Write\fP (\fBDRIVER_STRUCT\fP *pstDriver_, UCHAR *pucData_, USHORT usLen_)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Driver_AddControlFunc (\fBDRIVER_STRUCT\fP * pstDriver_, void * pfDriverControl_)"Set the control/event handler for the driver in question.
.PP
\fBParameters:\fP
.RS 4
\fIpstDriver_\fP - pointer to the driver 
.br
\fIpfDriverControl_\fP - pointer to the control function 
.RE
.PP

.SS "\fBDRIVER_RETURN\fP Driver_Control (\fBDRIVER_STRUCT\fP * pstDriver_, USHORT usID_, void * pvData_)"Calls the driver event handler from a given task with event type specified in the event ID field, and data passed in through the void * parameter field.
.PP
\fBParameters:\fP
.RS 4
\fIpstDriver_\fP - Pointer to the driver struct 
.br
\fIusID_\fP - Event ID 
.br
\fIpvData_\fP - Pointer to the event data. 
.RE
.PP

.SS "void Driver_Init (\fBDRIVER_STRUCT\fP * pstDriver_)"File: \fBDriver.c\fP
.PP
Description: This module implements the driver-level abstraction for FunkOS. All managed driver access is handled through this module.
.PP
Usage: Drivers are initialized with Driver_Init, started using Driver_Start, and stopped using Driver_Stop. These functions abstract the calls to the Init/Start/Stop functions specified in the \fBDRIVER_STRUCT\fP pointer corresponding to the driver. When a control event is triggered by an interrupt or by application code, the event is passed through the event handler in the driver for processing. In this way, all drivers are accessed consistently.
.PP
Calls the driver's initialization function and sets the driver state.
.PP
\fBParameters:\fP
.RS 4
\fIpstDriver_\fP - Pointer to the driver 
.RE
.PP

.SS "void Driver_Read (\fBDRIVER_STRUCT\fP * pstDriver_, UCHAR * pucData_, USHORT usLen_)"Use the driver's dedicated read function to read a specified amount of data from the driver's stream.
.PP
\fBParameters:\fP
.RS 4
\fIpstDriver_\fP - pointer to the task's driver 
.br
\fIpucData_\fP - pointer to the input data stream 
.br
\fIusLen_\fP - number of bytes to read from the stream. 
.RE
.PP
\fBReturns:\fP
.RS 4
USHORT - the number of bytes actually read from the stream 
.RE
.PP

.SS "void Driver_RemoveControlFunc (\fBDRIVER_STRUCT\fP * pstDriver_)"Remove the control function for the driver
.PP
\fBParameters:\fP
.RS 4
\fIpstDriver_\fP - driver to remove the event handler from 
.RE
.PP

.SS "void Driver_Start (\fBDRIVER_STRUCT\fP * pstDriver_)"Calls the driver's start function and sets the driver to the active state
.PP
\fBParameters:\fP
.RS 4
\fIpstDriver_\fP - pointer to the driver to start 
.RE
.PP

.SS "void Driver_Stop (\fBDRIVER_STRUCT\fP * pstDriver_)"Stop the driver and set to the idle state
.PP
\fBParameters:\fP
.RS 4
\fIpstDriver_\fP - driver to stop 
.RE
.PP

.SS "void Driver_Write (\fBDRIVER_STRUCT\fP * pstDriver_, UCHAR * pucData_, USHORT usLen_)"Use the driver's dedicated read function to write a specified amount of data to the driver's stream.
.PP
\fBParameters:\fP
.RS 4
\fIpstDriver_\fP - pointer to the task's driver 
.br
\fIpucData_\fP - pointer to data to write 
.br
\fIusLen_\fP - number of bytes to write to the stream. 
.RE
.PP
\fBReturns:\fP
.RS 4
USHORT - the number of bytes actually written to the stream 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
