.TH "EVENT_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EVENT_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <message.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusEventID\fP"
.br
.RI "\fIEvent ID for the message. \fP"
.ti -1c
.RI "USHORT \fBusEventData\fP"
.br
.RI "\fIEvent Data for the message. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Event item - contains an ID and an data field 
.SH "Field Documentation"
.PP 
.SS "USHORT \fBusEventData\fP"
.PP
Event Data for the message. 
.SS "USHORT \fBusEventID\fP"
.PP
Event ID for the message. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
