.TH "C:/Projects/R3/graphics/font.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/graphics/font.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'font_port.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFONT_STRUCT\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFONT_PRINTABLE_CHARS\fP   (256)"
.br
.ti -1c
.RI "#define \fBFONT_ASCII_OFFSET\fP   (0)"
.br
.ti -1c
.RI "#define \fBFONT_FLAG_NORMAL\fP   (0x00)"
.br
.ti -1c
.RI "#define \fBFONT_FLAG_BOLD\fP   (0x01)"
.br
.ti -1c
.RI "#define \fBFONT_FLAG_ITALIC\fP   (0x02)"
.br
.ti -1c
.RI "#define \fBFONT_FLAG_UNDERLINE\fP   (0x04)"
.br
.ti -1c
.RI "#define \fBFONT_FLAG_SUBSCRIPT\fP   (0x08)"
.br
.ti -1c
.RI "#define \fBFONT_FLAG_SUPERSCRIPT\fP   (0x10)"
.br
.ti -1c
.RI "#define \fBFONT_FLAG_STRIKETHROUGH\fP   (0x20)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBFONT_STRUCT\fP * \fBFont_Load\fP (CHAR *szFontName_, UCHAR ucFontWidth_, UCHAR ucFlags_)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Functions related to accessing fonts. 
.SH "Define Documentation"
.PP 
.SS "#define FONT_ASCII_OFFSET   (0)"
.SS "#define FONT_FLAG_BOLD   (0x01)"
.SS "#define FONT_FLAG_ITALIC   (0x02)"
.SS "#define FONT_FLAG_NORMAL   (0x00)"
.SS "#define FONT_FLAG_STRIKETHROUGH   (0x20)"
.SS "#define FONT_FLAG_SUBSCRIPT   (0x08)"
.SS "#define FONT_FLAG_SUPERSCRIPT   (0x10)"
.SS "#define FONT_FLAG_UNDERLINE   (0x04)"
.SS "#define FONT_PRINTABLE_CHARS   (256)"
.SH "Function Documentation"
.PP 
.SS "const \fBFONT_STRUCT\fP* Font_Load (CHAR * szFontName_, UCHAR ucFontWidth_, UCHAR ucFlags_)"Call this function at the end of main() to start the scheduler.
.PP
\fBParameters:\fP
.RS 4
\fIszFontName_\fP - the name of the font family (alphanumeric) 
.br
\fIucFontWidth_\fP - the point size of the font 
.br
\fIucFlags_\fP - font flags (bold, italic, underline, etc.) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
