.TH "C:/Projects/R3/graphics/font_table.c" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/graphics/font_table.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'font_table.h'\fP
.br
\fC#include 'font_port.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const FONT_RAW_TYPE \fBfntArial_12_0_0_0\fP []"
.br
.ti -1c
.RI "const FONT_RAW_TYPE \fBfntTahoma_12_0_0_0\fP []"
.br
.ti -1c
.RI "const FONT_RAW_TYPE \fBfntFixed_7_0_0_0\fP []"
.br
.ti -1c
.RI "const \fBFONT_STRUCT\fP \fBg_astFonts\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const FONT_RAW_TYPE \fBfntArial_12_0_0_0\fP[]"
.SS "const FONT_RAW_TYPE \fBfntFixed_7_0_0_0\fP[]"
.SS "const FONT_RAW_TYPE \fBfntTahoma_12_0_0_0\fP[]"
.SS "const \fBFONT_STRUCT\fP \fBg_astFonts\fP[]"
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
