.TH "C:/Projects/R3/graphics/font.c" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/graphics/font.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'font_table.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBFONT_STRUCT\fP * \fBFont_Load\fP (CHAR *szFontName_, UCHAR ucFontWidth_, UCHAR ucFlags_)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Functions related to loading font tables 
.SH "Function Documentation"
.PP 
.SS "const \fBFONT_STRUCT\fP * Font_Load (CHAR * szFontName_, UCHAR ucFontWidth_, UCHAR ucFlags_)"Call this function at the end of main() to start the scheduler.
.PP
\fBParameters:\fP
.RS 4
\fIszFontName_\fP - the name of the font family (alphanumeric) 
.br
\fIucFontWidth_\fP - the point size of the font 
.br
\fIucFlags_\fP - font flags (bold, italic, underline, etc.) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
