.TH "C:/Projects/R3/graphics/font_port.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/graphics/font_port.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFONT_RAW_TYPE\fP   UCHAR"
.br
.ti -1c
.RI "#define \fBFont_ReadByte\fP(usAddress, pucFont)   (pucFont[usAddress])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Hardware-specific module for reading bytes from the font table. Abstracting access out at this level allows for different storage classes and methods to be used without requiring the drawing functions to be rewritten. This example uses directly-addressible storage. 
.SH "Define Documentation"
.PP 
.SS "#define FONT_RAW_TYPE   UCHAR"
.SS "#define Font_ReadByte(usAddress, pucFont)   (pucFont[usAddress])"
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
