.TH "C:/Projects/R3/graphics/fooey.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/graphics/fooey.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'display.h'\fP
.br
\fC#include 'colorspace.h'\fP
.br
\fC#include 'fooey_event.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__gui_base_struct\fP"
.br
.ti -1c
.RI "struct \fBGUI_EVENT_QUEUE_STRUCT\fP"
.br
.ti -1c
.RI "struct \fBGUI_MANAGER_STRUCT\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBWIDGET_DEST_BROADCAST\fP   (0xFFFF)"
.br
.ti -1c
.RI "#define \fBWIDGET_DEST_ACTIVE\fP   (0xFFFE)"
.br
.ti -1c
.RI "#define \fBWIDGET_DEST_AUTO\fP   (0xFFFD)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBWIDGET_INIT\fP )(void *pstThis_)"
.br
.ti -1c
.RI "typedef void(* \fBWIDGET_DRAW\fP )(void *pstThis_)"
.br
.ti -1c
.RI "typedef void(* \fBWIDGET_CONTROL\fP )(void *pstThis_, \fBFOOEY_EVENT_STRUCT\fP *pstEvent_)"
.br
.ti -1c
.RI "typedef void(* \fBWIDGET_DESTROY\fP )(void *pstThis_)"
.br
.ti -1c
.RI "typedef struct \fB__gui_base_struct\fP \fBGUI_BASE_STRUCT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFooey_InitDisplay\fP (\fBGUI_MANAGER_STRUCT\fP *pstManager_, \fBDISPLAY_DRIVER_STRUCT\fP *pstDisplay_, \fBFOOEY_EVENT_STRUCT\fP *pstEvents_, UCHAR ucNumEvents_, \fBGUI_BASE_STRUCT\fP *astWidgets_[], USHORT usNumWidgets_)"
.br
.ti -1c
.RI "BOOL \fBFooey_AddWidget\fP (\fBGUI_MANAGER_STRUCT\fP *pstManager_, \fBGUI_BASE_STRUCT\fP *pstWidget_, UCHAR ucGroup_, UCHAR eType_)"
.br
.ti -1c
.RI "BOOL \fBFooey_RemoveWidget\fP (\fBGUI_MANAGER_STRUCT\fP *pstManager_, \fBGUI_BASE_STRUCT\fP *pstWidget_)"
.br
.ti -1c
.RI "void \fBFooey_RenderAll\fP (\fBGUI_MANAGER_STRUCT\fP *pstManager_)"
.br
.ti -1c
.RI "void \fBFooey_RenderChanged\fP (\fBGUI_MANAGER_STRUCT\fP *pstManager_)"
.br
.ti -1c
.RI "BOOL \fBFooey_SendEvent\fP (\fBGUI_MANAGER_STRUCT\fP *pstManager_, \fBFOOEY_EVENT_STRUCT\fP *pstEvent_)"
.br
.ti -1c
.RI "void \fBFooey_ProcessEvents\fP (\fBGUI_MANAGER_STRUCT\fP *pstManager_)"
.br
.ti -1c
.RI "void \fBFooey_GetControlOffsets\fP (\fBGUI_BASE_STRUCT\fP *pstWidget_, USHORT *pusX_, USHORT *pusY_)"
.br
.ti -1c
.RI "void \fBFooey_InitWidget\fP (\fBGUI_BASE_STRUCT\fP *pstWidget_)"
.br
.ti -1c
.RI "void \fBFooey_ResetFocus\fP (\fBGUI_MANAGER_STRUCT\fP *pstManager_)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: The Fooey GUI library - structure and function definitions 
.SH "Define Documentation"
.PP 
.SS "#define WIDGET_DEST_ACTIVE   (0xFFFE)"
.SS "#define WIDGET_DEST_AUTO   (0xFFFD)"
.SS "#define WIDGET_DEST_BROADCAST   (0xFFFF)"
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB__gui_base_struct\fP  \fBGUI_BASE_STRUCT\fP"
.SS "typedef void(* \fBWIDGET_CONTROL\fP)(void *pstThis_, \fBFOOEY_EVENT_STRUCT\fP *pstEvent_)"
.SS "typedef void(* \fBWIDGET_DESTROY\fP)(void *pstThis_)"
.SS "typedef void(* \fBWIDGET_DRAW\fP)(void *pstThis_)"
.SS "typedef void(* \fBWIDGET_INIT\fP)(void *pstThis_)"
.SH "Function Documentation"
.PP 
.SS "BOOL Fooey_AddWidget (\fBGUI_MANAGER_STRUCT\fP * pstManager_, \fBGUI_BASE_STRUCT\fP * pstWidget_, UCHAR ucGroup_, UCHAR eType_)"Adds a widget to a Fooey GUI, initilizing and specializing the control based on the type of widget specified. Once associated with the GUI, it is managed automatcially.
.PP
\fBParameters:\fP
.RS 4
\fIpstManager_\fP - Pointer to the GUI manager base struct 
.br
\fIpstWidget_\fP - Pointer to the widget to add to the managed GUI 
.br
\fIucGroup_\fP - The control group priority level for drawing (high = front, low = back) 
.br
\fIeType_\fP - The control's type 
.RE
.PP
\fBReturns:\fP
.RS 4
TRUE on success, FALSE if the GUI manager is full. 
.RE
.PP

.SS "void Fooey_GetControlOffsets (\fBGUI_BASE_STRUCT\fP * pstWidget_, USHORT * pusX_, USHORT * pusY_)"Determine the X/Y offsets of a widget relative to the root node in the display (usually a surface widget). Scans continuously until the base node is found.
.PP
\fBParameters:\fP
.RS 4
\fIpstWidget_\fP - pointer to the current widget 
.br
\fIpusX_\fP - pointer where the X offset of the control will be returned 
.br
\fIpusY_\fP - pointer where the Y offset of the control will be returned 
.RE
.PP

.SS "void Fooey_InitDisplay (\fBGUI_MANAGER_STRUCT\fP * pstManager_, \fBDISPLAY_DRIVER_STRUCT\fP * pstDisplay_, \fBFOOEY_EVENT_STRUCT\fP * pstEvents_, UCHAR ucNumEvents_, \fBGUI_BASE_STRUCT\fP * astWidgets_[], USHORT usNumWidgets_)"Initializes an instance of a Fooey GUI.
.PP
\fBParameters:\fP
.RS 4
\fIpstManager_\fP - Pointer to the GUI manager base struct 
.br
\fIpstDisplay_\fP - pointer to the display driver to use with this GUI instance 
.br
\fIpstEvents_\fP - pointer to the events buffer for the UI 
.br
\fIucNumEvents_\fP - Number of events in the events buffer 
.br
\fIastWidgets_\fP - Array of pointers to the widgets managed in this UI 
.br
\fIusNumWidgets_\fP - Number of elements in this instance 
.RE
.PP

.SS "void Fooey_InitWidget (\fBGUI_BASE_STRUCT\fP * pstWidget_)"Initialize a widget that has been added to a GUI manager
.PP
\fBParameters:\fP
.RS 4
\fIpstWidget_\fP - pointer to the current widget 
.RE
.PP

.SS "void Fooey_ProcessEvents (\fBGUI_MANAGER_STRUCT\fP * pstManager_)"Processes all queued events in the GUI manager's event buffer.
.PP
\fBParameters:\fP
.RS 4
\fIpstManager_\fP - pointer to the GUI manager containing the controls 
.RE
.PP

.SS "BOOL Fooey_RemoveWidget (\fBGUI_MANAGER_STRUCT\fP * pstManager_, \fBGUI_BASE_STRUCT\fP * pstWidget_)"Removes a widget from a Fooey GUI. Once a control is removed, it is no longer managed by the GUI.
.PP
\fBParameters:\fP
.RS 4
\fIpstManager_\fP - Pointer to the GUI manager base struct 
.br
\fIpstWidget_\fP - Pointer to the widget to remove from the managed GUI 
.RE
.PP
\fBReturns:\fP
.RS 4
TRUE on success, FALSE if the widget is not found 
.RE
.PP

.SS "void Fooey_RenderAll (\fBGUI_MANAGER_STRUCT\fP * pstManager_)"Renders (draws) all GUI elements associated with a UI from lowest group to highest group. Resets the 'bRedraw' property of each control afterward.
.PP
\fBParameters:\fP
.RS 4
\fIpstManager_\fP - pointer to the GUI manager containing the controls to render 
.RE
.PP

.SS "void Fooey_RenderChanged (\fBGUI_MANAGER_STRUCT\fP * pstManager_)"Renders (draws) all of the GUI elements associated with the UI that have their bRedraw property set to TRUE.
.PP
\fBParameters:\fP
.RS 4
\fIpstManager_\fP - pointer to the GUI manager containing the controls to render 
.RE
.PP

.SS "void Fooey_ResetFocus (\fBGUI_MANAGER_STRUCT\fP * pstManager_)"Resets the focus to false for all controls managed by a current UI manager struct.
.PP
\fBParameters:\fP
.RS 4
\fIpstManager_\fP - pointer to the GUI manager struct 
.RE
.PP

.SS "BOOL Fooey_SendEvent (\fBGUI_MANAGER_STRUCT\fP * pstManager_, \fBFOOEY_EVENT_STRUCT\fP * pstEvent_)"Buffers an event to the GUI manager's event queue, which will be processed by a call to \fBFooey_ProcessEvents()\fP.
.PP
\fBParameters:\fP
.RS 4
\fIpstManager_\fP - pointer to the GUI manager containing the controls to render 
.br
\fIpstEvent_\fP - pointer to the event to queue. This is copied in, so the event need not be persistent. 
.RE
.PP
\fBReturns:\fP
.RS 4
TRUE on successful buffering, FALSE on buffer full 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
