.TH "C:/Projects/R3/graphics/fooey_event.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/graphics/fooey_event.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'keycodes.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFOOEY_EVENT_STRUCT\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFOOEY_EVENT_TYPE\fP { \fBFOOEY_EVENT_TICK\fP, \fBFOOEY_EVENT_TYPE_KEYBOARD\fP, \fBFOOEY_EVENT_TYPE_MOUSE\fP, \fBFOOEY_EVENT_TYPES\fP }"
.br
.RI "\fIEvent types. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Description: Define the event types used for manipulating a UI built with Fooey GUI. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFOOEY_EVENT_TYPE\fP"
.PP
Event types. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIFOOEY_EVENT_TICK \fP\fP
.TP
\fB\fIFOOEY_EVENT_TYPE_KEYBOARD \fP\fP
.TP
\fB\fIFOOEY_EVENT_TYPE_MOUSE \fP\fP
.TP
\fB\fIFOOEY_EVENT_TYPES \fP\fP
! Other event type IDs go here. 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
