.TH "GUI_MANAGER_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI_MANAGER_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fooey.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDISPLAY_DRIVER_STRUCT\fP * \fBpstDisplay\fP"
.br
.RI "\fIVideo device associated with the user interface. \fP"
.ti -1c
.RI "\fBGUI_EVENT_QUEUE_STRUCT\fP \fBstEvents\fP"
.br
.RI "\fIPointer to an event struct. \fP"
.ti -1c
.RI "\fBGUI_BASE_STRUCT\fP ** \fBpastScene\fP"
.br
.RI "\fIPointer to a list of widgets. \fP"
.ti -1c
.RI "USHORT \fBusNumWidgets\fP"
.br
.RI "\fINumber of widgets allowed in this manager. \fP"
.ti -1c
.RI "ULONG \fBulCurrentID\fP"
.br
.RI "\fIIndex of control with focus. \fP"
.ti -1c
.RI "UCHAR \fBucMaxGroup\fP"
.br
.RI "\fIMax group. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBGUI_BASE_STRUCT\fP** \fBpastScene\fP"
.PP
Pointer to a list of widgets. 
.SS "\fBDISPLAY_DRIVER_STRUCT\fP* \fBpstDisplay\fP"
.PP
Video device associated with the user interface. 
.SS "\fBGUI_EVENT_QUEUE_STRUCT\fP \fBstEvents\fP"
.PP
Pointer to an event struct. 
.SS "UCHAR \fBucMaxGroup\fP"
.PP
Max group. 
.SS "ULONG \fBulCurrentID\fP"
.PP
Index of control with focus. 
.SS "USHORT \fBusNumWidgets\fP"
.PP
Number of widgets allowed in this manager. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
