.TH "GUI_EVENT_QUEUE_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI_EVENT_QUEUE_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fooey.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFOOEY_EVENT_STRUCT\fP * \fBpstEvents\fP"
.br
.RI "\fIpointer to array of events \fP"
.ti -1c
.RI "UCHAR \fBucSize\fP"
.br
.RI "\fIsize of event data array \fP"
.ti -1c
.RI "UCHAR \fBucHead\fP"
.br
.RI "\fIHead index of circular buffer. \fP"
.ti -1c
.RI "UCHAR \fBucTail\fP"
.br
.RI "\fITail index of circular buffer. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBFOOEY_EVENT_STRUCT\fP* \fBpstEvents\fP"
.PP
pointer to array of events 
.SS "UCHAR \fBucHead\fP"
.PP
Head index of circular buffer. 
.SS "UCHAR \fBucSize\fP"
.PP
size of event data array 
.SS "UCHAR \fBucTail\fP"
.PP
Tail index of circular buffer. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
