.TH "HEAP_INIT_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HEAP_INIT_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <heap.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusNumBlocks\fP"
.br
.RI "\fINumber of elements in this block. \fP"
.ti -1c
.RI "USHORT \fBusBlockSize\fP"
.br
.RI "\fISize of the elements in this block. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "USHORT \fBusBlockSize\fP"
.PP
Size of the elements in this block. 
.SS "USHORT \fBusNumBlocks\fP"
.PP
Number of elements in this block. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
