.TH "HEAP_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HEAP_STRUCT \- 
.PP
< Defines the structure of the heap as a whole  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <heap.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBHEAP_BLOCK_STRUCT\fP \fBastHeapElements\fP [HEAP_NUM_ELEMENTS]"
.br
.RI "\fIArray of heap block elements. \fP"
.ti -1c
.RI "UCHAR \fBaucPool\fP [HEAP_SIZE_BYTES]"
.br
.RI "\fIRaw data pool. \fP"
.in -1c
.SH "Detailed Description"
.PP 
< Defines the structure of the heap as a whole 
.SH "Field Documentation"
.PP 
.SS "\fBHEAP_BLOCK_STRUCT\fP \fBastHeapElements\fP[HEAP_NUM_ELEMENTS]"
.PP
Array of heap block elements. 
.SS "UCHAR \fBaucPool\fP[HEAP_SIZE_BYTES]"
.PP
Raw data pool. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
