.TH "C:/Projects/R3/kernel/heap.c" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/kernel/heap.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'taskport.h'\fP
.br
\fC#include 'heap.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHeap_Init\fP (void)"
.br
.ti -1c
.RI "UCHAR * \fBHeap_Alloc\fP (USHORT usSize_)"
.br
.ti -1c
.RI "void \fBHeap_Free\fP (void *pvData_)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Static block-size heap implementation 
.SH "Function Documentation"
.PP 
.SS "UCHAR * Heap_Alloc (USHORT usSize_)"Allocates a single block of memory from the heap based on the required size (if one is available).
.PP
\fBParameters:\fP
.RS 4
\fIusSize_\fP - the size of the block to allocate 
.RE
.PP
\fBReturns:\fP
.RS 4
pointer to the block of newly-allocated memory, or NULL on failure 
.RE
.PP

.SS "void Heap_Free (void * pvData_)"De-allocates a previously allocated block of memory based on the address given.
.PP
\fBParameters:\fP
.RS 4
\fIpvData_\fP - pointer to the previously-allocated memory block 
.RE
.PP

.SS "void Heap_Init (void)"Initializes each heap block header and zeros out the memory pool used for dynamic memory allocation. 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
