.TH "HEAP_BLOCK_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HEAP_BLOCK_STRUCT \- 
.PP
< Defines the structure of a heap block  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <heap.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusSize\fP"
.br
.RI "\fISize of the heap block in bytes. \fP"
.ti -1c
.RI "USHORT \fBusOffset\fP"
.br
.RI "\fIOffset of the heap block in the array. \fP"
.ti -1c
.RI "BOOL \fBbInUse\fP"
.br
.RI "\fIIn-use flag. \fP"
.in -1c
.SH "Detailed Description"
.PP 
< Defines the structure of a heap block 
.SH "Field Documentation"
.PP 
.SS "BOOL \fBbInUse\fP"
.PP
In-use flag. 
.SS "USHORT \fBusOffset\fP"
.PP
Offset of the heap block in the array. 
.SS "USHORT \fBusSize\fP"
.PP
Size of the heap block in bytes. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
