.TH "C:/Projects/R3/port/AVR_GCC/atmega328p/kernelwdt.c" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/port/AVR_GCC/atmega328p/kernelwdt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'kernelcfg.h'\fP
.br
\fC#include 'taskport.h'\fP
.br
\fC#include <avr\\io.h>\fP
.br
\fC#include <avr\\interrupt.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBWDT_PERIOD\fP   (0x05)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKernelWDT_Config\fP (void)"
.br
.ti -1c
.RI "void \fBKernelWDT_Start\fP (void)"
.br
.ti -1c
.RI "void \fBKernelWDT_Stop\fP (void)"
.br
.ti -1c
.RI "void \fBKernelWDT_Kick\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define WDT_PERIOD   (0x05)"
.SH "Function Documentation"
.PP 
.SS "void KernelWDT_Config (void)"
.SS "void KernelWDT_Kick (void)"
.SS "void KernelWDT_Start (void)"
.SS "void KernelWDT_Stop (void)"
.PP
! Must do this in critical seciton as the WDT clear enable only ! exists for 4 clock cycles !! 
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
