.TH "C:/Projects/R3/port/AVR_GCC/atmega328p/kerneltimer.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/port/AVR_GCC/atmega328p/kerneltimer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKernelTimer_Config\fP (void)"
.br
.ti -1c
.RI "void \fBKernelTimer_Start\fP (void)"
.br
.ti -1c
.RI "void \fBKernelTimer_Stop\fP (void)"
.br
.ti -1c
.RI "void \fBKernelTimer_DI\fP (void)"
.br
.ti -1c
.RI "void \fBKernelTimer_EI\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KernelTimer_Config (void)"
.SS "void KernelTimer_DI (void)"
.SS "void KernelTimer_EI (void)"
.SS "void KernelTimer_Start (void)"
.SS "void KernelTimer_Stop (void)"
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
