.TH "C:/Projects/R3/port/AVR_GCC/atmega328p/kernelswi.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/port/AVR_GCC/atmega328p/kernelswi.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKernelSWI_Config\fP (void)"
.br
.ti -1c
.RI "void \fBKernelSWI_Start\fP (void)"
.br
.ti -1c
.RI "void \fBKernelSWI_Stop\fP (void)"
.br
.ti -1c
.RI "void \fBKernelSWI_Clear\fP (void)"
.br
.ti -1c
.RI "void \fBKernelSWI_Trigger\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KernelSWI_Clear (void)"
.SS "void KernelSWI_Config (void)"
.SS "void KernelSWI_Start (void)"
.SS "void KernelSWI_Stop (void)"
.SS "void KernelSWI_Trigger (void)"
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
