.TH "MESSAGE_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MESSAGE_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <message.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEVENT_STRUCT\fP * \fBpstEvents\fP"
.br
.RI "\fIPointer to the message/event queue. \fP"
.ti -1c
.RI "USHORT \fBusSize\fP"
.br
.RI "\fISize of the message/event queue. \fP"
.ti -1c
.RI "USHORT \fBusHead\fP"
.br
.RI "\fIHead index of the queue. \fP"
.ti -1c
.RI "USHORT \fBusTail\fP"
.br
.RI "\fITail index of the queue. \fP"
.ti -1c
.RI "BOOL \fBbEmpty\fP"
.br
.RI "\fIBuffer-empty flag. \fP"
.ti -1c
.RI "BOOL \fBbFull\fP"
.br
.RI "\fIBuffer-full flag. \fP"
.ti -1c
.RI "\fBSEMAPHORE_STRUCT\fP \fBstSem\fP"
.br
.RI "\fISemaphore associated with the message/event queue. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Message queue - contains a circular buffer of event data specified by an owner task. 
.SH "Field Documentation"
.PP 
.SS "BOOL \fBbEmpty\fP"
.PP
Buffer-empty flag. 
.SS "BOOL \fBbFull\fP"
.PP
Buffer-full flag. 
.SS "\fBEVENT_STRUCT\fP* \fBpstEvents\fP"
.PP
Pointer to the message/event queue. 
.SS "\fBSEMAPHORE_STRUCT\fP \fBstSem\fP"
.PP
Semaphore associated with the message/event queue. 
.SS "USHORT \fBusHead\fP"
.PP
Head index of the queue. 
.SS "USHORT \fBusSize\fP"
.PP
Size of the message/event queue. 
.SS "USHORT \fBusTail\fP"
.PP
Tail index of the queue. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
