.TH "MUTEX_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MUTEX_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mutex.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusSem\fP"
.br
.ti -1c
.RI "UCHAR \fBucMaxPri\fP"
.br
.ti -1c
.RI "\fBTASK_STRUCT\fP * \fBpstTask\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBTASK_STRUCT\fP* \fBpstTask\fP"
.SS "UCHAR \fBucMaxPri\fP"
.SS "USHORT \fBusSem\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
