.TH "PLUMB_TABLE_ENTRY" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PLUMB_TABLE_ENTRY \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <plumber.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTASK_STRUCT\fP * \fBpstTask\fP"
.br
.RI "\fIDestination task/service. \fP"
.ti -1c
.RI "\fBPLUMB_STRUCT\fP * \fBpstPlumb\fP"
.br
.RI "\fIPointer to the first output pipe. \fP"
.ti -1c
.RI "\fBSEMAPHORE_STRUCT\fP * \fBpstSem\fP"
.br
.RI "\fISemaphore for the pipe. \fP"
.ti -1c
.RI "\fBPLUMB_STATE\fP \fBeState\fP"
.br
.RI "\fIState variable. \fP"
.ti -1c
.RI "USHORT \fBusPortNum\fP"
.br
.RI "\fIPort Number. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This struct defines an entry in the plumbing table 
.SH "Field Documentation"
.PP 
.SS "\fBPLUMB_STATE\fP \fBeState\fP"
.PP
State variable. 
.SS "\fBPLUMB_STRUCT\fP* \fBpstPlumb\fP"
.PP
Pointer to the first output pipe. 
.SS "\fBSEMAPHORE_STRUCT\fP* \fBpstSem\fP"
.PP
Semaphore for the pipe. 
.SS "\fBTASK_STRUCT\fP* \fBpstTask\fP"
.PP
Destination task/service. 
.SS "USHORT \fBusPortNum\fP"
.PP
Port Number. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
