.TH "C:/Projects/R3/services/plumber.c" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/services/plumber.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'task.h'\fP
.br
\fC#include 'taskport.h'\fP
.br
\fC#include 'plumber.h'\fP
.br
\fC#include 'semaphore.h'\fP
.br
\fC#include 'mutex.h'\fP
.br
\fC#include 'kernelcfg.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPlumber_CreateTask\fP (void)"
.br
.ti -1c
.RI "\fBPLUMB_RETURN\fP \fBPlumber_InitPipe\fP (\fBPLUMB_STRUCT\fP *pstPlumb_)"
.br
.ti -1c
.RI "\fBPLUMB_RETURN\fP \fBPlumber_AddToList\fP (\fBTASK_STRUCT\fP *pstTask_, USHORT usPortNum_, \fBSEMAPHORE_STRUCT\fP *pstSem_)"
.br
.ti -1c
.RI "\fBPLUMB_RETURN\fP \fBPlumber_OpenPort\fP (USHORT usPort_)"
.br
.ti -1c
.RI "\fBPLUMB_RETURN\fP \fBPlumber_ClosePort\fP (USHORT usPort_)"
.br
.ti -1c
.RI "\fBPLUMB_RETURN\fP \fBPlumber_WriteToPort\fP (UCHAR *pucData_, UCHAR ucLen_, USHORT usPort_)"
.br
.ti -1c
.RI "void \fBPlumber_FreePipe\fP (\fBPLUMB_STRUCT\fP *pstPipe_)"
.br
.ti -1c
.RI "\fBPLUMB_STRUCT\fP * \fBPlumber_ClaimPipe\fP (\fBTASK_STRUCT\fP *pstTask_, USHORT usPort_)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Implements interprocess communication using plumbing. A table is set up containing a list of tasks listening on a list of ports (1-65535). Multiple tasks can listen to the same ports, and in this fashion, data is copied from a single writer to multiple readers, each reader getting its own copy of the data. This module is completely threadsafe as it is implemented as a highest-priotiy task, where the temporary buffers are locked by Mutex, and the message processing itself is initialized by posting a Semaphore. 
.SH "Function Documentation"
.PP 
.SS "\fBPLUMB_RETURN\fP Plumber_AddToList (\fBTASK_STRUCT\fP * pstTask_, USHORT usPortNum_, \fBSEMAPHORE_STRUCT\fP * pstSem_)"Add a pipe to the plumbing table
.PP
\fBParameters:\fP
.RS 4
\fIpstTask_\fP - the task to associate with the pipe entry 
.br
\fIusPortNum_\fP - the port number for the pipe 
.br
\fIpstSem_\fP - the semaphore to pend/post on 
.RE
.PP
\fBReturns:\fP
.RS 4
PLUMB_RETURN - returns PLUMB_OK on success, PLUMB_FAIL_LIST_FAIL on list full 
.RE
.PP

.SS "\fBPLUMB_STRUCT\fP * Plumber_ClaimPipe (\fBTASK_STRUCT\fP * pstTask_, USHORT usPort_)"Searches through the plumbing table for a pipe on the task or port combination specified. Returns a handle to the pipe if successful, else, NULL.
.PP
\fBParameters:\fP
.RS 4
\fIpstTask_\fP - handle to the task requesting the pipe 
.br
\fIusPort_\fP - port number of the pipe to request 
.RE
.PP
\fBReturns:\fP
.RS 4
PLUMB_STRUCT* - the handle of the first valid pipe 
.RE
.PP

.SS "\fBPLUMB_RETURN\fP Plumber_ClosePort (USHORT usPort_)"Close the pipe specified
.PP
\fBParameters:\fP
.RS 4
\fIusPort_\fP - the port to close 
.RE
.PP
\fBReturns:\fP
.RS 4
PLUMB_RETURN - returns PLUMB_OK on success, PLUMB_FAIL_* on failure 
.RE
.PP

.SS "void Plumber_CreateTask (void)"Create the plumber task and add it to the scheduler 
.SS "void Plumber_FreePipe (\fBPLUMB_STRUCT\fP * pstPipe_)"Deallocates a previously allocated pipe for future use.
.PP
\fBParameters:\fP
.RS 4
\fIpstPipe_\fP - free a pipe that`s been allocated. 
.RE
.PP

.SS "\fBPLUMB_RETURN\fP Plumber_InitPipe (\fBPLUMB_STRUCT\fP * pstPlumb_)"Initialize a pipe used by the plumber
.PP
\fBParameters:\fP
.RS 4
\fIpstPlumb_\fP - the pipe to initialize 
.RE
.PP
\fBReturns:\fP
.RS 4
PLUMB_RETURN - returns PLUMB_OK on success 
.RE
.PP

.SS "\fBPLUMB_RETURN\fP Plumber_OpenPort (USHORT usPort_)"Open the pipe specified
.PP
\fBParameters:\fP
.RS 4
\fIusPort_\fP - the port number to open 
.RE
.PP
\fBReturns:\fP
.RS 4
PLUMB_RETURN - returns PLUMB_OK on success, PLUMB_FAIL_* on failure 
.RE
.PP

.SS "\fBPLUMB_RETURN\fP Plumber_WriteToPort (UCHAR * pucData_, UCHAR ucLen_, USHORT usPort_)"Write a packet to the specified port
.PP
\fBParameters:\fP
.RS 4
\fIpucData_\fP - pointer to the data to send 
.br
\fIucLen_\fP - the length of the data packet 
.br
\fIusPort_\fP - the port to send the data to 
.RE
.PP
\fBReturns:\fP
.RS 4
PLUMB_RETURN - returns PLUMB_OK on success, PLUMB_FAIL_* on failure 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
