.TH "PTASK_LIST_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PTASK_LIST_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ptask.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "UCHAR \fBucSize\fP"
.br
.RI "\fINumber of tasks. \fP"
.ti -1c
.RI "UCHAR \fBucCurrentTask\fP"
.br
.RI "\fITask index currently being executing. \fP"
.ti -1c
.RI "\fBPTASK_STRUCT\fP ** \fBpstTasks\fP"
.br
.RI "\fIPointer to array of tasks. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPTASK_STRUCT\fP** \fBpstTasks\fP"
.PP
Pointer to array of tasks. 
.SS "UCHAR \fBucCurrentTask\fP"
.PP
Task index currently being executing. 
.SS "UCHAR \fBucSize\fP"
.PP
Number of tasks. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
