.TH "PTASK_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PTASK_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ptask.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "UCHAR \fBucPriority\fP"
.br
.RI "\fIPriority of the ptask. \fP"
.ti -1c
.RI "\fBPTASK_EVENT_STRUCT\fP * \fBpstEvents\fP"
.br
.RI "\fIPointer to the task's event queue. \fP"
.ti -1c
.RI "\fBPTASK_FUNCTION\fP \fBpfHandler\fP"
.br
.RI "\fIPointer to the task function. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPTASK_FUNCTION\fP \fBpfHandler\fP"
.PP
Pointer to the task function. 
.SS "\fBPTASK_EVENT_STRUCT\fP* \fBpstEvents\fP"
.PP
Pointer to the task's event queue. 
.SS "UCHAR \fBucPriority\fP"
.PP
Priority of the ptask. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
