.TH "PTASK_EVENT_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PTASK_EVENT_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ptask.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT * \fBpusEventID\fP"
.br
.RI "\fIArray of event IDs. \fP"
.ti -1c
.RI "USHORT * \fBpusEventData\fP"
.br
.RI "\fIArray of event data. \fP"
.ti -1c
.RI "UCHAR \fBucNumEvents\fP"
.br
.RI "\fISize of the event buffer. \fP"
.ti -1c
.RI "UCHAR \fBucHead\fP"
.br
.RI "\fIHead index in the event buffer (circular). \fP"
.ti -1c
.RI "UCHAR \fBucTail\fP"
.br
.RI "\fITail index of the event buffer (circular). \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "USHORT* \fBpusEventData\fP"
.PP
Array of event data. 
.SS "USHORT* \fBpusEventID\fP"
.PP
Array of event IDs. 
.SS "UCHAR \fBucHead\fP"
.PP
Head index in the event buffer (circular). 
.SS "UCHAR \fBucNumEvents\fP"
.PP
Size of the event buffer. 
.SS "UCHAR \fBucTail\fP"
.PP
Tail index of the event buffer (circular). 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
