.TH "RTC_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtc.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBuiYear\fP:12"
.br
.RI "\fIYears 0-4095. \fP"
.ti -1c
.RI "unsigned int \fBuiMonth\fP:4"
.br
.RI "\fIMonth 0-11 (use the enumerated values). \fP"
.ti -1c
.RI "unsigned int \fBuiDay\fP:5"
.br
.RI "\fIDay 0-30 (0 is the first day of the month). \fP"
.ti -1c
.RI "unsigned int \fBuiHour\fP:5"
.br
.RI "\fIHour 0-23. \fP"
.ti -1c
.RI "unsigned int \fBuiMinute\fP:6"
.br
.RI "\fIMinute 0-59. \fP"
.ti -1c
.RI "unsigned int \fBuiSecond\fP:6"
.br
.RI "\fISecond 0-59. \fP"
.ti -1c
.RI "unsigned int \fBuiTicks\fP:16"
.br
.RI "\fITicks 0-65535. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBuiDay\fP"
.PP
Day 0-30 (0 is the first day of the month). 
.SS "unsigned int \fBuiHour\fP"
.PP
Hour 0-23. 
.SS "unsigned int \fBuiMinute\fP"
.PP
Minute 0-59. 
.SS "unsigned int \fBuiMonth\fP"
.PP
Month 0-11 (use the enumerated values). 
.SS "unsigned int \fBuiSecond\fP"
.PP
Second 0-59. 
.SS "unsigned int \fBuiTicks\fP"
.PP
Ticks 0-65535. 
.SS "unsigned int \fBuiYear\fP"
.PP
Years 0-4095. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
