.TH "SEMAPHORE_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SEMAPHORE_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <semaphore.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusSem\fP"
.br
.RI "\fISemaphore value (0 or 1 for binary semaphores). \fP"
.ti -1c
.RI "USHORT \fBusMax\fP"
.br
.RI "\fIMaximum semaphore value. \fP"
.ti -1c
.RI "\fBTASK_STRUCT\fP * \fBpstTask\fP"
.br
.RI "\fIPointer to the first task in the semaphore wait list. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBTASK_STRUCT\fP* \fBpstTask\fP"
.PP
Pointer to the first task in the semaphore wait list. 
.SS "USHORT \fBusMax\fP"
.PP
Maximum semaphore value. 
.SS "USHORT \fBusSem\fP"
.PP
Semaphore value (0 or 1 for binary semaphores). 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
