.TH "C:/Projects/R3/port/AVR_GCC/atmega328p/taskport.c" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/port/AVR_GCC/atmega328p/taskport.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include 'taskport.h'\fP
.br
\fC#include 'task.h'\fP
.br
\fC#include 'kernelswi.h'\fP
.br
\fC#include 'kerneltimer.h'\fP
.br
\fC#include 'kernelcfg.h'\fP
.br
\fC#include 'timer.h'\fP
.br
\fC#include <avr\\io.h>\fP
.br
\fC#include <avr\\interrupt.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTask_InitStack\fP (\fBTASK_STRUCT\fP *pstTask_)"
.br
.ti -1c
.RI "void \fBTask_StartTasks\fP (void)"
.br
.ti -1c
.RI "\fBISR\fP (INT0_vect)"
.br
.ti -1c
.RI "\fBISR\fP (TIMER1_COMPA_vect)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTASK_STRUCT\fP * \fBpstCurrentTask\fP"
.br
.ti -1c
.RI "SHORT \fBsCriticalCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: AVRMega implementation of context switching 
.SH "Function Documentation"
.PP 
.SS "ISR (TIMER1_COMPA_vect)"Timer interrupt ISR - causes a tick, which may cause a context switch 
.SS "ISR (INT0_vect)"SWI using INT0 - used to trigger a context switch 
.SS "void Task_InitStack (\fBTASK_STRUCT\fP * pstTask_)"This function initializes the stack of a task
.PP
\fBParameters:\fP
.RS 4
\fI*pstTask_\fP - the task whose stack we wish to initialize. 
.RE
.PP

.SS "void Task_StartTasks (void)"Call this function at the end of main() to start the scheduler. 
.SH "Variable Documentation"
.PP 
.SS "\fBTASK_STRUCT\fP* \fBpstCurrentTask\fP"
.SS "SHORT \fBsCriticalCount\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
