.TH "TIMER_STRUCT" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMER_STRUCT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timer.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusTicks\fP"
.br
.RI "\fITicks between timer calls. \fP"
.ti -1c
.RI "USHORT \fBusOffset\fP"
.br
.RI "\fITimer Phase Offset (for timer load-balancing). \fP"
.ti -1c
.RI "USHORT \fBusTickCount\fP"
.br
.RI "\fITimer's own tick count. \fP"
.ti -1c
.RI "\fBTIMER_STATE\fP \fBeState\fP"
.br
.RI "\fITimer state. \fP"
.ti -1c
.RI "\fBTIMER_CALLBACK\fP \fBpfCallback\fP"
.br
.RI "\fICallback Function (Lightweight Thread). \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBTIMER_STATE\fP \fBeState\fP"
.PP
Timer state. 
.SS "\fBTIMER_CALLBACK\fP \fBpfCallback\fP"
.PP
Callback Function (Lightweight Thread). 
.SS "USHORT \fBusOffset\fP"
.PP
Timer Phase Offset (for timer load-balancing). 
.SS "USHORT \fBusTickCount\fP"
.PP
Timer's own tick count. 
.SS "USHORT \fBusTicks\fP"
.PP
Ticks between timer calls. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
