.TH "C:/Projects/R3/pipsqueak/types.h" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/R3/pipsqueak/types.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLONG\fP   long"
.br
.ti -1c
.RI "#define \fBULONG\fP   unsigned long"
.br
.ti -1c
.RI "#define \fBSHORT\fP   short"
.br
.ti -1c
.RI "#define \fBUSHORT\fP   unsigned short"
.br
.ti -1c
.RI "#define \fBBYTE\fP   char"
.br
.ti -1c
.RI "#define \fBCHAR\fP   char"
.br
.ti -1c
.RI "#define \fBUCHAR\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBINT\fP   int"
.br
.ti -1c
.RI "#define \fBFLOAT\fP   float"
.br
.ti -1c
.RI "#define \fBDOUBLE\fP   double"
.br
.ti -1c
.RI "#define \fBWORD\fP   UCHAR"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define BYTE   char"
.SS "#define CHAR   char"
.SS "#define DOUBLE   double"
.SS "#define FLOAT   float"
.SS "#define INT   int"
.SS "#define LONG   long"
.SS "#define SHORT   short"
.SS "#define UCHAR   unsigned char"
.SS "#define ULONG   unsigned long"
.SS "#define USHORT   unsigned short"
.SS "#define WORD   UCHAR"
.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
