.TH "Watchdog_Task" 3 "20 Mar 2010" "Version R3" "FunkOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Watchdog_Task \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <watchdog.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "USHORT \fBusTimeout\fP"
.br
.ti -1c
.RI "USHORT \fBusCurrentTime\fP"
.br
.ti -1c
.RI "\fBWATCHDOG_STATE\fP \fBeState\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBWATCHDOG_STATE\fP \fBeState\fP"
.SS "USHORT \fBusCurrentTime\fP"
.SS "USHORT \fBusTimeout\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FunkOS from the source code.
